CREATE MATERIALIZED VIEW VW_CUSTO_LAVOURA
REFRESH FORCE ON DEMAND
START WITH SYSDATE  NEXT SYSDATE + 5/24/60 
AS
SELECT
       COD_SAFRA,
       DESCRICAO_SAFRA,
       DESC_REGIAO,
       SIGLA_REGIAO,
       COD_EMPRESA,
       NOME_EMPRESA,
       SIGLA_EMPRESA,
       SEQ_PLA_AGLOMERADO,
       DESC_AGLOMERADO,
       SIGLA_AGLOMERADO,
       SEQ_PLA_FAZENDA,
       DESC_FAZENDA,
       SIGLA_FAZENDA,
       SEQ_PLA_TALHAO,
       NUMERO_TALHAO,
       DESC_TALHAO,
       SEQ_PLA_TIPO_CULT,
       DESC_CULTURA,
       SEQ_PLA_VARIEDADE,
       DESC_FINALIDADE,
       DESC_VARIEDADE,
       DATA_CUMPR,
       DATA_LANCAMENTO,
       DATA_EMISSAO,
       NR_CONTROLE,
       DESCRICAO_FAMILIA,
       DESCRICAO_GRUPO,
       CUSTO_HA,
       DESC_SUB_GRUPO,
       SEQ_PLA_PRODUTO,
       DESCRICAO_PRODUTO,
       SIGLA_UNIDADE,
       CASE WHEN LOTE IS NULL THEN '' ELSE LOTE END AS LOTE,
       QTDE_HA,
       QTD_HA_EFETIVO,
       CASE WHEN QUANTIDADE_RECOMENDADA IS NULL THEN 0 ELSE QUANTIDADE_RECOMENDADA END AS QUANTIDADE_RECOMENDADA,
       CASE WHEN DOSE_RECOMENDADA IS NULL THEN 0 ELSE DOSE_RECOMENDADA END AS DOSE_RECOMENDADA,
       QUANTIDADE,
       DOSE,
       CASE WHEN VAZAO IS NULL THEN 0 ELSE VAZAO END AS VAZAO,
       DESC_GRUPO_TAREFA,
       DESC_TAREFA,
       NOME,
       FORMA_APLICACAO,
       EXECUTOR
FROM (
SELECT
       SA.COD_SAFRA,
       SA.DESCRICAO_SAFRA,
       RE.DESC_REGIAO,
       RE.SIGLA_REGIAO,
       EM.COD_EMPRESA,
       EM.NOME_EMPRESA,
       EM.SIGLA_EMPRESA,
       AG.SEQ_PLA_AGLOMERADO,
       AG.DESC_AGLOMERADO,
       AG.SIGLA_AGLOMERADO,
       FA.SEQ_PLA_FAZENDA,
       FA.DESC_FAZENDA,
       FA.SIGLA_FAZENDA,
       TA.SEQ_PLA_TALHAO,
       TA.NUMERO_TALHAO,
       TA.DESC_TALHAO,
       TC.SEQ_PLA_TIPO_CULT,
       TC.DESC_CULTURA,
       FN.DESCRICAO AS DESC_FINALIDADE,
       (CASE
        WHEN TSA.SEQ_PLA_VARIEDADE IS NULL THEN
        (SELECT AGNEW.WM_CONCAT(DISTINCT V.SEQ_PLA_VARIEDADE)
        FROM AGNEW.RECEITUARIO_SEMENTE S, AGNEW.UBS_VARIEDADES V
        WHERE S.SEQ_PLA_ORDEM = OS.SEQ_PLA_ORDEM
        AND S.SEQ_PLA_VARIEDADE = V.SEQ_PLA_VARIEDADE)
        ELSE
          VAA.SEQ_PLA_VARIEDADE
        END)  AS SEQ_PLA_VARIEDADE,
       (CASE
        WHEN TSA.SEQ_PLA_VARIEDADE IS NULL THEN
        (SELECT AGNEW.WM_CONCAT(DISTINCT V.DESC_VARIEDADE)
        FROM AGNEW.RECEITUARIO_SEMENTE S, AGNEW.UBS_VARIEDADES V
        WHERE S.SEQ_PLA_ORDEM = OS.SEQ_PLA_ORDEM
        AND S.SEQ_PLA_VARIEDADE = V.SEQ_PLA_VARIEDADE)
        ELSE
          VAA.DESC_VARIEDADE
        END)  AS DESC_VARIEDADE,
       OST.EFETIVO_CUMPRIMENTO as DATA_CUMPR,
       OST.DATA_LANCAMENTO,
       OS.DATA_EMISSAO,
       OS.NR_CONTROLE,
       FAM.DESCRICAO_FAMILIA,
       GR.DESCRICAO_GRUPO,
       case when esi.quantidade <> 0
        then (NVL(ESI.CUSTO_TOTAL,0)/NVL(ESI.QUANTIDADE,0))
        else 0 end AS CUSTO_TOTAL,
       case when esi.quantidade <> 0
        then ( NVL(ESI.CUSTO_TOTAL,0)/NVL(ESI.QUANTIDADE,0) * NVL(LTA.QUANTIDADE,0))
        else 0 end   AS VALOR_TOTAL,
       case when esi.quantidade <> 0
        then (NVL(ESI.CUSTO_TOTAL,0)/NVL(ESI.QUANTIDADE,0) * NVL(LTA.QUANTIDADE,0)    / OST.QTD_HA_EFETIVO)
        else 0 end AS CUSTO_HA,
       SG.DESC_SUB_GRUPO,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SIGLA_UNIDADE,
       LT.LOTE,
       TA.QTDE_HA,
       OST.QTD_HA_EFETIVO,
       0 QUANTIDADE_RECOMENDADA,
       0 DOSE_RECOMENDADA,
       LTA.QUANTIDADE,
       DECODE(NVL(OST.QTD_HA_EFETIVO,0),0,0,NVL(LTA.QUANTIDADE,0)/NVL(OST.QTD_HA_EFETIVO,0)) DOSE,
       OS.VAZAO,
       GT.DESC_GRUPO_TAREFA,
       TAR.DESC_TAREFA,
       FF.NOME,
       DECODE(TAR.DEFENSIVO,'S',
              DECODE(OS.FORMA_APLICACAO_DEFENSIVO,1,'A?rea',2,'Terrestre',3,'A Definir'),
              DECODE(OS.FORMA_APLICACAO_FERTILIZANTE,1,'A?rea',2,'A Lan?o',3,'Em Linha',4,'A Definir')) FORMA_APLICACAO,
       FF1.NOME AS EXECUTOR
FROM AGNEW.ORDEM_SERVICO         OS,
     AGNEW.ORDEM_SERV_TALHOES    OST,
     AGNEW.VINCULA_TAREFA_GRUPO  VTG,
     AGNEW.TAREFAS               TAR,
     AGNEW.TALHOES_SAFRA         TS,
     AGNEW.GRUPO_TAREFAS         GT,
     AGNEW.FUNCIONARIOS_FAZENDA  FF,
     AGNEW.FUNCIONARIOS_FAZENDA FF1,
     AGNEW.TALHOES_SAFRA        TSA,
     AGNEW.UBS_VARIEDADES       VAA,
     AGNEW.LIGA_TALHAO_APLICACAO LTA,
     AGNEW.EST_SAIDAS_ITENS      ESI,
     AGNEW.EST_SAIDAS            ES,
     AGNEW.SAFRAS               SA,
     AGNEW.EMPRESAS             EM,
     AGNEW.FILIAIS              FI,
     AGNEW.AGLOMERADOS          AG,
     AGNEW.REGIOES_GERENCIAIS   RE,
     AGNEW.FAZENDAS             FA,
     AGNEW.TALHOES              TA,
     AGNEW.TIPO_CULTURA         TC,
     AGNEW.PRODUTOS             PR,
     AGNEW.SUB_GRUPO            SG,
     AGNEW.GRUPO                GR,
     AGNEW.FAMILIAS             FAM,
     AGNEW.UNIDADE_PRODUTO      UN,
     AGNEW.PRODUTOS_INSUMOS     PRI,
     AGNEW.VAZAO                VA,
     AGNEW.FINALIDADE_ORDEM_SERVICO FN,
     (SELECT esl.seq_pla_sai_item,
               AGNEW.WM_CONCAT(UL.NR_LOTE) as lote
          FROM AGNEW.EST_SAIDAS_LOTES ESL, AGNEW.UBS_LOTES UL
         WHERE ESL.SEQ_PLA_LOTES = UL.SEQ_PLA_LOTES
         GROUP BY ESL.SEQ_PLA_SAI_ITEM
         union
        SELECT esl.seq_pla_sai_item,
               AGNEW.WM_CONCAT(pl.lote) as lote
          FROM AGNEW.EST_SAIDAS_LOTES ESL, AGNEW.produto_lotes pl
         WHERE ESL.SEQ_PLA_LOTE_PRODUTO = pl.seq_pla_lote_produto
         GROUP BY ESL.SEQ_PLA_SAI_ITEM) lt
WHERE OS.SEQ_PLA_ORDEM          = OST.SEQ_PLA_ORDEM
  AND OST.SEQ_PLA_ORDEM_TALHOES = TS.SEQ_PLA_ORDEM_PLANTIO(+)
  AND OS.COD_SAFRA              = SA.COD_SAFRA
  AND OS.SEQ_PLA_FAZENDA        = FA.SEQ_PLA_FAZENDA
  AND OS.SEQ_PLA_VINC_TAREFA    = VTG.SEQ_PLA_VINC_TAREFA
  AND OS.SEQ_PLA_FUNCIONARIO    = FF.SEQ_PLA_FUNCIONARIO(+)
    AND OST.SEQ_PLA_TALHAO_SAFRA = TSA.SEQ_PLA_TALHAO_SAFRA(+)
    AND TSA.SEQ_PLA_VARIEDADE  = VAA.SEQ_PLA_VARIEDADE(+)
  AND OS.SEQ_PLA_FINALIDADE = FN.SEQ_PLA_FINALIDADE(+)
  AND VTG.SEQ_PLA_TAREFA        = TAR.SEQ_PLA_TAREFA
  AND VTG.SEQ_PLA_GRUPO_TAREFA  = GT.SEQ_PLA_GRUPO_TAREFA
  AND OST.SEQ_PLA_TALHAO        = TA.SEQ_PLA_TALHAO
  AND FA.SEQ_PLA_AGLOMERADO     = AG.SEQ_PLA_AGLOMERADO
  AND AG.COD_EMPRESA            = EM.COD_EMPRESA
  AND AG.COD_EMPRESA            = FI.COD_EMPRESA
  AND AG.COD_FILIAL             = FI.COD_FILIAL
  AND AG.SEQ_PLA_REGIAO         = RE.SEQ_PLA_REGIAO(+)
  AND OS.SEQ_PLA_TIPO_CULT      = TC.SEQ_PLA_TIPO_CULT
  AND OST.SEQ_PLA_ORDEM_TALHOES = LTA.SEQ_PLA_ORDEM_TALHAO
  AND LTA.SEQ_PLA_SAI_ITEM      = ESI.SEQ_PLA_SAI_ITEM
  AND ESI.SEQ_PLA_SAIDA         = ES.SEQ_PLA_SAIDA
  AND ESI.SEQ_PLA_PRODUTO       = PR.SEQ_PLA_PRODUTO
  AND PR.SEQ_PLA_SUB_GRUPO      = SG.SEQ_PLA_SUB_GRUPO
  AND SG.SEQ_PLA_GRUPO          = GR.SEQ_PLA_GRUPO
  AND GR.SEQ_PLA_FAMILIA        = FAM.SEQ_PLA_FAMILIA
  AND PR.SEQ_PLA_UNIDADE        = UN.SEQ_PLA_UNIDADE
  and OS.Seq_Pla_Executor       = ff1.seq_pla_funcionario (+)
  AND PR.SEQ_PLA_PRODUTO        = PRI.SEQ_PLA_PRODUTO(+)
  AND OS.SEQ_PLA_VAZAO = VA.SEQ_PLA_VAZAO(+)
  AND ESI.SEQ_PLA_SAI_ITEM = LT.SEQ_PLA_SAI_ITEM(+)
  AND OST.EFETIVO = 'S'
  AND OS.DATA_ENCERRAMENTO IS NOT NULL

order by SA.DESCRICAO_SAFRA, FA.SIGLA_FAZENDA, TA.DESC_TALHAO, OST.EFETIVO_CUMPRIMENTO
) X
WHERE X.DESC_VARIEDADE IS NULL;
