CREATE OR REPLACE VIEW VW_CONTAS_PAGAR_MES_DETALHE_PI AS
SELECT FI.DESCRICAO_FILIAL,
       TRUNC(CP.DATA_LCTO) DATA_LCTO,
       CL.NOME_CLIENTE AS FORNECEDOR,
       CP.DOCUMENTO,
       PP.NR_DOCUMENTO AS NR_CHEQUE,
       TRUNC(CP.DATA_VCTO) DATA_VCTO,
       PP.DATA_PGTO AS DATA_BAIXA,
       MO.SIGLA_MOEDA AS MOEDA,
       (NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_DESCONTO,0)-NVL(CP.VALOR_JUROS,0)) AS VALOR_ORIGINAL,
       NVL(CP.VALOR_DESCONTO,0) AS VALOR_DESCONTO,
       NVL(CP.VALOR_JUROS,0) AS VALOR_JUROS,
       NVL(PP.VALOR_PAGO,0) AS VALOR_PAGO,
       0 AS VALOR_RECEBIDO,
       FH.DESC_FIN_HIST AS HIST_LCTO,
       CP.COD_EMPRESA,
       CP.COD_SAFRA,
       CP.COD_FILIAL,
       CASE EXTRACT(MONTH FROM TO_DATE(CP.DATA_LCTO,'DD/MM/RRRR'))
         WHEN 1 THEN 'Jan'
         WHEN 2 THEN 'Fev'
         WHEN 3 THEN 'Mar'
         WHEN 4 THEN 'Abr'
         WHEN 5 THEN 'Mai'
         WHEN 6 THEN 'Jun'
         WHEN 7 THEN 'Jul'
         WHEN 8 THEN 'Ago'
         WHEN 9 THEN 'Set'
         WHEN 10 THEN 'Out'
         WHEN 11 THEN 'Nov'
         WHEN 12 THEN 'Dez'
       END || '/' || EXTRACT(YEAR FROM TO_DATE(CP.DATA_LCTO,'DD/MM/RRRR')) AS MES_ANO
  FROM GUSTAVO.CONTAS_PAGAR       CP,
       GUSTAVO.CLIENTES           CL,
       GUSTAVO.CLIENTES_ENDERECOS CE,
       GUSTAVO.FIN_HISTORICOS     FH,
       GUSTAVO.MOEDAS             MO,
       GUSTAVO.FILIAIS            FI,
       GUSTAVO.EMPRESAS           EP,
       (SELECT PP.SEQ_PLA_PAGAR, TRUNC(PP.DATA_PGTO) DATA_PGTO, TRIM(CH.NR_DOCUMENTO) NR_DOCUMENTO, SUM(NVL(PP.VALOR_PAGO,0)) VALOR_PAGO
          FROM GUSTAVO.PAGAR_PAGTOS  PP,
               GUSTAVO.FIN_MOVIMENTO FM,
               GUSTAVO.FIN_CHEQUES   CH
         WHERE PP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
           AND FM.SEQ_PLA_FIN_CHEQUE = CH.SEQ_PLA_FIN_CHEQUE(+)
         GROUP BY PP.SEQ_PLA_PAGAR, TRUNC(PP.DATA_PGTO), TRIM(CH.NR_DOCUMENTO) ) PP
       /*
       GUSTAVO.PAGAR_PAGTOS       PP,
       GUSTAVO.FIN_MOVIMENTO      FM,
       GUSTAVO.FIN_CHEQUES        CH
       */

 WHERE NVL(CP.CANCELADO,'N') = 'N'
   AND CP.SEQ_PLA_ENDERECO   = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE    = CL.SEQ_PLA_CLIENTE
   AND CP.SEQ_PLA_FIN_HIST   = FH.SEQ_PLA_FIN_HIST  (+)
   AND CP.SEQ_PLA_MOEDA      = MO.SEQ_PLA_MOEDA
   AND CP.COD_FILIAL         = FI.COD_FILIAL
   AND CP.COD_EMPRESA        = EP.COD_EMPRESA
   AND EP.COD_EMPRESA        = FI.COD_EMPRESA
   AND CP.SEQ_PLA_PAGAR      = PP.SEQ_PLA_PAGAR(+)
   /*jhony 29/12/2020 ajustes feitos com base na consulta CP 2 */
   AND UPPER(NVL(CP.FORM_LANCAMENTO,'XXX')) not in ('DFMFINANCIAMENTOS1','DFMFINANCIAMENTOS')
   AND NVL(CP.PREVISAO,'N') = 'N'
   AND NVL(FH.ADIANTAMENTO,'N') <> 'S'
   /**/   
   --AND PP.SEQ_PLA_MOV_FIN    = FM.SEQ_PLA_MOV_FIN(+)
   --AND FM.SEQ_PLA_FIN_CHEQUE = CH.SEQ_PLA_FIN_CHEQUE(+);
