CREATE OR REPLACE VIEW VW_CONTAS_PAGAR_MES_PI AS
SELECT DECODE(MO.SEQ_PLA_MOEDA,'     75601',SUM(NVL(CR.VALOR_DOCUM,0)),0) AS VALOR_DEBITO_REAL,
       DECODE(MO.SEQ_PLA_MOEDA,'      3501',SUM(NVL(CR.VALOR_DOCUM,0)),0) AS VALOR_DEBITO_DOLAR,
       CASE EXTRACT(MONTH FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR'))
         WHEN 1 THEN 'Jan'
         WHEN 2 THEN 'Fev'
         WHEN 3 THEN 'Mar'
         WHEN 4 THEN 'Abr'
         WHEN 5 THEN 'Mai'
         WHEN 6 THEN 'Jun'
         WHEN 7 THEN 'Jul'
         WHEN 8 THEN 'Ago'
         WHEN 9 THEN 'Set'
         WHEN 10 THEN 'Out'
         WHEN 11 THEN 'Nov'
         WHEN 12 THEN 'Dez'
       END AS MES,
       EXTRACT(YEAR FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')) AS ANO,
       TO_CHAR(CR.DATA_LCTO, 'MM/YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''') AS MES_ANO,
       TRUNC(CR.DATA_LCTO) DATA_LCTO,
       CR.COD_EMPRESA,
       CR.COD_SAFRA,
       CR.COD_FILIAL,
       EXTRACT(MONTH FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')) AS MES_NUM,
       (SUBSTR((EXTRACT(YEAR FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR'))),3,2) || LPAD(EXTRACT(MONTH FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')),2,0)) ANO_MES
  FROM GUSTAVO.CONTAS_PAGAR       CR,
       GUSTAVO.CLIENTES           CL,
       GUSTAVO.CLIENTES_ENDERECOS CE,
       GUSTAVO.FIN_HISTORICOS     FH,
       GUSTAVO.MOEDAS             MO
 WHERE NVL(CR.CANCELADO,'N') = 'N'
   AND CR.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
   AND CR.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST(+)
   AND CR.SEQ_PLA_MOEDA     = MO.SEQ_PLA_MOEDA
   /*jhony 29/12/2020 ajustes feitos com base na consulta CP 2 */
   AND UPPER(NVL(CR.FORM_LANCAMENTO,'XXX')) not in ('DFMFINANCIAMENTOS1','DFMFINANCIAMENTOS')
   AND NVL(CR.PREVISAO,'N') = 'N'
   --AND NVL(FH.ADIANTAMENTO,'N') <> 'S'
   /**/
 GROUP BY EXTRACT(MONTH FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')), EXTRACT(YEAR FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')),
       TO_CHAR(CR.DATA_LCTO, 'MM/YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),
       CONCAT(TO_CHAR(CR.DATA_LCTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(CR.DATA_LCTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')),
       CR.COD_EMPRESA, CR.COD_SAFRA, CR.DATA_LCTO, MO.SEQ_PLA_MOEDA,CR.COD_FILIAL,CR.DOCUMENTO,
       (EXTRACT(YEAR FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')) || EXTRACT(MONTH FROM TO_DATE(CR.DATA_LCTO,'DD/MM/RRRR')));
