CREATE MATERIALIZED VIEW GRAFICO_MOV_CAROCO_ALGODAO
REFRESH FORCE ON DEMAND
START WITH TO_DATE('10-09-2020 14:41:02', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE + 5/24/60 
AS
SELECT
  'FARDAO_ENTRADA' AS PRODUTO,
  ET.COD_EMPRESA,
  ET.COD_FILIAL,
  ET.COD_SAFRA,
  SF.DESCRICAO_SAFRA AS SAFRA,
  EP.COD_EMPRESA||FI.COD_FILIAL AS ID_ALGODOEIRA,
  EP.SIGLA_EMPRESA||' - '||FI.SIGLA_FILIAL AS ALGODOEIRA,
  CL.SEQ_PLA_CLIENTE,
  CL.NOME_CLIENTE              AS PRODUTOR,
  ET.DATA_ENTRADA              AS DATA_OPERACAO,
  ET.PESO_LIQUIDO              AS PESO_TOTAL
FROM
  AGRICOLA.ENTRADAS     ET,
  AGRICOLA.CLIENTES_ENDERECOS CE,
  AGRICOLA.CLIENTES           CL,
  AGRICOLA.EMPRESAS           EP,
  AGRICOLA.FILIAIS            FI,
  AGRICOLA.SAFRAS             SF
WHERE
  ET.COD_EMPRESA             = EP.COD_EMPRESA
  AND ET.COD_FILIAL          = FI.COD_FILIAL
  AND FI.COD_EMPRESA         = EP.COD_EMPRESA
  AND ET.COD_SAFRA           = SF.COD_SAFRA
  AND ET.SEQ_PLA_ENDERECO    = CE.SEQ_PLA_ENDERECO
  AND CE.SEQ_PLA_CLIENTE     = CL.SEQ_PLA_CLIENTE
  AND ET.CANCELADO <> 'S'

  UNION ALL

SELECT
  'FARDAO_BENEFICIADO' AS PRODUTO,
  BE.COD_EMPRESA,
  BE.COD_FILIAL,
  BE.COD_SAFRA,
  SF.DESCRICAO_SAFRA AS SAFRA,
  EP.COD_EMPRESA||FI.COD_FILIAL AS ID_ALGODOEIRA,
  EP.SIGLA_EMPRESA||' - '||FI.SIGLA_FILIAL AS ALGODOEIRA,
  CL.SEQ_PLA_CLIENTE,
  CL.NOME_CLIENTE              AS PRODUTOR,
  BE.DATA_BENEFICIAMENTO       AS DATA_OPERACAO,
  TT.PESO_FARDAO               AS PESO_TOTAL
FROM
  AGRICOLA.BENEFICIAMENTO     BE,
  AGRICOLA.CLIENTES_ENDERECOS CE,
  AGRICOLA.CLIENTES           CL,
  AGRICOLA.EMPRESAS           EP,
  AGRICOLA.FILIAIS            FI,
  AGRICOLA.SAFRAS             SF,
  (SELECT ET.PESO_LIQUIDO AS PESO_FARDAO, 1 AS QTD_FARDAO, LIG.SEQ_BENEFICIAMENTO, ET.COD_SAFRA
    FROM AGRICOLA.LIGA_ENTRADA_BENEFICIAMENTO LIG , AGRICOLA.ENTRADAS ET
  WHERE
  ET.SEQ_ENTRADA = LIG.SEQ_ENTRADA
  AND ET.COD_EMPRESA = LIG.ENT_COD_EMPRESA
  AND ET.COD_FILIAL  = LIG.ENT_COD_FILIAL
  AND ET.COD_SAFRA   = LIG.ENT_COD_SAFRA
  AND ET.CANCELADO <> 'S'
  ) TT
WHERE
  BE.COD_EMPRESA             = EP.COD_EMPRESA
  AND BE.COD_FILIAL          = FI.COD_FILIAL
  AND FI.COD_EMPRESA         = EP.COD_EMPRESA
  AND BE.COD_SAFRA           = SF.COD_SAFRA
  AND BE.SEQ_PLA_ENDERECO    = CE.SEQ_PLA_ENDERECO
  AND CE.SEQ_PLA_CLIENTE     = CL.SEQ_PLA_CLIENTE
  AND BE.SEQ_BENEFICIAMENTO = TT.SEQ_BENEFICIAMENTO (+)
  AND BE.COD_SAFRA = TT.COD_SAFRA

UNION ALL

SELECT
  'CAROCO_SAIDA' AS PRODUTO,
  SN.COD_EMPRESA,
  SN.COD_FILIAL,
  CS.COD_SAFRA,
  SF.DESCRICAO_SAFRA AS SAFRA,
  EP.COD_EMPRESA||FI.COD_FILIAL AS ID_ALGODOEIRA,
  EP.SIGLA_EMPRESA||' - '||FI.SIGLA_FILIAL AS ALGODOEIRA,
  CL.SEQ_PLA_CLIENTE,
  CL.NOME_CLIENTE                          AS PRODUTOR,
  SN.DATA_SAIDA                            AS DATA_OPERACAO,
  SN.QUANTIDADE                            AS PESO_TOTAL
FROM AGRICOLA.CONTRATO_CAROCO    CS,
  AGRICOLA.INSTRUCAO_EMBARQUE_CAROCO IEC,
  AGRICOLA.SAIDA_CAROCO       SN,
  AGRICOLA.CLIENTES_ENDERECOS CE,
  AGRICOLA.CLIENTES           CL,
  AGRICOLA.EMPRESAS           EP,
  AGRICOLA.FILIAIS            FI,
  AGRICOLA.SAFRAS             SF
WHERE SN.COD_EMPRESA               = EP.COD_EMPRESA
  AND EP.COD_EMPRESA               = FI.COD_EMPRESA
  AND SN.COD_FILIAL                = FI.COD_FILIAL
  AND CS.SEQ_PLA_CONT_CAROCO       = IEC.SEQ_PLA_CONT_CAROCO
  AND IEC.SEQ_PLA_INSTRUCAO_CAROCO = SN.SEQ_PLA_INSTRUCAO_CAROCO
  AND CS.SEQ_PLA_PRODUTOR          = CE.SEQ_PLA_ENDERECO
  AND CE.SEQ_PLA_CLIENTE           = CL.SEQ_PLA_CLIENTE (+)
  AND SN.COD_SAFRA                 = SF.COD_SAFRA
  AND DECODE(SN.CANCELADO,NULL,'N',SN.CANCELADO)='N'

UNION ALL

SELECT
  'CAROCO_ENTRADA' AS PRODUTO,
  BE.COD_EMPRESA,
  BE.COD_FILIAL,
  BE.COD_SAFRA,
  SF.DESCRICAO_SAFRA AS SAFRA,
  EP.COD_EMPRESA||FI.COD_FILIAL AS ID_ALGODOEIRA,
  EP.SIGLA_EMPRESA||' - '||FI.SIGLA_FILIAL AS ALGODOEIRA,
  CL.SEQ_PLA_CLIENTE,
  CL.NOME_CLIENTE              AS PRODUTOR,
  BE.DATA_BENEFICIAMENTO       AS DATA_OPERACAO,
  BE.QTD_CAROCO                AS PESO_TOTAL
FROM
  AGRICOLA.BENEFICIAMENTO     BE,
  AGRICOLA.CLIENTES_ENDERECOS CE,
  AGRICOLA.CLIENTES           CL,
  AGRICOLA.EMPRESAS           EP,
  AGRICOLA.FILIAIS            FI,
  AGRICOLA.SAFRAS             SF
WHERE
  BE.COD_EMPRESA             = EP.COD_EMPRESA
  AND BE.COD_FILIAL          = FI.COD_FILIAL
  AND FI.COD_EMPRESA         = EP.COD_EMPRESA
  AND BE.COD_SAFRA           = SF.COD_SAFRA
  AND BE.SEQ_PLA_ENDERECO    = CE.SEQ_PLA_ENDERECO
  AND CE.SEQ_PLA_CLIENTE     = CL.SEQ_PLA_CLIENTE
