CREATE MATERIALIZED VIEW GRAFICO_MEDIA_PRODUCAO
REFRESH FORCE ON DEMAND
START WITH TO_DATE('10-09-2020 14:43:47', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE + 5/24/60 
AS
SELECT RO.COD_EMPRESA,
       RO.NOME_EMPRESA,
       RO.COD_FILIAL,
       RO.SIGLA_FILIAL AS DESCRICAO_FILIAL,
       ' ' AS SEQ_PLA_AGLOMERADO,
       ' ' AS DESC_AGLOMERADO,
       RO.COD_SAFRA,
       RO.DESCRICAO_SAFRA,
       RO.SEQ_PLA_FAZENDA,
       RO.SIGLA_FAZENDA,
       RO.DESC_FAZENDA,
       RO.SEQ_PLA_TALHAO,
       RO.NUMERO_TALHAO,
       RO.FINALIZADO,
       RO.SIGLA_UNIDADE,
       RO.DESC_VARIEDADE,
       RO.SEQ_PLA_VARIEDADE,
       RO.DESC_CULTURA,
       RO.SEQ_PLA_TIPO_CULT,
       RO.QTDE_HA,
       RO.KGS_PREV_PRODUCAO,
       ' ' AS OBSERVACOES,
       RO.DESCRICAO_PRODUTO,
       RO.SEQ_PLA_PRODUTO,
       RO.ROMANEIOS,
       RO.SUBTOTAL,
       RO.PESO_BRUTO ,
       RO.DES_UMIDADE,
       RO.DES_IMPUREZA,
       RO.DES_AVARIADO,
       RO.DES_ARDIDO,
       RO.DES_OUTROS,
       RO.DESCONTOS,
       RO.TOTPERUMI,
       RO.TOTUMI,
       ' ' AS PER_UMIDADE,
       ' ' AS PER_IMPUREZA,
       ' ' AS PER_AVARIADO,
       ' ' AS PER_ARDIDO,
       ' ' AS PER_OUTROS,
       RO.PESO_LIQUIDO,
       RO.LIQUIDO_SACAS,
       ' ' AS SACAS_HA
  FROM (SELECT COUNT(RO.SEQ_PLA_ENTRADA) AS ROMANEIOS,
               SUM(RO.PESO_BRUTO) AS PESO_BRUTO,
               SUM(RO.PESO_BRUTO- DECODE(RO.PESO_TARA   ,NULL,0,RO.PESO_TARA   )) AS SUBTOTAL,
               SUM(DECODE(RO.DES_UMIDADE ,NULL,0,RO.DES_UMIDADE )) AS DES_UMIDADE,
               SUM(DECODE(RO.DES_IMPUREZA,NULL,0,RO.DES_IMPUREZA)) AS DES_IMPUREZA,
               SUM(DECODE(RO.DES_AVARIADO,NULL,0,RO.DES_AVARIADO)) AS DES_AVARIADO,
               SUM(DECODE(RO.DES_ARDIDO  ,NULL,0,RO.DES_ARDIDO  )) AS DES_ARDIDO,
               SUM(DECODE(RO.DES_OUTROS  ,NULL,0,RO.DES_OUTROS  )) AS DES_OUTROS,
               SUM(DECODE(RO.DES_UMIDADE ,NULL,0,RO.DES_UMIDADE )+
                   DECODE(RO.DES_IMPUREZA,NULL,0,RO.DES_IMPUREZA)+
                   DECODE(RO.DES_AVARIADO,NULL,0,RO.DES_AVARIADO)+
                   DECODE(RO.DES_ARDIDO  ,NULL,0,RO.DES_ARDIDO  )+
                   DECODE(RO.DES_OUTROS  ,NULL,0,RO.DES_OUTROS  )) AS DESCONTOS,
               SUM(DECODE(DECODE(PER_UMIDADE,NULL,0,PER_UMIDADE),0,0,RO.PESO_BRUTO-RO.PESO_TARA)) AS TOTUMI,
               SUM(DECODE(DECODE(PER_UMIDADE,NULL,0,PER_UMIDADE),0,0,(RO.PESO_BRUTO-RO.PESO_TARA)*DECODE(PER_UMIDADE,NULL,0,PER_UMIDADE))) AS TOTPERUMI,
               SUM(DECODE(DECODE(PER_IMPUREZA,NULL,0,PER_IMPUREZA),0,0,RO.PESO_BRUTO-RO.PESO_TARA)) AS TOTIMP,
               SUM(DECODE(DECODE(PER_IMPUREZA,NULL,0,PER_IMPUREZA),0,0,(RO.PESO_BRUTO-RO.PESO_TARA)*DECODE(PER_IMPUREZA,NULL,0,PER_IMPUREZA))) AS TOTPERIMP,
               SUM(DECODE(DECODE(PER_AVARIADO,NULL,0,PER_AVARIADO),0,0,RO.PESO_BRUTO-RO.PESO_TARA)) AS TOTAVA,
               SUM(DECODE(DECODE(PER_AVARIADO,NULL,0,PER_AVARIADO),0,0,(RO.PESO_BRUTO-RO.PESO_TARA)*DECODE(PER_AVARIADO,NULL,0,PER_AVARIADO))) AS TOTPERAVA,
               SUM(DECODE(DECODE(PER_ARDIDO,NULL,0,PER_ARDIDO),0,0,RO.PESO_BRUTO-RO.PESO_TARA)) AS TOTARD,
               SUM(DECODE(DECODE(PER_ARDIDO,NULL,0,PER_ARDIDO),0,0,(RO.PESO_BRUTO-RO.PESO_TARA)*DECODE(PER_ARDIDO,NULL,0,PER_ARDIDO))) AS TOTPERARD,
               SUM(DECODE(DECODE(PER_OUTROS,NULL,0,PER_OUTROS),0,0,RO.PESO_BRUTO-RO.PESO_TARA)) AS TOTOUT,
               SUM(DECODE(DECODE(PER_OUTROS,NULL,0,PER_OUTROS),0,0,(RO.PESO_BRUTO-RO.PESO_TARA)*DECODE(PER_OUTROS,NULL,0,PER_OUTROS))) AS TOTPEROUT,
               SUM(IT.QUANTIDADE) AS PESO_LIQUIDO,
               SUM(IT.QUANTIDADE) AS PESO_LIQUIDO_DESC,
               SUM(IT.QUANTIDADE)/ 1 AS LIQUIDO_SACAS_DESC,
               SUM(IT.QUANTIDADE / 1 ) AS LIQUIDO_SACAS,
               RO.SEQ_PLA_TALHAO_SAFRA,
               NF.SEQ_PLA_ENDERECO,
               CE.ENDERECO,
               CL.NOME_CLIENTE,
               PD.SEQ_PLA_PRODUTO,
               PD.DESCRICAO_PRODUTO,
               FI.COD_FILIAL,
               FI.SIGLA_FILIAL,
               SF.DESCRICAO_SAFRA,
               NF.SEQ_PLA_FAZENDA,
               FZ.SIGLA_FAZENDA,
               FZ.DESC_FAZENDA,
               NF.COD_EMPRESA,
               EM.NOME_EMPRESA,
               NF.COD_SAFRA,
               TA.SEQ_PLA_TALHAO,
               TA.NUMERO_TALHAO,
               TS.FINALIZADO,
               UP.SIGLA_UNIDADE,
               UV.SEQ_PLA_VARIEDADE,
               UV.DESC_VARIEDADE,
               TP.SEQ_PLA_TIPO_CULT,
               TP.DESC_CULTURA,
               TS.QTDE_HA,
               TS.KGS_PREV_PRODUCAO
          FROM AGRICOLA.EST_ENTRADAS       NF,
               AGRICOLA.EST_ENTRADAS_ROM   RO,
               AGRICOLA.EST_ENTRADAS_ITENS IT,
               AGRICOLA.CLIENTES_ENDERECOS CE,
               AGRICOLA.CLIENTES           CL,
               AGRICOLA.PRODUTOS           PD,
               AGRICOLA.SUB_GRUPO          SG,
               AGRICOLA.FILIAIS            FI,
               AGRICOLA.SAFRAS             SF,
               AGRICOLA.FAZENDAS           FZ,
               AGRICOLA.EMPRESAS           EM,
               AGRICOLA.TALHOES_SAFRA      TS,
               AGRICOLA.TALHOES            TA,
               AGRICOLA.UNIDADE_PRODUTO    UP,
               AGRICOLA.UBS_VARIEDADES     UV,
               AGRICOLA.TIPO_CULTURA       TP
         WHERE NF.SEQ_PLA_ENTRADA     =RO.SEQ_PLA_ENTRADA
           AND NVL(RO.CANCELADO,'N')  ='N'
           AND RO.TIPO_ENTRADA<>'A'
           AND NF.SEQ_PLA_ENTRADA     = IT.SEQ_PLA_ENTRADA
           AND NF.SEQ_PLA_ENDERECO    = CE.SEQ_PLA_ENDERECO
           AND CE.SEQ_PLA_CLIENTE     = CL.SEQ_PLA_CLIENTE
           AND IT.SEQ_PLA_PRODUTO     = PD.SEQ_PLA_PRODUTO
           AND PD.SEQ_PLA_SUB_GRUPO   = SG.SEQ_PLA_SUB_GRUPO
           AND NF.COD_EMPRESA         = FI.COD_EMPRESA
           AND NF.COD_FILIAL          = FI.COD_FILIAL
           AND NF.COD_SAFRA           = SF.COD_SAFRA
           AND NF.SEQ_PLA_FAZENDA     = FZ.SEQ_PLA_FAZENDA
           AND NF.COD_EMPRESA         = EM.COD_EMPRESA
           AND TS.SEQ_PLA_TALHAO_SAFRA =RO.SEQ_PLA_TALHAO_SAFRA (+)
           AND TS.SEQ_PLA_TALHAO      = TA.SEQ_PLA_TALHAO
           AND IT.SEQ_PLA_UNIDADE     = UP.SEQ_PLA_UNIDADE
           AND RO.SEQ_PLA_VARIEDADE   = UV.SEQ_PLA_VARIEDADE
           AND UV.SEQ_PLA_TIPO_CULT   = TP.SEQ_PLA_TIPO_CULT
         GROUP BY NF.SEQ_PLA_ENDERECO,
               CE.ENDERECO,
               RO.SEQ_PLA_TALHAO_SAFRA,
               PD.SEQ_PLA_PRODUTO,
               PD.DESCRICAO_PRODUTO,
               FI.COD_FILIAL,
               FI.SIGLA_FILIAL,
               NF.SEQ_PLA_FAZENDA,
               FZ.SIGLA_FAZENDA,
               FZ.DESC_FAZENDA,
               NF.COD_EMPRESA,
               EM.NOME_EMPRESA,
               NF.COD_SAFRA,
               SF.DESCRICAO_SAFRA,
               TA.SEQ_PLA_TALHAO,
               TA.NUMERO_TALHAO,
               TS.FINALIZADO,
               UP.SIGLA_UNIDADE,
               UV.SEQ_PLA_VARIEDADE,
               UV.DESC_VARIEDADE,
               TP.SEQ_PLA_TIPO_CULT,
               TP.DESC_CULTURA,
               TS.QTDE_HA,
               TS.KGS_PREV_PRODUCAO,
               CL.NOME_CLIENTE
  UNION
  SELECT 0 AS ROMANEIOS,
         SUM(ET.PESO_BRUTO) AS PESO_BRUTO,
         SUM(ET.PESO_BRUTO- DECODE(ET.PESO_TARA,NULL,0,ET.PESO_TARA)) AS SUBTOTAL,
         SUM(DECODE(ET.DESC_UMIDADE ,NULL,0,ET.DESC_UMIDADE )) AS DES_UMIDADE,
         SUM(DECODE(ET.DESC_IMPUREZA,NULL,0,ET.DESC_IMPUREZA)) AS DES_IMPUREZA,
         0 AS DES_AVARIADO,
         0 AS DES_ARDIDO,
         0 AS DES_OUTROS,
         SUM(DECODE(ET.DESC_UMIDADE,NULL,0,ET.DESC_UMIDADE )+
             DECODE(ET.DESC_IMPUREZA,NULL,0,ET.DESC_IMPUREZA)) AS DESCONTOS,
         SUM(DECODE(DECODE(ET.PERC_UMIDADE,NULL,0,ET.PERC_UMIDADE),0,0,ET.PESO_BRUTO-ET.PESO_TARA)) AS TOTUMI,
         SUM(DECODE(DECODE(ET.PERC_UMIDADE,NULL,0,ET.PERC_UMIDADE),0,0,(ET.PESO_BRUTO-ET.PESO_TARA)*DECODE(ET.PERC_UMIDADE,NULL,0,ET.PERC_UMIDADE))) AS TOTPERUMI,
         SUM(DECODE(DECODE(ET.PERC_IMPUREZA,NULL,0,ET.PERC_IMPUREZA),0,0,ET.PESO_BRUTO-ET.PESO_TARA)) AS TOTIMP,
         SUM(DECODE(DECODE(ET.PERC_IMPUREZA,NULL,0,ET.PERC_IMPUREZA),0,0,(ET.PESO_BRUTO-ET.PESO_TARA)*DECODE(ET.PERC_IMPUREZA,NULL,0,ET.PERC_IMPUREZA))) AS TOTPERIMP,
         0 AS TOTAVA,
         0 AS TOTPERAVA,
         0 AS TOTARD,
         0 AS TOTPERARD,
         0 AS TOTOUT,
         0 AS TOTPEROUT,
         SUM(ET.PESO_LIQUIDO) AS PESO_LIQUIDO,
         SUM(ET.PESO_LIQUIDO) AS PESO_LIQUIDO_DESC,
         SUM(ET.PESO_LIQUIDO)/ 1 AS LIQUIDO_SACAS_DESC,
         SUM(ET.PESO_LIQUIDO / 1 ) AS LIQUIDO_SACAS,
         ET.SEQ_PLA_TALHAO_SAFRA,
         ET.SEQ_PLA_ENDERECO,
         CE.ENDERECO,
         CL.NOME_CLIENTE,
         PD.SEQ_PLA_PRODUTO,
         PD.DESCRICAO_PRODUTO,
         FI.COD_FILIAL,
         FI.SIGLA_FILIAL,
         SF.DESCRICAO_SAFRA,
         FZ.SEQ_PLA_FAZENDA,
         FZ.SIGLA_FAZENDA,
         FZ.DESC_FAZENDA,
         ET.COD_EMPRESA,
         EM.NOME_EMPRESA,
         ET.COD_SAFRA,
         TA.SEQ_PLA_TALHAO,
         TA.NUMERO_TALHAO,
         TS.FINALIZADO,
         UP.SIGLA_UNIDADE,
         TS.SEQ_PLA_VARIEDADE,
         VA.DESC_VARIEDADE,
         TC.SEQ_PLA_TIPO_CULT,
         TC.DESC_CULTURA,
         TA.QTDE_HA,
         TS.KGS_PREV_PRODUCAO
    FROM AGRICOLA.TALHOES             TA,
         AGRICOLA.CLIENTES_ENDERECOS  CE,
         AGRICOLA.CLIENTES            CL,
         AGRICOLA.TALHOES_SAFRA       TS,
         AGRICOLA.UBS_VARIEDADES      VA,
         AGRICOLA.ENTRADAS            ET,
         AGRICOLA.PRODUTOS            PD,
         AGRICOLA.TIPO_CULTURA        TC,
         AGRICOLA.PARAMETROS_BALANCAS PA,
         AGRICOLA.FILIAIS             FI,
         AGRICOLA.SAFRAS              SF,
         AGRICOLA.EMPRESAS            EM,
         AGRICOLA.UNIDADE_PRODUTO     UP,
         AGRICOLA.FAZENDAS            FZ
 WHERE TA.SEQ_PLA_ENDERECO     = CE.SEQ_PLA_ENDERECO(+)
   AND CE.SEQ_PLA_CLIENTE      = CL.SEQ_PLA_CLIENTE(+)
   AND TA.SEQ_PLA_TALHAO       = TS.SEQ_PLA_TALHAO(+)
   AND TS.SEQ_PLA_VARIEDADE    = VA.SEQ_PLA_VARIEDADE(+)
   AND TS.SEQ_PLA_TALHAO_SAFRA = ET.SEQ_PLA_TALHAO_SAFRA(+)
   AND TC.SEQ_PLA_TIPO_CULT    = TS.Seq_Pla_Tipo_Cult
   AND PD.SEQ_PLA_PRODUTO      = TC.Seq_Pla_Produto
   AND PA.Seq_Pla_Alg_Caroco   = PD.Seq_Pla_Produto
   AND NVL(ET.CANCELADO,'N')   = 'N'
   AND ET.COD_EMPRESA          = EM.COD_EMPRESA
   AND ET.COD_EMPRESA          = FI.COD_EMPRESA
   AND ET.COD_FILIAL           = FI.COD_FILIAL
   AND ET.COD_SAFRA            = SF.COD_SAFRA
   AND PD.SEQ_PLA_UNIDADE      = UP.SEQ_PLA_UNIDADE
   AND FI.COD_EMPRESA          = FZ.COD_EMPRESA
   AND FI.COD_FILIAL           = FZ.COD_FILIAL
   AND FZ.SEQ_PLA_FAZENDA      = FZ.SEQ_PLA_FAZENDA_PRINCIPAL
GROUP BY TA.NUMERO_TALHAO,
               TA.SEQ_PLA_TALHAO,
               ET.SEQ_PLA_TALHAO_SAFRA,
               ET.SEQ_PLA_ENDERECO,
               CE.ENDERECO,
               CL.NOME_CLIENTE,
               PD.SEQ_PLA_PRODUTO,
               PD.DESCRICAO_PRODUTO,
               FI.COD_FILIAL,
               FI.SIGLA_FILIAL,
               SF.DESCRICAO_SAFRA,
               ET.COD_EMPRESA,
               EM.NOME_EMPRESA,
               ET.COD_SAFRA,
               TS.FINALIZADO,
               UP.SIGLA_UNIDADE,
               TS.SEQ_PLA_VARIEDADE,
               VA.DESC_VARIEDADE,
               TC.SEQ_PLA_TIPO_CULT,
               TC.DESC_CULTURA,
               TA.QTDE_HA,
               TS.KGS_PREV_PRODUCAO,
               FZ.SEQ_PLA_FAZENDA,
               FZ.SIGLA_FAZENDA,
               FZ.DESC_FAZENDA
  ) RO
