CREATE MATERIALIZED VIEW VW_ESTOQUE_GRAOS
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT
       TIPO,
       COD_SAFRA,
       CL.NOME_CLIENTE,
       COD_EMPRESA,
       NOME_EMPRESA,
       COD_FILIAL,
       DESCRICAO_FILIAL,
       PD.SEQ_PLA_PRODUTO,
       PD.DESCRICAO_PRODUTO,
       SUM(NVL(ENSA.QUANTIDADE_ENTRADA,0)) AS QUANTIDADE_ENTRADA,
       SUM(NVL(ENSA.QUANTIDADE_SAIDA,0)) AS QUANTIDADE_SAIDA,
       SUM(NVL(ENSA.QUEBRA_TECNICA,0)) AS QUEBRA_TECNICA,
       SUM(NVL(ENSA.TRANSF_ENTRADA,0)) AS TRANSF_ENTRADA,
       SUM(NVL(ENSA.TRANSF_SAIDA,0)) AS TRANSF_SAIDA
  FROM AGUIAR3107.CLIENTES CL,
       AGUIAR3107.PRODUTOS PD,
       (
        SELECT
        'ROM_SAIDA' AS TIPO,
        SA.COD_SAFRA,
        CE.SEQ_PLA_CLIENTE,
        EP.COD_EMPRESA,
        EP.NOME_EMPRESA,
        FI.COD_FILIAL,
        FI.DESCRICAO_FILIAL,
        SAI.SEQ_PLA_PRODUTO,
        0 AS QUANTIDADE_ENTRADA,
        SUM(RO.PESO_BRUTO - RO.PESO_TARA) AS QUANTIDADE_SAIDA,
        0 AS QUEBRA_TECNICA,
        0 AS TRANSF_ENTRADA,
        0 AS TRANSF_SAIDA
        FROM AGUIAR3107.EST_SAIDAS      SA,
             AGUIAR3107.EST_SAIDAS_ITENS SAI,
             AGUIAR3107.EST_SAIDAS_ROM  RO,
             AGUIAR3107.UBS_VARIEDADES  UV,
             AGUIAR3107.PRODUTOS        PD,
             AGUIAR3107.PRODUTOS        PDC,
             AGUIAR3107.TIPO_CULTURA    TC,
             AGUIAR3107.EMPRESAS        EP,
             AGUIAR3107.FILIAIS         FI,
             AGUIAR3107.CLIENTES_ENDERECOS CE
        WHERE
             SA.SEQ_PLA_SAIDA = SAI.SEQ_PLA_SAIDA
         AND SAI.SEQ_PLA_PRODUTO = PD.SEQ_PLA_PRODUTO
         AND SA.SEQ_PLA_SAIDA    = RO.SEQ_PLA_SAIDA
         AND NVL(RO.CANCELADO,'N') = 'N'
         AND RO.SEQ_PLA_VARIEDADE = UV.SEQ_PLA_VARIEDADE(+)
         AND UV.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT(+)
         AND TC.SEQ_PLA_PRODUTO   = PDC.SEQ_PLA_PRODUTO(+)
         AND SA.COD_EMPRESA = EP.COD_EMPRESA
         AND SA.COD_FILIAL = FI.COD_FILIAL
         AND FI.COD_EMPRESA = EP.COD_EMPRESA
         AND SA.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
         GROUP BY
            SA.COD_SAFRA,
            CE.SEQ_PLA_CLIENTE,
            EP.COD_EMPRESA,
            EP.NOME_EMPRESA,
            FI.COD_FILIAL,
            FI.DESCRICAO_FILIAL,
            SAI.SEQ_PLA_PRODUTO

        UNION

        SELECT
               'QUEBRA' AS TIPO,
               QT.COD_SAFRA,
               CE.SEQ_PLA_CLIENTE,
               EP.COD_EMPRESA,
               EP.NOME_EMPRESA,
               FI.COD_FILIAL,
               FI.DESCRICAO_FILIAL,
               QT.SEQ_PLA_PRODUTO,
               0 AS QUANTIDADE_ENTRADA,
               0 AS QUANTIDADE_SAIDA,
               SUM(QT.QUANTIDADE) AS QUEBRA_TECNICA,
               0 AS TRANSF_ENTRADA,
               0 AS TRANSF_SAIDA
          FROM AGUIAR3107.QUEBRA_TECNICA     QT,
               AGUIAR3107.PRODUTOS           PD,
               AGUIAR3107.CLIENTES_ENDERECOS CE,
               AGUIAR3107.EMPRESAS EP,
               AGUIAR3107.FILIAIS FI
         WHERE QT.SEQ_PLA_PRODUTO   = PD.SEQ_PLA_PRODUTO   (+)
           AND QT.SEQ_PLA_CLIENTE   = CE.SEQ_PLA_ENDERECO  (+)
           AND QT.COD_EMPRESA = EP.COD_EMPRESA
           AND QT.COD_FILIAL = FI.COD_FILIAL
           AND FI.COD_EMPRESA = EP.COD_EMPRESA
         GROUP BY
               QT.COD_SAFRA,
               CE.SEQ_PLA_CLIENTE,
               EP.COD_EMPRESA,
               EP.NOME_EMPRESA,
               FI.COD_FILIAL,
               FI.DESCRICAO_FILIAL,
               QT.SEQ_PLA_PRODUTO

         UNION

        SELECT
               'TRANSF_SAIDA' AS TIPO,
               TR.COD_SAFRA,
               CE.SEQ_PLA_CLIENTE,
               EP.COD_EMPRESA,
               EP.NOME_EMPRESA,
               FI.COD_FILIAL,
               FI.DESCRICAO_FILIAL,
               TR.SEQ_PLA_PRODUTO,
               0 AS QUANTIDADE_ENTRADA,
               0 AS QUANTIDADE_SAIDA,
               0 AS QUEBRA_TECNICA,
               0 AS TRANSF_ENTRADA,
               SUM(TR.QUANTIDADE) AS TRANSF_SAIDA
          FROM AGUIAR3107.TRANSFERENCIAS     TR,
               AGUIAR3107.CLIENTES_ENDERECOS CE,
               AGUIAR3107.PRODUTOS           PD,
               AGUIAR3107.EMPRESAS EP,
               AGUIAR3107.FILIAIS FI
         WHERE TR.SEQ_PLA_CEDENTE    = CE.SEQ_PLA_ENDERECO
           AND TR.SEQ_PLA_PRODUTO    = PD.SEQ_PLA_PRODUTO   (+)
           AND TR.COD_EMPRESA = EP.COD_EMPRESA
           AND TR.COD_FILIAL = FI.COD_FILIAL
           AND FI.COD_EMPRESA = EP.COD_EMPRESA
         GROUP BY
               TR.COD_SAFRA,
               CE.SEQ_PLA_CLIENTE,
               EP.COD_EMPRESA,
               EP.NOME_EMPRESA,
               FI.COD_FILIAL,
               FI.DESCRICAO_FILIAL,
               TR.SEQ_PLA_PRODUTO

        UNION

        SELECT
               'TRANSF_ENTRADA' AS TIPO,
               TR.COD_SAFRA,
               CE.SEQ_PLA_CLIENTE,
               EP.COD_EMPRESA,
               EP.NOME_EMPRESA,
               FI.COD_FILIAL,
               FI.DESCRICAO_FILIAL,
               TR.SEQ_PLA_PRODUTO,
               0 AS QUANTIDADE_ENTRADA,
               0 AS QUANTIDADE_SAIDA,
               0 AS QUEBRA_TECNICA,
               SUM(TR.QUANTIDADE) AS TRANSF_ENTRADA,
               0 AS TRANSF_SAIDA
          FROM AGUIAR3107.TRANSFERENCIAS     TR,
               AGUIAR3107.CLIENTES_ENDERECOS CE,
               AGUIAR3107.PRODUTOS           PD,
               AGUIAR3107.EMPRESAS EP,
               AGUIAR3107.FILIAIS FI
         WHERE TR.SEQ_PLA_BENEFICIADO = CE.SEQ_PLA_ENDERECO
           AND TR.SEQ_PLA_PRODUTO    = PD.SEQ_PLA_PRODUTO   (+)
           AND TR.EMPRESA_DESTINO = EP.COD_EMPRESA
           AND TR.FILIAL_DESTINO = FI.COD_FILIAL
           AND FI.COD_EMPRESA = EP.COD_EMPRESA

         GROUP BY
               TR.COD_SAFRA,
               CE.SEQ_PLA_CLIENTE,
               EP.COD_EMPRESA,
               EP.NOME_EMPRESA,
               FI.COD_FILIAL,
               FI.DESCRICAO_FILIAL,
               TR.SEQ_PLA_PRODUTO
         ) ENSA
 WHERE CL.SEQ_PLA_CLIENTE = ENSA.SEQ_PLA_CLIENTE
   AND PD.SEQ_PLA_PRODUTO = ENSA.SEQ_PLA_PRODUTO
GROUP BY
       TIPO,
       COD_SAFRA,
       CL.NOME_CLIENTE,
       PD.DESCRICAO_PRODUTO,
       COD_EMPRESA,
       NOME_EMPRESA,
       COD_FILIAL,
       DESCRICAO_FILIAL,
       PD.SEQ_PLA_PRODUTO,
       PD.DESCRICAO_PRODUTO;