CREATE OR REPLACE VIEW VW_PLANTIO_TALHAO_SAFRA
AS
SELECT TS.COD_SAFRA,
	   SF.DESCRICAO_SAFRA,
       FA.COD_EMPRESA,
       FA.COD_FILIAL,
       ' ' AS SEQ_PLA_AGLOMERADO,
       FA.SEQ_PLA_FAZENDA,
       FA.SIGLA_FAZENDA,
	   FA.DESC_FAZENDA,
       TL.SEQ_PLA_TALHAO,
       TC.SEQ_PLA_TIPO_CULT,
       UV.SEQ_PLA_VARIEDADE,       
       EP.SIGLA_EMPRESA,
       ' ' AS DESC_REGIAO,
       ' ' AS SIGLA_AGLOMERADO,
       TC.DESC_CULTURA AS CULTURA,
       TS.SEQ_PLA_TALHAO_SAFRA,
       UV.DESC_VARIEDADE  AS VARIEDADE,
       ' ' AS CICLO,
       TS.DATA_PLANTIO,
       ' ' AS DESC_GRUPO_TAREFA,
       NVL(TS.FINALIZADO,'N') AS FINALIZADO,
       NVL(TS.QTDE_HA,0) AS QTD_HA_EFETIVO,
       ' ' AS SEMENTE_POR_METRO,
       TS.KGS_PREV_PRODUCAO AS QUANTIDADE,
       TS.ESPACAMENTO_TALHAO AS ESPACAMENTO,
       ' ' AS PMS
  FROM BANCO.TALHOES        TL,
       BANCO.TALHOES_SAFRA  TS,
       BANCO.UBS_VARIEDADES UV,
       BANCO.TIPO_CULTURA   TC,
       BANCO.FAZENDAS       FA,
       BANCO.SAFRAS         SF,
       BANCO.EMPRESAS       EP,
       BANCO.FILIAIS        FL
 WHERE TL.SEQ_PLA_TALHAO       = TS.SEQ_PLA_TALHAO
   AND TS.SEQ_PLA_VARIEDADE    = UV.SEQ_PLA_VARIEDADE(+)
   AND TL.SEQ_PLA_FAZENDA      = FA.SEQ_PLA_FAZENDA(+)
   AND UV.SEQ_PLA_TIPO_CULT    = TC.SEQ_PLA_TIPO_CULT (+)
   AND TS.COD_SAFRA            = SF.COD_SAFRA
   AND FL.COD_EMPRESA          = FA.COD_EMPRESA
   AND FL.COD_FILIAL           = FA.COD_FILIAL
   AND EP.COD_EMPRESA          = FL.COD_EMPRESA;
