CREATE MATERIALIZED VIEW VW_ACORDO_POTENCIAL REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT AP.SEQ_PLA_ACORDO_POTENCIAL,
       AP.COD_EMPRESA,
       AP.COD_SAFRA,
       AC.NR_CONFIRMACAO,
       TRUNC(AP.DATA_ACORDO) DATA_ACORDO,      
       DECODE(AP.TIPO_CTR,'C','COMPRA','VENDA') TIPO_CTR,
       AP.SEQ_PLA_PRODUTO,
       PD.DESCRICAO_PRODUTO,
       AP.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       UN.QTDE_UNIDADE,
       CL.NOME_CLIENTE AS NOME_AGENTE_INTERNO,
       AG.SEQ_PLA_AGENTE,
       AP.SEQ_PLA_AGENTE_IN,       
       NVL(AP.QUANTIDADE,0) AS QUANTIDADE,
       ROUND(NVL(AP.UNITARIO,0),2) AS UNITARIO,
       ROUND(NVL(AP.VALOR_TOTAL,0),2) AS VALOR_TOTAL,
       NVL(CP.VALOR_PAGO,0) VLR_PG_RB,
       CASE WHEN (NVL(DECODE(CP.DATA_VCTO,NULL,0, TRUNC(CP.DATA_VCTO) - (SELECT TRUNC(SYSDATE) FROM DUAL)),0)) < 0 then CASE WHEN (NVL(CP.VALOR_DOCUM,0) - NVL(CP.VALOR_PAGO,0))     = 0 then 'REGULAR' else 'IRREGULAR' end else 'REGULAR' end SITUACAO_FINAN,
       0 as LUCRO_VENDA,
       NVL(AP.PERC_COMISSAO_AGENTE_IN,0) AS PERC_COMISSAO_AGENTE_IN,
       NVL(AP.COMISSAO_TOT_AGENTE_IN,0) AS COMISSAO_AGENTE_INT                          
       
  FROM CERES1002.ACORDO_POTENCIAL   AP,
       CERES1002.ACORDO_CONFIRMACAO AC,
       CERES1002.PRODUTOS           PD,
       CERES1002.UNIDADE_PRODUTO    UN,
       --agente interno
       CERES1002.AGENTES            AG,
       CERES1002.CLIENTES           CL,
       CERES1002.CLIENTES_ENDERECOS CE,
       --CTR COMPRA
       CERES1002.COMPRA_CONTRATO    CC,
       CERES1002.CONTAS_PAGAR       CP

 WHERE AP.SEQ_PLA_ACORDO_POTENCIAL   = AC.SEQ_PLA_ACORDO_POTENCIAL
   --agente interno
   AND AP.SEQ_PLA_AGENTE_IN          = AG.SEQ_PLA_AGENTE
   AND AG.SEQ_PLA_ENDERECO           = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE            = CL.SEQ_PLA_CLIENTE  
   --
   AND AP.SEQ_PLA_PRODUTO            = PD.SEQ_PLA_PRODUTO
   AND AP.Seq_Pla_Unidade            = UN.SEQ_PLA_UNIDADE
   --CTR COMPRA      
   AND AP.SEQ_PLA_ACORDO_POTENCIAL   = CC.SEQ_PLA_ACORDO_POTENCIAL(+)
   AND CC.SEQ_PLA_CTR_COMPRA         = CP.Seq_Pla_Origem(+)
   --      
   AND NVL(AP.STATUS,'A')            = 'F'
   AND AP.TIPO_CTR                   = 'C'
   
UNION ALL

SELECT AP.SEQ_PLA_ACORDO_POTENCIAL,
       AP.COD_EMPRESA,
       AP.COD_SAFRA,
       AC.NR_CONFIRMACAO,
       TRUNC(AP.DATA_ACORDO) DATA_ACORDO,      
       DECODE(AP.TIPO_CTR,'C','COMPRA','VENDA') TIPO_CTR,
       AP.SEQ_PLA_PRODUTO,
       PD.DESCRICAO_PRODUTO,
       AP.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       UN.QTDE_UNIDADE,
       CL.NOME_CLIENTE AS NOME_AGENTE_INTERNO,
       AG.SEQ_PLA_AGENTE,
       AP.SEQ_PLA_AGENTE_IN,       
       NVL(AP.QUANTIDADE,0) AS QUANTIDADE,
       ROUND(NVL(AP.UNITARIO,0),2) AS UNITARIO,
       ROUND(NVL(AP.VALOR_TOTAL,0),2) AS VALOR_TOTAL,
       NVL(CR.VALOR_RECEBIDO,0) VLR_PG_RB,       

       CASE WHEN (NVL(DECODE(CR.DATA_VCTO,NULL,0, TRUNC(CR.DATA_VCTO) - (SELECT TRUNC(SYSDATE) FROM DUAL)),0)) < 0 then CASE WHEN (NVL(CR.VALOR_DOCUM,0) - NVL(CR.VALOR_RECEBIDO,0)) = 0 then 'REGULAR' else 'IRREGULAR' end else 'REGULAR'   end SITUACAO_FINAN,       
       ROUND(NVL(AP.UNITARIO,0),2) -
       --UNITARIO DAS COMPRAS VINCULADAS NO CONTRATO DE SAIDA. NA TELA NOVA, NÃO FOI FEITA NENHUMA TRAVA, MAS SERIA IMPORTANTE QUE VINCULASSE OS CTR DE COMPRA COM O MESMO PRODUTO/UNIDADE/AGENTE_INTERNO
       ROUND(NVL(LG.UNITARIO,0),2)
       as LUCRO_VENDA,

       NVL(AP.PERC_COMISSAO_AGENTE_IN,0) AS PERC_COMISSAO_AGENTE_IN,
       NVL(AP.COMISSAO_TOT_AGENTE_IN,0) AS COMISSAO_AGENTE_INT                          
       
  FROM CERES1002.ACORDO_POTENCIAL   AP,
       CERES1002.ACORDO_CONFIRMACAO AC,
       CERES1002.PRODUTOS           PD,
       CERES1002.UNIDADE_PRODUTO    UN,

       --agente interno
       CERES1002.AGENTES            AG,
       CERES1002.CLIENTES           CL,
       CERES1002.CLIENTES_ENDERECOS CE,

       --CTR SAIDA
       CERES1002.CONTRATO_SAIDA     CS,
       CERES1002.CONTAS_RECEBER     CR,

       --liga da venda pras Compras
       --NA TELA NOVA, NÃO FOI FEITA NENHUMA TRAVA, MAS SERIA IMPORTANTE QUE VINCULASSE OS CTR DE COMPRA COM O MESMO PRODUTO/UNIDADE/AGENTE_INTERNO
       (SELECT NVL(SUM(LG.UNITARIO),0) AS UNITARIO, LG.SEQ_PLA_PED_VENDA FROM CERES1002.LIGA_CTR_VENDA_COMPRAS LG GROUP BY LG.SEQ_PLA_PED_VENDA) LG

 WHERE AP.SEQ_PLA_ACORDO_POTENCIAL   = AC.SEQ_PLA_ACORDO_POTENCIAL
   --agente interno
   AND AP.SEQ_PLA_AGENTE_IN          = AG.SEQ_PLA_AGENTE
   AND AG.SEQ_PLA_ENDERECO           = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE            = CL.SEQ_PLA_CLIENTE   
   --fim agente interno

   AND AP.SEQ_PLA_PRODUTO            = PD.SEQ_PLA_PRODUTO
   AND AP.Seq_Pla_Unidade            = UN.SEQ_PLA_UNIDADE

   --CTR SAIDA      
   AND AP.SEQ_PLA_ACORDO_POTENCIAL   = CS.SEQ_PLA_ACORDO_POTENCIAL(+)
   AND CS.SEQ_PLA_PED_VENDA          = CR.Seq_Pla_Origem(+)   
   --fim CTR SAIDA
  
   AND CS.SEQ_PLA_PED_VENDA          = LG.SEQ_PLA_PED_VENDA(+)
   AND NVL(AP.STATUS,'A')            = 'F'
   AND AP.TIPO_CTR                   = 'V'   

ORDER BY 5,11
