CREATE OR REPLACE VIEW VW_PLANTIO_TALHAO_SAFRA AS
SELECT TS.COD_SAFRA,
       EM.COD_EMPRESA,
       FI.COD_FILIAL,
       TA.SEQ_PLA_FAZENDA,
       FA.SIGLA_FAZENDA,
       FA.DESC_FAZENDA,
       TS.SEQ_PLA_TALHAO,
       TS.SEQ_PLA_TIPO_CULT,
       TS.SEQ_PLA_VARIEDADE,
       SA.DESCRICAO_SAFRA,
       EM.SIGLA_EMPRESA,
       RE.DESC_REGIAO,
       AG.SEQ_PLA_AGLOMERADO,
       AG.DESC_AGLOMERADO,
       AG.SIGLA_AGLOMERADO,
       TA.NUMERO_TALHAO,
       TA.DESC_TALHAO,
       TC.DESC_CULTURA CULTURA,
       TS.SEQ_PLA_TALHAO_SAFRA,
       UV.DESC_VARIEDADE VARIEDADE,
       (SELECT PVR.CICLO
          FROM AGNEW.PAR_VARIEDADE_REGIAO PVR
         WHERE PVR.COD_SAFRA = OS.COD_SAFRA
           AND PVR.SEQ_PLA_REGIAO = RE.SEQ_PLA_REGIAO
           AND PVR.SEQ_PLA_VARIEDADE = UV.SEQ_PLA_VARIEDADE) CICLO,
       TRUNC(TS.DATA_PLANTIO) AS DATA_PLANTIO,
       GT.DESC_GRUPO_TAREFA,
       NVL(TS.FINALIZADO,'N') AS FINALIZADO,
       SUM(NVL(TS.QTDE_HA,0)) AS QTD_HA_EFETIVO,
       AVG(RS.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
       SUM(RS.QUANTIDADE) AS QUANTIDADE,
       AVG(RS.ESPACAMENTO) AS ESPACAMENTO,
       DECODE(((SUM(TS.QTDE_HA) * (10000 / AVG(RS.ESPACAMENTO)) *
              AVG(RS.SEMENTES_POR_METRO)) / 1000),
              0,
              0,
              ((SUM(RS.QUANTIDADE) * 1000) /
              ((SUM(TS.QTDE_HA) * (10000 / AVG(RS.ESPACAMENTO)) *
              AVG(RS.SEMENTES_POR_METRO)) / 1000))) as pms

  FROM AGNEW.ORDEM_SERVICO OS,
       AGNEW.ORDEM_SERV_TALHOES OST,
       AGNEW.VINCULA_TAREFA_GRUPO VTG,
       AGNEW.TAREFAS TAR,
       AGNEW.GRUPO_TAREFAS GT,
       AGNEW.TALHOES_SAFRA TS,
       AGNEW.SAFRAS             SA,
       AGNEW.EMPRESAS           EM,
       AGNEW.FILIAIS            FI,
       AGNEW.AGLOMERADOS        AG,
       AGNEW.REGIOES_GERENCIAIS RE,
       AGNEW.FAZENDAS           FA,
       AGNEW.TALHOES            TA,
       AGNEW.TIPO_CULTURA       TC,
       AGNEW.UBS_VARIEDADES     UV,
       --,RECEITUARIO_SEMENTE RS   --Eberson  07/01/2012  ch 4508

       (SELECT X.SEQ_PLA_ORDEM AS SEQ_PLA_ORDEM,
               X.SEQ_PLA_ORDEM_TALHAO AS SEQ_PLA_ORDEM_TALHAO,
               AVG(X.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
               AVG(X.SEMENTES_PMS) AS SEMENTES_PMS,
               SUM(X.QUANTIDADE) AS QUANTIDADE,
               AVG(X.ESPACAMENTO) AS ESPACAMENTO,
               AVG(X.PMS_LOTE) AS PMS_LOTE
          FROM (SELECT RS.SEQ_PLA_ORDEM,
                       LT.SEQ_PLA_ORDEM_TALHAO,
                       AVG(RS.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
                       AVG(RS.SEMENTES_PMS) AS SEMENTES_PMS,
                       SUM(LT.QUANTIDADE) AS QUANTIDADE,
                       AVG(E.ESPACAMENTO) AS ESPACAMENTO,
                       nvl((select avg(ul.sementes_pms) as pms
                             from AGNEW.est_saidas_lotes sl, AGNEW.ubs_lotes ul
                            where sl.seq_pla_sai_item = ESI.SEQ_PLA_SAI_ITEM
                              and sl.seq_pla_lotes = ul.seq_pla_lotes),
                           0) as pms_lote
                  FROM AGNEW.RECEITUARIO_SEMENTE   RS,
                       AGNEW.ESPACAMENTO           E,
                       AGNEW.EST_SAIDAS_ITENS      ESI,
                       AGNEW.EST_SAIDAS            ES,
                       AGNEW.LIGA_TALHAO_APLICACAO LT
                 WHERE RS.SEQ_PLA_ESPACAMENTO = E.SEQ_PLA_ESPACAMENTO
                   AND RS.SEQ_PLA_REC_SEM = ESI.PRODUTO_COMPLEMENTO
                   AND ESI.SEQ_PLA_SAIDA = ES.SEQ_PLA_SAIDA
                   AND ES.FORM_LANCAMENTO = 'DFMORDEMAPLICACAO'
                   AND ESI.SEQ_PLA_SAI_ITEM = LT.SEQ_PLA_SAI_ITEM
                 GROUP BY RS.SEQ_PLA_ORDEM,
                          LT.SEQ_PLA_ORDEM_TALHAO,
                          ESI.SEQ_PLA_SAI_ITEM
                UNION ALL
                SELECT RS.SEQ_PLA_ORDEM,
                       NULL AS SEQ_PLA_ORDEM_TALHAO,
                       AVG(RS.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
                       AVG(RS.SEMENTES_PMS) AS SEMENTES_PMS,
                       SUM(RS.QUANTIDADE) AS QUANTIDADE,
                       AVG(E.ESPACAMENTO) AS ESPACAMENTO,
                       0 AS PMS_LOTE
                  FROM AGNEW.RECEITUARIO_SEMENTE RS,
                       AGNEW.ESPACAMENTO         E,
                       AGNEW.ORDEM_SERVICO       OSS
                 WHERE RS.SEQ_PLA_ESPACAMENTO = E.SEQ_PLA_ESPACAMENTO
                   AND RS.SEQ_PLA_ORDEM = OSS.SEQ_PLA_ORDEM
                   AND NVL(OSS.TIPO_ORDEM, 'N') = 'S'
                 GROUP BY RS.SEQ_PLA_ORDEM) X
         GROUP BY X.SEQ_PLA_ORDEM, X.SEQ_PLA_ORDEM_TALHAO) RS
 WHERE OS.SEQ_PLA_ORDEM = OST.SEQ_PLA_ORDEM
   AND OST.SEQ_PLA_ORDEM_TALHOES = TS.SEQ_PLA_ORDEM_PLANTIO(+)
   AND OST.SEQ_PLA_ORDEM_TALHOES =  NVL(RS.SEQ_PLA_ORDEM_TALHAO, OST.SEQ_PLA_ORDEM_TALHOES)
   AND OS.COD_SAFRA = SA.COD_SAFRA
   AND OS.SEQ_PLA_FAZENDA = FA.SEQ_PLA_FAZENDA
   AND OS.SEQ_PLA_VINC_TAREFA = VTG.SEQ_PLA_VINC_TAREFA
   AND VTG.SEQ_PLA_TAREFA = TAR.SEQ_PLA_TAREFA
   AND VTG.SEQ_PLA_GRUPO_TAREFA = GT.SEQ_PLA_GRUPO_TAREFA
   AND OST.SEQ_PLA_TALHAO = TA.SEQ_PLA_TALHAO
   AND FA.SEQ_PLA_AGLOMERADO = AG.SEQ_PLA_AGLOMERADO
   AND AG.COD_EMPRESA = EM.COD_EMPRESA
   AND AG.COD_EMPRESA = FI.COD_EMPRESA
   AND AG.COD_FILIAL = FI.COD_FILIAL
   AND AG.SEQ_PLA_REGIAO = RE.SEQ_PLA_REGIAO
   AND TS.SEQ_PLA_TIPO_CULT =  TC.SEQ_PLA_TIPO_CULT
   AND TS.SEQ_PLA_VARIEDADE = UV.SEQ_PLA_VARIEDADE
   AND OST.SEQ_PLA_ORDEM = RS.SEQ_PLA_ORDEM(+)
   AND (TAR.PLANTIO = 'S' /*OR TAR.REPLANTIO = 'S'*/)
 GROUP BY SA.DESCRICAO_SAFRA,
          EM.SIGLA_EMPRESA,
          RE.DESC_REGIAO,
          AG.SEQ_PLA_AGLOMERADO,
          AG.DESC_AGLOMERADO,
          AG.SIGLA_AGLOMERADO,
          FA.SIGLA_FAZENDA,
          FA.DESC_FAZENDA,
          TA.NUMERO_TALHAO,
          TA.DESC_TALHAO,
          TC.DESC_CULTURA,
          UV.DESC_VARIEDADE,
          TS.DATA_PLANTIO,
          GT.DESC_GRUPO_TAREFA,
          OS.COD_SAFRA,
          RE.SEQ_PLA_REGIAO,
          UV.SEQ_PLA_VARIEDADE,
          SA.APELIDO_SAFRA,
          TS.SEQ_PLA_TALHAO_SAFRA,
          TS.COD_SAFRA,
          EM.COD_EMPRESA,
          FI.COD_FILIAL,
          AG.SEQ_PLA_AGLOMERADO,
          TA.SEQ_PLA_FAZENDA,
          TS.SEQ_PLA_TALHAO,
          TS.SEQ_PLA_TIPO_CULT,
          TS.SEQ_PLA_VARIEDADE,
          NVL(TS.FINALIZADO,'N');
