CREATE MATERIALIZED VIEW VW_GRAFICO_MOV_SEMENTES
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT       X.SIGLA_CLASSE AS CATEGORIA,
             X.SEQ_PLA_CLASSE,
             X.SEQ_PLA_UNIDADE,
             X.SIGLA_UNIDADE,
             X.QTDE_UNIDADE,
             X.SEQ_PLA_PENEIRA,
             X.SEQ_PLA_VARIEDADE,
             X.EMBARQUE,
             X.DESCRICAO_MARCA,
             X.SIGLA_PENEIRA AS PENEIRA,
             X.DESC_VARIEDADE AS VARIEDADE,
			 X.SEQ_PLA_TIPO_CULT,
             X.CULTURA,
             X.SIGLA_EMPRESA,
             X.COD_EMPRESA,
             X.COD_FILIAL,
             X.COD_SAFRA,
             X.SIGLA_FILIAL,
             X.DESCRICAO_SAFRA AS SAFRA,
             X.SIGLA_UNIDADE AS SIGLA_UNID_BASE,
             X.QTDE_UNIDADE AS QTDE_UNID_BASE,
             (SUM(X.X_TOTAL_PRODUZIDO) + SUM(X.VOL_TOTAL_COMPRADO) - SUM(X.qtde_reserva_tecnica) - SUM(X.X_TOTAL_SAI_DESCARTE) -  SUM(X.X_TOTAL_VENDIDO) + SUM(X.X_TOTAL_DEVOLVIDO)) AS SALDO_VENDER_KG,
             SUM(X.X_TOTAL_PRODUZIDO) AS TOTAL_PRODUZIDO_KG,
             SUM(X.VOL_TOTAL_COMPRADO) AS TOTAL_COMPRADO_KG,
             SUM(X.qtde_reserva_tecnica) + SUM(X.X_TOTAL_VENDIDO) - SUM(X.X_TOTAL_DEVOLVIDO) AS TOTAL_VENDIDO_KG,
             SUM(X.X_TOTAL_VENDIDO) - SUM(X.X_TOTAL_ENTREGUE) AS SALDO_ENTREGAR_KG,
             SUM(X.X_TOTAL_VENDIDO / 1000) AS X_TOTAL_VENDIDO,
             SUM(X.X_TOTAL_VENDIDO) - SUM(X.X_TOTAL_ENTREGUE) AS X_SALDO_ENTREGAR,
             0 AS X_TOTAL_A_VENDER,
             SUM(X.X_TOTAL_PRODUZIDO / 1000) - SUM(X.X_TOTAL_TRATADO) AS X_TOTAL_PRODUZIDO,
             SUM(X.X_TOTAL_PROJECAO / 1000) AS X_TOTAL_PROJECAO,
             SUM(X.X_TOTAL_COMPRADO / 1000) AS X_TOTAL_COMPRADO,
             SUM(X.X_TOTAL_DEVOLVIDO / 1000) AS X_TOTAL_DEVOLVIDO,
             SUM(X.X_TOTAL_ENT_TRANSF / 1000) AS X_TOTAL_ENT_TRANSF,
             SUM(X.X_TOTAL_RESERVAS / 1000) AS X_TOTAL_RESERVAS,
             SUM(X.X_TOTAL_RESERVAS_UTS / 1000) AS X_TOTAL_RESERVAS_UTS,
             SUM(X.X_TOTAL_PRE_BENEFICIAMENTO / 1000) AS X_TOTAL_PRE_BENEFICIAMENTO,
             (SUM(X.X_TOTAL_ENTREGUE / 1000)) AS TOTAL_ENTREGUE,
              SUM(X.X_TOTAL_SAI_TRATAMENTO / 1000) AS X_TOTAL_SAI_TRATAMENTO,
              SUM(X.X_TOTAL_SAI_DESCARTE / 1000) AS X_TOTAL_SAI_DESCARTE,
             SUM(X.VOL_TOTAL_PRODUZIDO) - SUM(X.VOL_TOTAL_RESERVAS) + SUM(X.VOL_TOTAL_DEVOLVIDO) AS VOL_TOTAL_DISPONIVEL,
             (SUM(X.VOL_TOTAL_PRODUZIDO) -
              SUM(X.vol_reserva_tecnica) -
              SUM(X.VOL_TOTAL_SAI_DESCARTE) -
              0 - -->Reserva Comercial
              SUM(X.VOL_TOTAL_VENDIDO) +
              SUM(X.VOL_TOTAL_DEVOLVIDO)) AS VOL_TOTAL_A_VENDER,
             SUM(X.VOL_TOTAL_VENDIDO) AS VOL_TOTAL_VENDIDO,
             SUM(X.VOL_TOTAL_PRODUZIDO) AS VOL_TOTAL_PRODUZIDO,
             SUM(X.VOL_TOTAL_PROJECAO) AS VOL_TOTAL_PROJECAO,
             SUM(X.VOL_TOTAL_COMPRADO) AS VOL_TOTAL_COMPRADO,
             SUM(X.VOL_TOTAL_DEVOLVIDO) AS VOL_TOTAL_DEVOLVIDO,
             SUM(X.VOL_TOTAL_ENT_TRANSF) AS VOL_TOTAL_ENT_TRANSF,
             SUM(X.VOL_TOTAL_RESERVAS) AS VOL_TOTAL_RESERVAS,
             SUM(X.VOL_TOTAL_RESERVAS_UTS) AS VOL_TOTAL_RESERVAS_UTS,
             SUM(X.VOL_TOTAL_PRE_BENEFICIAMENTO) AS VOL_TOTAL_PRE_BENEFICIAMENTO,
             SUM(X.VOL_TOTAL_TRATADO) AS VOL_TOTAL_TRATADO,
             SUM(X.VOL_TOTAL_VENDIDO) - SUM(X.VOL_TOTAL_ENTREGUE) AS VOL_SALDO_ENTREGAR,
             (SUM(X.VOL_TOTAL_ENTREGUE)) AS VOL_TOTAL_ENTREGUE,
              SUM(X.VOL_TOTAL_SAI_TRATAMENTO) AS VOL_TOTAL_SAI_TRATAMENTO,
              SUM(X.VOL_TOTAL_SAI_DESCARTE) AS VOL_TOTAL_SAI_DESCARTE,
             sum(x.qtde_reserva_tecnica / 1000) as qtde_reserva_tecnica,
             sum(x.vol_reserva_tecnica) as vol_reserva_tecnica
from(
SELECT UC.SIGLA_CLASSE,
       TUDO.SEQ_PLA_CLASSE,
       us.seq_pla_unidade,
       us.sigla_unidade,
       us.qtde_unidade,
       TUDO.SEQ_PLA_PENEIRA,
       TUDO.SEQ_PLA_VARIEDADE,
	   TC.SEQ_PLA_TIPO_CULT,
       TC.DESC_CULTURA AS CULTURA,
       TUDO.EMBARQUE,
       MP.DESCRICAO_MARCA,
       UP.SIGLA_PENEIRA,
       UV.DESC_VARIEDADE,
       EM.SIGLA_EMPRESA,
       FI.SIGLA_FILIAL,
       SA.DESCRICAO_SAFRA,
       EM.COD_EMPRESA,
       FI.COD_FILIAL,
       SA.COD_SAFRA,
       SUM(TUDO.X_TOTAL_VENDIDO) AS X_TOTAL_VENDIDO,
       SUM(TUDO.X_TOTAL_PRODUZIDO) AS X_TOTAL_PRODUZIDO,
       SUM(TUDO.X_TOTAL_PROJECAO) AS X_TOTAL_PROJECAO,
       SUM(TUDO.X_TOTAL_COMPRADO) AS X_TOTAL_COMPRADO,
       SUM(TUDO.X_TOTAL_DEVOLVIDO) AS X_TOTAL_DEVOLVIDO,
       SUM(TUDO.X_TOTAL_ENT_TRANSF) AS X_TOTAL_ENT_TRANSF,
       SUM(TUDO.X_TOTAL_RESERVAS) AS X_TOTAL_RESERVAS,
       SUM(TUDO.X_TOTAL_RESERVAS_UTS) AS X_TOTAL_RESERVAS_UTS,
       SUM(TUDO.X_TOTAL_PRE_BENEFICIAMENTO) AS X_TOTAL_PRE_BENEFICIAMENTO,
       SUM(TUDO.X_TOTAL_TRATADO) AS X_TOTAL_TRATADO,
       SUM(TUDO.X_TOTAL_VENDIDO) - SUM(TUDO.X_TOTAL_ENTREGUE) AS X_SALDO_ENTREGAR,
       (SUM(TUDO.X_TOTAL_ENTREGUE) - SUM(TUDO.X_TOTAL_DEVOLVIDO) - SUM(TUDO.X_TOTAL_ENT_TRANSF)) AS X_TOTAL_ENTREGUE,
       SUM(TUDO.X_TOTAL_SAI_TRATAMENTO) AS X_TOTAL_SAI_TRATAMENTO,
       SUM(TUDO.X_TOTAL_SAI_DESCARTE) AS X_TOTAL_SAI_DESCARTE,
       SUM(TUDO.VOL_TOTAL_VENDIDO) AS VOL_TOTAL_VENDIDO,
       SUM(TUDO.VOL_TOTAL_PRODUZIDO) AS VOL_TOTAL_PRODUZIDO,
       SUM(TUDO.VOL_TOTAL_PROJECAO) AS VOL_TOTAL_PROJECAO,
       SUM(TUDO.VOL_TOTAL_COMPRADO) AS VOL_TOTAL_COMPRADO,
       SUM(TUDO.VOL_TOTAL_DEVOLVIDO) AS VOL_TOTAL_DEVOLVIDO,
       SUM(TUDO.VOL_TOTAL_ENT_TRANSF) AS VOL_TOTAL_ENT_TRANSF,
       SUM(TUDO.VOL_TOTAL_RESERVAS) AS VOL_TOTAL_RESERVAS,
       SUM(TUDO.VOL_TOTAL_RESERVAS_UTS) AS VOL_TOTAL_RESERVAS_UTS,
       SUM(TUDO.VOL_TOTAL_PRE_BENEFICIAMENTO) AS VOL_TOTAL_PRE_BENEFICIAMENTO,
       SUM(TUDO.VOL_TOTAL_TRATADO) AS VOL_TOTAL_TRATADO,
       SUM(TUDO.VOL_TOTAL_VENDIDO) - SUM(TUDO.VOL_TOTAL_ENTREGUE) AS VOL_SALDO_ENTREGAR,
       (SUM(TUDO.VOL_TOTAL_ENTREGUE) - SUM(TUDO.VOL_TOTAL_DEVOLVIDO) - SUM(TUDO.VOL_TOTAL_ENT_TRANSF)) AS VOL_TOTAL_ENTREGUE,
       SUM(TUDO.VOL_TOTAL_SAI_TRATAMENTO) AS VOL_TOTAL_SAI_TRATAMENTO,
       SUM(TUDO.VOL_TOTAL_SAI_DESCARTE) AS VOL_TOTAL_SAI_DESCARTE,
       NVL((SELECT SUM((R.QUANTIDADE* DECODE(L.PESO_LOTE,0,U.QTDE_UNIDADE,L.PESO_LOTE))) AS QTDE_RESERVA
              FROM TROPICAL.RESERVA_LOTES_QUANTIDADE R, TROPICAL.UBS_LOTES L, TROPICAL.UNIDADE_PRODUTO U
             WHERE R.SEQ_PLA_LOTES = L.SEQ_PLA_LOTES
               AND R.TIPO_RESERVA = 'C'
               AND L.SEQ_PLA_UNIDADE = U.SEQ_PLA_UNIDADE
               AND L.SEQ_PLA_PRODUTO = PR.SEQ_PLA_PRODUTO
               AND L.SEQ_PLA_VARIEDADE = uv.seq_pla_variedade
               AND L.SEQ_PLA_CLASSE = uc.seq_pla_classe
               AND L.SEQ_PLA_PENEIRA = up.seq_pla_peneira
               AND L.COD_SAFRA = sa.cod_safra
             GROUP BY L.SEQ_PLA_VARIEDADE,
                      L.SEQ_PLA_CLASSE,
                      L.SEQ_PLA_PENEIRA),
            0) AS QTDE_RESERVA_TECNICA,
       NVL((SELECT sum(NVL(R.QUANTIDADE,0)) AS VOL_RESERVA
              FROM TROPICAL.RESERVA_LOTES_QUANTIDADE R, TROPICAL.UBS_LOTES L, TROPICAL.UNIDADE_PRODUTO U
             WHERE R.SEQ_PLA_LOTES = L.SEQ_PLA_LOTES
               AND R.TIPO_RESERVA = 'C'
               AND L.SEQ_PLA_PRODUTO = PR.SEQ_PLA_PRODUTO
               AND L.SEQ_PLA_UNIDADE = U.SEQ_PLA_UNIDADE
               AND L.SEQ_PLA_VARIEDADE = uv.seq_pla_variedade
               AND L.SEQ_PLA_CLASSE = uc.seq_pla_classe
               AND L.SEQ_PLA_PENEIRA = up.seq_pla_peneira
               AND L.COD_SAFRA = sa.cod_safra
             GROUP BY L.SEQ_PLA_VARIEDADE,
                      L.SEQ_PLA_CLASSE,
                      L.SEQ_PLA_PENEIRA),
          0) AS VOL_RESERVA_TECNICA,
       NVL((SELECT SUM((R.QUANTIDADE* DECODE(L.PESO_LOTE,0,U.QTDE_UNIDADE,L.PESO_LOTE))) AS QTDE_RESERVA
              FROM TROPICAL.RESERVA_LOTES_QUANTIDADE R, TROPICAL.UBS_LOTES L, TROPICAL.UNIDADE_PRODUTO U
             WHERE R.SEQ_PLA_LOTES = L.SEQ_PLA_LOTES
               AND R.TIPO_RESERVA = 'P'
               AND L.SEQ_PLA_UNIDADE = U.SEQ_PLA_UNIDADE
               AND L.SEQ_PLA_PRODUTO = PR.SEQ_PLA_PRODUTO
               AND L.SEQ_PLA_VARIEDADE = uv.seq_pla_variedade
               AND L.SEQ_PLA_CLASSE = uc.seq_pla_classe
               AND L.SEQ_PLA_PENEIRA = up.seq_pla_peneira
               AND L.COD_SAFRA = sa.cod_safra
             GROUP BY L.SEQ_PLA_VARIEDADE,
                      L.SEQ_PLA_CLASSE,
                      L.SEQ_PLA_PENEIRA),
         0) AS QTDE_RESERVA_PEDIDO,
       NVL((SELECT sum(NVL(R.QUANTIDADE,0)) AS VOL_RESERVA
              FROM TROPICAL.RESERVA_LOTES_QUANTIDADE R, TROPICAL.UBS_LOTES L, TROPICAL.UNIDADE_PRODUTO U
             WHERE R.SEQ_PLA_LOTES = L.SEQ_PLA_LOTES
               AND R.TIPO_RESERVA = 'P'
               AND L.SEQ_PLA_UNIDADE = U.SEQ_PLA_UNIDADE
               AND L.SEQ_PLA_PRODUTO = PR.SEQ_PLA_PRODUTO
               AND L.SEQ_PLA_VARIEDADE = uv.seq_pla_variedade
               AND L.SEQ_PLA_CLASSE = uc.seq_pla_classe
               AND L.SEQ_PLA_PENEIRA = up.seq_pla_peneira
               AND L.COD_SAFRA = sa.cod_safra
             GROUP BY L.SEQ_PLA_VARIEDADE,
                      L.SEQ_PLA_CLASSE,
                      L.SEQ_PLA_PENEIRA),
         0) AS VOL_RESERVA_PEDIDO
 FROM (SELECT * FROM TROPICAL.VW_CONS_POS_COM_SEM ) TUDO,
       TROPICAL.UBS_PENEIRAS UP,
       TROPICAL.UBS_CLASSES UC,
       TROPICAL.UBS_VARIEDADES UV,
       TROPICAL.PRODUTOS PR,
       TROPICAL.EMPRESAS EM,
       TROPICAL.FILIAIS FI,
       TROPICAL.SAFRAS SA,
       TROPICAL.MARCA_PRODUTO MP,
       TROPICAL.produto_unidade_semente ps,
       TROPICAL.unidade_produto         us,
       TROPICAL.TIPO_CULTURA TC
 WHERE TUDO.SEQ_PLA_PENEIRA   = UP.SEQ_PLA_PENEIRA(+)
   AND TUDO.SEQ_PLA_VARIEDADE = UV.SEQ_PLA_VARIEDADE
   AND TUDO.SEQ_PLA_CLASSE    = UC.SEQ_PLA_CLASSE(+)
   AND TUDO.SEQ_PLA_PRODUTO   = PR.SEQ_PLA_PRODUTO
   AND TUDO.SEQ_PLA_MARCA     = MP.SEQ_PLA_MARCA(+)
   AND TUDO.COD_EMPRESA       = EM.COD_EMPRESA
   AND TUDO.COD_FILIAL        = FI.COD_FILIAL
   AND TUDO.COD_SAFRA         = SA.COD_SAFRA
   AND EM.COD_EMPRESA         = FI.COD_EMPRESA
   AND UV.SEQ_PLA_TIPO_CULT   = TC.SEQ_PLA_TIPO_CULT
   AND ((TUDO.X_TOTAL_PRODUZIDO <> 0) OR (TUDO.X_TOTAL_COMPRADO <> 0) OR (TUDO.X_TOTAL_VENDIDO <> 0) OR
        (TUDO.X_TOTAL_DEVOLVIDO <> 0) OR (TUDO.X_TOTAL_ENT_TRANSF) <> 0 OR (TUDO.X_TOTAL_ENTREGUE <> 0) OR (TUDO.X_TOTAL_PROJECAO <> 0) OR
        (TUDO.X_TOTAL_SAI_TRATAMENTO <> 0) OR (TUDO.X_TOTAL_SAI_DESCARTE <> 0) OR (TUDO.X_TOTAL_RESERVAS <> 0) OR (TUDO.X_TOTAL_RESERVAS_UTS <> 0))
   and tudo.seq_pla_produto   = ps.seq_pla_produto(+)
   and ps.seq_pla_unidade     = us.seq_pla_unidade(+)
 --AND TUDO.COD_EMPRESA = '1'
 --AND TUDO.COD_SAFRA = '20'
   GROUP BY TUDO.SEQ_PLA_PENEIRA,
            TUDO.SEQ_PLA_CLASSE,
            UC.SIGLA_CLASSE,
            TUDO.SEQ_PLA_VARIEDADE,
            TUDO.EMBARQUE,
            UP.SIGLA_PENEIRA,
            UV.DESC_VARIEDADE,
            UC.SIGLA_CLASSE,
            PR.SIGLA_PRODUTO,
            PR.SEQ_PLA_PRODUTO,
            EM.SIGLA_EMPRESA,
            EM.COD_EMPRESA,
            FI.COD_FILIAL,
            SA.COD_SAFRA,
            FI.SIGLA_FILIAL,
			TC.SEQ_PLA_TIPO_CULT,
            TC.DESC_CULTURA,
            MP.DESCRICAO_MARCA,
            SA.DESCRICAO_SAFRA,
            us.seq_pla_unidade,
            us.sigla_unidade,
            us.qtde_unidade,
            uv.seq_pla_variedade,
            uc.seq_pla_classe,
            up.seq_pla_peneira)  x
GROUP BY    X.SEQ_PLA_CLASSE,
            X.SIGLA_CLASSE,
      X.seq_pla_unidade,
      X.sigla_unidade,
      X.qtde_unidade,
      X.SEQ_PLA_PENEIRA,
      X.SEQ_PLA_VARIEDADE,
      X.EMBARQUE,
      X.DESCRICAO_MARCA,
      X.SIGLA_PENEIRA,
      X.DESC_VARIEDADE,
      X.SIGLA_EMPRESA,
      X.SIGLA_FILIAL,
      X.DESCRICAO_SAFRA,
      X.COD_EMPRESA,
      X.COD_FILIAL,
      X.COD_SAFRA,
	  X.SEQ_PLA_TIPO_CULT,
      X.CULTURA;
