CREATE OR REPLACE VIEW VW_SALDO_CONTA_BANCARIA_CAIXA AS
SELECT SUM(ROUND(NVL(SC.SALDO_CONTA  ,0),2)) as SALDO_CONTA,
       SUM(ROUND(NVL(MV.VALOR_DEBITO ,0),2)) as VALOR_DEBITO,
       SUM(ROUND(NVL(MV.VALOR_CREDITO,0),2)) as VALOR_CREDITO,
       SUM(ROUND(ROUND(NVL(SC.SALDO_CONTA,0),2) - ROUND(NVL(MV.DEBITO_ANTERIOR,0),2) + ROUND(NVL(MV.CREDITO_ANTERIOR,0),2),2)) AS SALDO_ANTERIOR,
       SUM(ROUND(ROUND(NVL(SC.SALDO_CONTA,0),2) - ROUND(NVL(MV.DEBITO_ANTERIOR,0),2) + ROUND(NVL(MV.CREDITO_ANTERIOR,0),2) - ROUND(NVL(MV.VALOR_DEBITO,0),2) + ROUND(NVL(MV.VALOR_CREDITO,0),2),2)) AS SALDO_ATUAL,
       SUM(ROUND(ROUND(NVL(SC.SALDO_CONTA,0),2) - ROUND(NVL(MV.DEBITO_ANTERIOR,0),2) + ROUND(NVL(MV.CREDITO_ANTERIOR,0),2) - ROUND(NVL(MV.VALOR_DEBITO,0),2) + ROUND(NVL(MV.VALOR_CREDITO,0),2),2)) AS SALDO_ATUAL_REAL,
       MV.CTB_TABELA,
       MV.CTB_CONTA,
       PC.NOME_CONTA
  FROM AGRICOLA.CTB_PLANO_CONTAS PC,
       (SELECT CT.CTB_TABELA,
               CT.CTB_CONTA,
               SUM(DECODE(HI.DEB_CRED,'D',DECODE(SIGN(TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY')- TO_DATE('01/01/2000', 'DD/MM/YYYY')),-1,ROUND(FI.VALOR_REAL,2)+ROUND(DECODE(FI.JUROS_CPAGAR,'S',0,DECODE(FI.VALOR_JUROS,NULL,0,FI.VALOR_JUROS)-DECODE(FI.VALOR_ANTECIPACAO,NULL,0,FI.VALOR_ANTECIPACAO)),2),0),0)) AS DEBITO_ANTERIOR,
               SUM(DECODE(HI.DEB_CRED,'C',DECODE(SIGN(TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY')- TO_DATE('01/01/2000', 'DD/MM/YYYY')),-1,ROUND(FI.VALOR_REAL,2)+ROUND(DECODE(FI.JUROS_CPAGAR,'S',0,DECODE(FI.VALOR_JUROS,NULL,0,FI.VALOR_JUROS)-DECODE(FI.VALOR_ANTECIPACAO,NULL,0,FI.VALOR_ANTECIPACAO)),2),0),0)) AS CREDITO_ANTERIOR,
               SUM(DECODE(HI.DEB_CRED,'D',DECODE(SIGN(TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY')- TO_DATE('01/01/2000', 'DD/MM/YYYY')),-1,0,DECODE(SIGN(TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY')- TO_DATE(SYSDATE, 'DD/MM/YYYY')),1,0,ROUND(FI.VALOR_REAL,2)+ROUND(DECODE(FI.JUROS_CPAGAR,'S',0,DECODE(FI.VALOR_JUROS,NULL,0,FI.VALOR_JUROS)-DECODE(FI.VALOR_ANTECIPACAO,NULL,0,FI.VALOR_ANTECIPACAO)),2))),0)) AS VALOR_DEBITO,
               SUM(DECODE(HI.DEB_CRED,'C',DECODE(SIGN(TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY')- TO_DATE('01/01/2000', 'DD/MM/YYYY')),-1,0,DECODE(SIGN(TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY')- TO_DATE(SYSDATE, 'DD/MM/YYYY')),1,0,ROUND(FI.VALOR_REAL,2)+ROUND(DECODE(FI.JUROS_CPAGAR,'S',0,DECODE(FI.VALOR_JUROS,NULL,0,FI.VALOR_JUROS)-DECODE(FI.VALOR_ANTECIPACAO,NULL,0,FI.VALOR_ANTECIPACAO)),2))),0)) AS VALOR_CREDITO
          FROM AGRICOLA.FIN_MOVIMENTO  FI,
               AGRICOLA.FIN_HISTORICOS HI,
               AGRICOLA.FIN_CONTAS     CT
         WHERE FI.SEQ_PLA_FIN_HIST   = HI.SEQ_PLA_FIN_HIST
           AND FI.SEQ_PLA_FIN_CONTA  = CT.SEQ_PLA_FIN_CONTA
           AND NVL(FI.CANCELADO,'N') = 'N'
           AND NVL(CT.ATIVO,'S') = 'S'
           AND TO_DATE(TRUNC(FI.DATA_DOCUM),'DD/MM/YYYY') <= TO_DATE(SYSDATE, 'DD/MM/YYYY')
           --AND CT.TIPO_CONTA IN ('C','T','G','B')
           --AND NVL(HI.ADIANTAMENTO,'N') = 'N' - NA BAIXA PODE CONSIDERAR OS ADIANTAMENTOS POIS JÁ FORAM BAIXADOS
       GROUP BY CT.CTB_TABELA,CT.CTB_CONTA
       ) MV,
       (SELECT CTB_TABELA,
               CTB_CONTA,
               SUM(NVL(SALDO_FINANCEIRO,0)) AS SALDO_CONTA
          FROM AGRICOLA.CTB_SALDO_CONTAS
         WHERE 1 = 1
           AND CTB_CONTA > 99999
         GROUP BY CTB_TABELA,CTB_CONTA
       ) SC
 WHERE PC.GRAU       = '5'
   AND PC.CTB_TABELA = MV.CTB_TABELA (+)
   AND PC.CTB_CONTA  = MV.CTB_CONTA  (+)
   AND PC.CTB_TABELA = SC.CTB_TABELA (+)
   AND PC.CTB_CONTA  = SC.CTB_CONTA  (+)
   AND EXISTS (SELECT FIC.CTB_TABELA||FIC.CTB_CONTA FROM AGRICOLA.FIN_CONTAS FIC WHERE FIC.ATIVO = 'S' AND FIC.CTB_TABELA||FIC.CTB_CONTA =PC.CTB_TABELA||PC.CTB_CONTA)   
   AND (PC.CTB_TABELA,PC.CTB_CONTA) IN (SELECT CTB_TABELA,CTB_CONTA
                                          FROM AGRICOLA.FIN_CONTAS
                                         WHERE 1=1
                                           --AND TIPO_CONTA IN ('C','T','G','B')
                                           )
 GROUP BY MV.CTB_TABELA, MV.CTB_CONTA, PC.NOME_CONTA;
