CREATE OR REPLACE VIEW VW_VALOR_MES_DEBITO_FUTURO AS
SELECT (SUM(NVL(CR.VALOR_DOCUM,0)) + SUM(NVL(CR.VALOR_JUROS,0)) - SUM(NVL(CR.VALOR_DESCONTO,0))) AS VALOR_DEBITO,
       CASE EXTRACT(MONTH FROM TO_DATE(CR.DATA_VCTO,'DD/MM/YYYY'))
         WHEN 1 THEN 'Janeiro'
         WHEN 2 THEN 'Fevereiro'
         WHEN 3 THEN 'Março'
         WHEN 4 THEN 'Abril'
         WHEN 5 THEN 'Maio'
         WHEN 6 THEN 'Junho'
         WHEN 7 THEN 'Julho'
         WHEN 8 THEN 'Agosto'
         WHEN 9 THEN 'Setembro'
         WHEN 10 THEN 'Outubro'
         WHEN 11 THEN 'Novembro'
         WHEN 12 THEN 'Dezembro'
       END AS MES,
       EXTRACT(YEAR FROM TO_DATE(CR.DATA_VCTO,'DD/MM/YYYY')) AS ANO,
       TO_CHAR(CR.DATA_VCTO, 'YYYY/MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''') AS MES_ANO,
       CONCAT(TO_CHAR(CR.DATA_VCTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(CR.DATA_VCTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')) AS ID_MES,
       CR.COD_EMPRESA,
       CR.COD_SAFRA,
       EXTRACT(MONTH FROM TO_DATE(CR.DATA_VCTO,'DD/MM/YYYY')) AS MES_NUM,
       TRUNC(CR.DATA_VCTO) AS DATA
  FROM AGRICOLA.CONTAS_PAGAR       CR,
       AGRICOLA.FIN_HISTORICOS     FH,
       AGRICOLA.CTB_PLANO_CONTAS   PC,
       AGRICOLA.CLIENTES           CL,
       AGRICOLA.CLIENTES_ENDERECOS CE
 WHERE 1 = 1
   AND CR.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST(+)
   AND FH.CTB_TABELA        = PC.CTB_TABELA
   AND FH.CTB_CONTA         = PC.CTB_CONTA
   AND CR.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
   AND CR.SEQ_PLA_PAGAR   NOT IN (SELECT SEQ_PLA_PAGAR FROM AGRICOLA.PAGAR_PAGTOS RP WHERE RP.SEQ_PLA_PAGAR = CR.SEQ_PLA_PAGAR)
   AND NVL(FH.ADIANTAMENTO,'N') = 'N'
   AND UPPER(NVL(CR.FORM_LANCAMENTO,'AAA'))  <> 'DFMCTRSAIDACORRETOR'
   --AND EXTRACT(YEAR FROM TO_DATE(RP.DATA_REC,'DD/MM/YYYY')) = SUBSTR(EXTRACT(YEAR FROM SYSDATE),1,2) --PASSANDO O ANO ATUAL, CRIAR FILTRO PARA PASSAR O ANO (COMENTADO POIS PODE SER LANÇAMENTOS FUTUROS)
 GROUP BY EXTRACT(MONTH FROM TO_DATE(CR.DATA_VCTO,'DD/MM/YYYY')), EXTRACT(YEAR FROM TO_DATE(CR.DATA_VCTO,'DD/MM/YYYY')),
       TO_CHAR(CR.DATA_VCTO, 'YYYY/MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),
       CONCAT(TO_CHAR(CR.DATA_VCTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(CR.DATA_VCTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')),
       CR.COD_EMPRESA, CR.COD_SAFRA, TRUNC(CR.DATA_VCTO)
