CREATE OR REPLACE VIEW VW_VALOR_MES_DEB_FUT_DETALHE AS
SELECT CP.DOCUMENTO,
       CP.DATA_LCTO,
       PC.NOME_CONTA,
       CE.ENDERECO,
       CL.NOME_CLIENTE,
       CP.LIBERA_FLUXO,
       CP.DATA_VCTO,
       DECODE(DECODE(TD.PREDATADO,NULL,'N',TD.PREDATADO),'N',' ','*') AS PRE,
       CP.AUXILIAR,
       FH.DESC_FIN_HIST,
       CP.OBSERVACOES,
       CP.SEQ_PLA_PAGAR,
       TO_CHAR(CP.DATA_VCTO, 'YYYY/MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''') AS MES_ANO,
       CONCAT(TO_CHAR(CP.DATA_VCTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(CP.DATA_VCTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')) AS ID_MES,
       CP.COD_EMPRESA,
       CP.COD_SAFRA,
       (NVL(CP.VALOR_DOCUM,0) + NVL(CP.VALOR_JUROS,0) - NVL(CP.VALOR_DESCONTO,0)) AS VALOR_DEBITO,
       TRUNC(CP.DATA_VCTO) AS DATA
  FROM AGRICOLA.CONTAS_PAGAR       CP,
       AGRICOLA.FIN_HISTORICOS     FH,
       AGRICOLA.CTB_PLANO_CONTAS   PC,
       AGRICOLA.CLIENTES           CL,
       AGRICOLA.CLIENTES_ENDERECOS CE,
       AGRICOLA.TIPO_DOCUMENTO     TD
 WHERE 1 = 1
   AND CP.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST(+)
   AND FH.CTB_TABELA        = PC.CTB_TABELA
   AND FH.CTB_CONTA         = PC.CTB_CONTA
   AND CP.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
   AND CP.SEQ_PLA_TIPO_DOC  = TD.SEQ_PLA_TIPO_DOC
   AND CP.SEQ_PLA_PAGAR     NOT IN (SELECT RP.SEQ_PLA_PAGAR FROM AGRICOLA.PAGAR_PAGTOS RP WHERE RP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR)
   AND NVL(FH.ADIANTAMENTO,'N')                   = 'N'
   AND UPPER(NVL(CP.FORM_LANCAMENTO,'AAA'))      <> 'DFMCTRSAIDACORRETOR';
