CREATE OR REPLACE VIEW VW_VALOR_MES_CRED_FUT_DETALHE AS
SELECT CR.DOCUMENTO,
       CR.DATA_LCTO,
       PC.NOME_CONTA,
       CE.ENDERECO,
       CL.NOME_CLIENTE,
       CR.LIBERA_FLUXO,
       CR.DATA_VCTO,
       DECODE(DECODE(TD.PREDATADO,NULL,'N',TD.PREDATADO),'N',' ','*') AS PRE,
       CR.AUXILIAR,
       FH.DESC_FIN_HIST,
       CR.OBSERVACOES,
       CR.SEQ_PLA_RECEBER,
       CR.COD_EMPRESA,
       CR.COD_SAFRA,
       TO_CHAR(CR.DATA_VCTO, 'YYYY/MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''') AS MES_ANO,
       CONCAT(TO_CHAR(CR.DATA_VCTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(CR.DATA_VCTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')) AS ID_MES,
       (NVL(CR.VALOR_DOCUM,0) + NVL(CR.VALOR_JUROS,0) - NVL(CR.VALOR_DESCONTO,0)) AS VALOR_CREDITO,
       TRUNC(CR.DATA_VCTO) as data
  FROM AGRICOLA.CONTAS_RECEBER     CR,
       AGRICOLA.FIN_HISTORICOS     FH,
       AGRICOLA.CTB_PLANO_CONTAS   PC,
       AGRICOLA.CLIENTES           CL,
       AGRICOLA.CLIENTES_ENDERECOS CE,
       AGRICOLA.TIPO_DOCUMENTO     TD
 WHERE 1 = 1
   AND CR.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST(+)
   AND FH.CTB_TABELA        = PC.CTB_TABELA
   AND FH.CTB_CONTA         = PC.CTB_CONTA
   AND CR.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
   AND CR.SEQ_PLA_TIPO_DOC  = TD.SEQ_PLA_TIPO_DOC
   AND CR.SEQ_PLA_RECEBER   NOT IN (SELECT RP.SEQ_PLA_RECEBER FROM AGRICOLA.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND NVL(FH.ADIANTAMENTO,'N')             = 'N'
   AND UPPER(NVL(CR.FORM_LANCAMENTO,'AAA')) <> 'DFMCTRSAIDACORRETOR';
