CREATE OR REPLACE VIEW VW_VALOR_MES_DEBITO AS
SELECT (SUM(NVL(PP.VALOR_PAGO,0)) + SUM(NVL(PP.VALOR_JUROS,0)) - SUM(NVL(PP.VALOR_DESCONTO,0))) AS VALOR_DEBITO,
       CASE EXTRACT(MONTH FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY'))
         WHEN 1 THEN 'Janeiro'
         WHEN 2 THEN 'Fevereiro'
         WHEN 3 THEN 'Março'
         WHEN 4 THEN 'Abril'
         WHEN 5 THEN 'Maio'
         WHEN 6 THEN 'Junho'
         WHEN 7 THEN 'Julho'
         WHEN 8 THEN 'Agosto'
         WHEN 9 THEN 'Setembro'
         WHEN 10 THEN 'Outubro'
         WHEN 11 THEN 'Novembro'
         WHEN 12 THEN 'Dezembro'
       END AS MES,
       EXTRACT(YEAR FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY')) AS ANO,
       TO_CHAR(PP.DATA_PGTO, 'YYYY/MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''') AS MES_ANO,
       CONCAT(TO_CHAR(PP.DATA_PGTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(PP.DATA_PGTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')) AS ID_MES,
       CP.COD_EMPRESA,
       CP.COD_SAFRA,
       EXTRACT(MONTH FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY')) AS MES_NUM,
       TRUNC(PP.DATA_PGTO) AS DATA
  FROM AGRICOLA.CONTAS_PAGAR       CP,
       AGRICOLA.FIN_HISTORICOS     FH,
       AGRICOLA.CTB_PLANO_CONTAS   PC,
       AGRICOLA.CLIENTES           CL,
       AGRICOLA.CLIENTES_ENDERECOS CE,
       AGRICOLA.PAGAR_PAGTOS       PP
 WHERE 1 = 1
   AND CP.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST(+)
   AND FH.CTB_TABELA        = PC.CTB_TABELA
   AND FH.CTB_CONTA         = PC.CTB_CONTA
   AND CP.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
   AND CP.SEQ_PLA_PAGAR     = PP.SEQ_PLA_PAGAR
   --AND NVL(FH.ADIANTAMENTO,'N') = 'N'  --PARA LANÇAMENTOS BAIXAIDOS PODE CONSIDERAR (COMENTADO)
   --AND EXTRACT(YEAR FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY')) = SUBSTR(EXTRACT(YEAR FROM SYSDATE),1,2) --COMENTADO POIS PODE TER LANÇAMENTOS FUTUROS
   --AND UPPER(NVL(CP.FORM_LANCAMENTO,'AAA'))  <> 'DFMCTRSAIDACORRETOR'  --PARA LANÇAMENTOS BAIXAIDOS PODE CONSIDERAR (COMENTADO)
 GROUP BY EXTRACT(MONTH FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY')), EXTRACT(YEAR FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY')),TO_CHAR(PP.DATA_PGTO, 'YYYY/MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),
       CONCAT(TO_CHAR(PP.DATA_PGTO, 'YYYY', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE'''),TO_CHAR(PP.DATA_PGTO, 'MM', 'NLS_DATE_LANGUAGE=''BRAZILIAN PORTUGUESE''')),
       CP.COD_EMPRESA, CP.COD_SAFRA, TRUNC(PP.DATA_PGTO)
 ORDER BY EXTRACT(MONTH FROM TO_DATE(PP.DATA_PGTO,'DD/MM/YYYY'));
