CREATE OR REPLACE VIEW VW_VALOR_CREDITO_CR AS
SELECT (SUM(NVL(RP.VALOR_RECEBIDO,0)) + SUM(NVL(RP.VALOR_JUROS,0))) - (SUM(NVL(RP.VALOR_DESCONTO,0))) AS VALOR_CREDITO,
       RP.SEQ_PLA_RECEBER,
       RP.DATA_REC,
       TRUNC(RP.DATA_REC) AS DATA
  FROM AGRICOLA.RECEBER_PAGTOS RP
 GROUP BY RP.SEQ_PLA_RECEBER, RP.DATA_REC;
