CREATE OR REPLACE VIEW VW_PLUVIOMETRO AS
SELECT
 PM."SEQ_PLA_MEDICAO",
 PM."SEQ_PLA_FAZENDA",
 PM."SEQ_PLA_PLUVIOMETRO",
 P.CODIGO AS DESC_PLUV,
 PM."DATA_MEDICAO",
 PM."HORA_MEDICAO",
 PM."QUANTIDADE_MM",
 PM."OBSERVACOES",
 PM."SEQ_PLA_FUNCIONARIO",
 PM."DATA_LCTO",
 PM."LATITUDE",
 PM."LONGITUDE",
 AG.SEQ_PLA_AGLOMERADO,
 AG.SIGLA_AGLOMERADO,
 AG.DESC_AGLOMERADO,
 FAZ.SIGLA_FAZENDA,
 FAZ.DESC_FAZENDA
FROM
   AGNEW.PLUV_MEDICOES PM,
   AGNEW.PLUVIOMETROS P,
   AGNEW.FAZENDAS FAZ,
   AGNEW.AGLOMERADOS AG
WHERE
PM.SEQ_PLA_PLUVIOMETRO = P.SEQ_PLA_PLUVIOMETRO
AND PM.SEQ_PLA_FAZENDA = FAZ.SEQ_PLA_FAZENDA
AND FAZ.SEQ_PLA_AGLOMERADO = AG.SEQ_PLA_AGLOMERADO
order by p.codigo;
