CREATE MATERIALIZED VIEW VW_SALDO_BALANCETE REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT RPAD(PC.COD_CONTA,8,' ') AS CTB_CONTA,
       PC.TAMANHO,
       PC.GRAU,
       PC.NOME_CONTA,
       TRUNC(CM.DATA_MVTO) AS DATA_MVTO,
       CM.COD_EMPRESA,
       CM.COD_FILIAL,
       CM.COD_SAFRA,
       SUM(CASE WHEN (TRUNC(FM.DATA_DOCUM)>= TO_DATE('01/01/2000','DD/MM/YYYY') AND TRUNC(FM.DATA_DOCUM)<= TRUNC(SYSDATE)) THEN Round(DECODE(CM.SEQ_PLA_PAGAR,NULL,DECODE(CM.SEQ_PLA_MOV_FIN,NULL,0,DECODE(FH.Deb_Cred,'D',CM.VALOR_REAL,0)),CM.VALOR_REAL),2) ELSE 0 END) AS TOTAL_DEBITO,
       SUM(CASE WHEN (TRUNC(FM.DATA_DOCUM)>= TO_DATE('01/01/2000','DD/MM/YYYY') AND TRUNC(FM.DATA_DOCUM)<= TRUNC(SYSDATE)) THEN Round(DECODE(CM.SEQ_PLA_RECEBER,NULL,DECODE(CM.SEQ_PLA_MOV_FIN,NULL,0,DECODE(FH.Deb_Cred,'C',CM.VALOR_REAL,0)),CM.VALOR_REAL),2) ELSE 0 END) AS TOTAL_CREDITO,
       COUNT(FM.SEQ_PLA_MOV_FIN) QTD_MOVI
  FROM AGRICOLA.GER_PLANO_CONTAS PC,
       AGRICOLA.GER_MOVIMENTO    CM,
       AGRICOLA.FIN_MOVIMENTO    FM,
       AGRICOLA.FIN_HISTORICOS   FH
 WHERE PC.COD_TABELA = (SELECT COD_TABELA_GERENCIAL FROM AGRICOLA.EMPRESAS WHERE ROWNUM = 1)
   AND PC.COD_TABELA = CM.COD_TABELA
   AND PC.COD_CONTA  = CM.COD_CONTA
   AND CM.COD_TABELA IN (SELECT COD_TABELA_GERENCIAL FROM AGRICOLA.EMPRESAS)
   AND CM.SEQ_PLA_MOV_FIN IS NOT NULL
   AND CM.SEQ_PLA_MOV_FIN  = FM.SEQ_PLA_MOV_FIN
   AND FM.SEQ_PLA_FIN_HIST = FH.SEQ_PLA_FIN_HIST
   AND DECODE(FM.CANCELADO,NULL,'N',FM.CANCELADO) <> 'S'
 GROUP BY PC.COD_CONTA,
          PC.TAMANHO,
          PC.GRAU,
          PC.NOME_CONTA,
          CM.DATA_MVTO,
          CM.COD_EMPRESA,
          CM.COD_FILIAL,
          CM.COD_SAFRA;
