CREATE MATERIALIZED VIEW GRAFICO_MOV_ALGODOEIRA 
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT EE.COD_EMPRESA,
       EE.COD_FILIAL,
       EE.COD_SAFRA,
       SA.DESCRICAO_SAFRA AS SAFRA,
       EP.SIGLA_EMPRESA||' - '||FI.SIGLA_FILIAL AS ALGODOEIRA,
       CL.SEQ_PLA_CLIENTE,
       CL.NOME_CLIENTE                          AS PRODUTOR,
       EE.DATA_ENTRADA,
       BE.DATA_BENEFICIAMENTO,
       ES.DATA_SAIDA,
       EE.NR_DOCUMENTO                          AS FARDAO,
       EER.SEQ_PLA_ENTRADA                      AS FARDAO_ROLINHO,
       EER.PESO_LIQUIDO                         AS PESO_FARDAO,
       FA.NUM_FARDO                             AS FARDINHO,
       FA.PESO_FARDO                            AS PESO_FARDINHO,
       MA.COD_MAQUINA                           AS PRENSA,
       TI.APELIDO                                  AS TIPO,
       ES.NR_DOCUMENTO                             AS NOTA_FISCAL,
       DECODE(VF.SEQ_PLA_VINC_TAKEUP,NULL,'N','S') AS TAKEUP,
       0 AS CAROCO,
       TU.DESCRICAO                                AS TURNO,
       FA.SEQ_PLA_FARDO
  FROM BANCO.EST_ENTRADAS_ROM EER,
       BANCO.EST_ENTRADAS EE,
       BANCO.LIGA_ENTRADA_BENEFICIAMENTO LB,
       BANCO.BENEFICIAMENTO BE,
       BANCO.FARDOS FA,
       BANCO.LIGA_SAIDA_FARDO LF,
       BANCO.EST_SAIDAS_ITENS ESI,
       BANCO.EST_SAIDAS ES,
       BANCO.SAFRAS SA,
       BANCO.CLIENTES CL,
       BANCO.CLIENTES_ENDERECOS CE,
       BANCO.TURNOS TU,
       BANCO.EMPRESAS EP,
       BANCO.FILIAIS FI,
       BANCO.MAQUINAS MA,
       BANCO.FARDO_CLASS_TERCEIROS FC,
       BANCO.TIPOS TI,
       BANCO.VINCULA_FARDOS_TAKEUP VF
 WHERE EE.SEQ_PLA_ENTRADA = EER.SEQ_PLA_ENTRADA
   AND EE.SEQ_PLA_ENTRADA = LB.SEQ_PLA_ENTRADA(+)
   AND LB.SEQ_PLA_BENEFICIAMENTO = BE.SEQ_PLA_BENEFICIAMENTO(+)
   AND LB.SEQ_PLA_BENEFICIAMENTO = FA.SEQ_PLA_BENEFICIAMENTO(+)
   AND LB.SEQ_PLA_ENTRADA        = FA.SEQ_PLA_ENTRADA(+)
   AND FA.SEQ_PLA_FARDO          = LF.SEQ_PLA_FARDO(+)
   AND LF.SEQ_PLA_SAI_ITEM       = ESI.SEQ_PLA_SAI_ITEM(+)
   AND ESI.SEQ_PLA_SAIDA         = ES.SEQ_PLA_SAIDA(+)
   AND EE.COD_SAFRA              = SA.COD_SAFRA(+)
   AND EE.SEQ_PLA_ENDERECO       = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE        = CL.SEQ_PLA_CLIENTE
   AND BE.SEQ_PLA_TURNO          = TU.SEQ_PLA_TURNO(+)
   AND FA.SEQ_PLA_MAQUINA        = MA.SEQ_PLA_PATRIMONIO(+)
   AND FA.SEQ_PLA_FARDO          = FC.SEQ_PLA_FARDO(+)
   AND FC.COD_TIPO               = TI.COD_TIPO(+)
   AND FA.SEQ_PLA_FARDO          = VF.SEQ_PLA_FARDO(+)
   AND BE.COD_EMPRESA            = EP.COD_EMPRESA(+)
   AND BE.COD_FILIAL             = FI.COD_FILIAL(+)
   AND BE.COD_EMPRESA            = FI.COD_EMPRESA(+)
   AND NOT EXISTS (SELECT VC.SEQ_PLA_ROM_MODULO FROM BANCO.VINC_ROM_MODULO_COLHIDO VC WHERE VC.SEQ_PLA_ENT_CARGA = EE.SEQ_PLA_ENTRADA AND VC.SEQ_PLA_ENTRADA IS NOT NULL)
   AND NVL(EER.CANCELADO,'N') <> 'S';
