CREATE MATERIALIZED VIEW VW_ACOMPANHAMENTO_EMBARQUE REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT EM.NOME_EMPRESA,
       EM.COD_EMPRESA,
       CS.COD_SAFRA,
       CL.NOME_CLIENTE,
       CS.NR_CONTRATO,
       DECODE(CS.TIPO_FRETE,'E','CIF','C','FOB') AS TIPO_FRETE,
       PD.DESCRICAO_PRODUTO,
       AR.SIGLA_ARMAZEM,
       CD.QUANTIDADE,
       NVL(BA.BAIXAS,0) AS EMBARCADO,
       (NVL(CD.QUANTIDADE,0) - NVL(BA.BAIXAS ,0) + NVL(DV.DEVOLUCAO,0)) AS EMBARCAR,
       TRUNC(CS.DATA_CONTRATO) AS DATA_CONTRATO,
       CD.INICIO_ENTREGA,
       CD.FINAL_ENTREGA,
       CR.DATA_VCTO,
       DECODE(NVL(CD.INICIA_ACOMP_EMBARQUE,'N'),'S', DECODE(SIGN(NVL(CD.QUANTIDADE,0) - NVL(BA.BAIXAS ,0) + NVL(DV.DEVOLUCAO,0)),0,'FINALIZADO',-1,'FINALIZADO','EMBARCANDO'),
                                                     DECODE(SIGN(NVL(CD.QUANTIDADE,0) - NVL(BA.BAIXAS ,0) + NVL(DV.DEVOLUCAO,0)),0,'FINALIZADO',-1,'FINALIZADO', 'A EMBARCAR')) AS STATUS,
       NVL(DECODE(CR.DATA_VCTO,NULL,TRUNC(CD.INICIO_ENTREGA) - (SELECT TRUNC(SYSDATE) FROM DUAL), TRUNC(CR.DATA_VCTO) - (SELECT TRUNC(SYSDATE) FROM DUAL)),0) AS DIAS_VCTO,
       NVL(DECODE(CR.DATA_VCTO,NULL,NULL, TRUNC(CD.INICIO_ENTREGA) - (SELECT TRUNC(SYSDATE) FROM DUAL)),0) AS DIAS_ENTREGA,
       TO_CHAR(TRUNC(CS.DATA_CONTRATO),'MM/YYYY') MES_ANO,
       TO_CHAR(TRUNC(CS.DATA_CONTRATO),'YYYYMM') MES_ANO_ID,
       CS.SEQ_PLA_PED_VENDA

  FROM AGRICOLA.CONTRATO_SAIDA          CS,
       AGRICOLA.CONTRATO_DESMEMBRAMENTO CD,
       AGRICOLA.CLIENTES_ENDERECOS      CE,
       AGRICOLA.CLIENTES                CL,
       AGRICOLA.EMPRESAS                EM,
       AGRICOLA.PRODUTOS                PD,
       AGRICOLA.ARMAZENS                AR,

       (SELECT SA.SEQ_PLA_CONT_DES,
               SUM(RO.PESO_BRUTO - RO.PESO_TARA) AS BAIXAS
          FROM AGRICOLA.CONTRATO_DESMEMBRAMENTO DE,
               AGRICOLA.EST_SAIDAS              SA,
               AGRICOLA.EST_SAIDAS_ROM          RO
         WHERE DE.SEQ_PLA_CONT_DES = SA.SEQ_PLA_CONT_DES
           AND SA.SEQ_PLA_SAIDA    = RO.SEQ_PLA_SAIDA
           AND NVL(RO.CANCELADO,'N') = 'N'
         GROUP BY SA.SEQ_PLA_CONT_DES) BA,

       (SELECT EET.SEQ_PLA_CTR_RETORNO,
               SUM(ETI.QUANTIDADE) AS DEVOLUCAO
          FROM AGRICOLA.EST_ENTRADAS            EET,
               AGRICOLA.EST_ENTRADAS_ITENS      ETI
         WHERE EET.SEQ_PLA_ENTRADA = ETI.SEQ_PLA_ENTRADA
           AND DECODE(EET.CANCELADO,NULL,'N',EET.CANCELADO) <> 'S'
         GROUP BY EET.SEQ_PLA_CTR_RETORNO) DV,

       (SELECT SEQ_PLA_ORIGEM,
               DATA_VCTO,
               DECODE(TIPO_RECBTO,'C','CARTEIRA','D','CRED.CONTA','O','OUTRAS','B','BOLETO') AS TIPO_RECBTO
          FROM AGRICOLA.CONTAS_RECEBER
         WHERE SEQ_PLA_RECEBER IN (SELECT MIN(SEQ_PLA_RECEBER)
                                     FROM AGRICOLA.CONTAS_RECEBER
                                    GROUP BY SEQ_PLA_ORIGEM)) CR

 WHERE CS.SEQ_PLA_PED_VENDA   = CD.SEQ_PLA_PED_VENDA
   AND CS.SEQ_PLA_END_ENTREGA = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE     = CL.SEQ_PLA_CLIENTE     (+)
   AND CS.COD_EMPRESA         = EM.COD_EMPRESA
   AND CS.SEQ_PLA_PRODUTO     = PD.SEQ_PLA_PRODUTO
   AND CD.SEQ_PLA_ARMAZEM     = AR.SEQ_PLA_ARMAZEM
   AND CD.SEQ_PLA_CONT_DES    = BA.SEQ_PLA_CONT_DES    (+)
   AND CD.SEQ_PLA_CONT_DES    = DV.SEQ_PLA_CTR_RETORNO (+)
   AND CS.SEQ_PLA_PED_VENDA   = CR.SEQ_PLA_ORIGEM      (+)
   AND TO_CHAR(TRUNC(CS.DATA_CONTRATO),'YYYYMM')    >= '200001'
  ORDER BY EM.NOME_EMPRESA, CL.NOME_CLIENTE, TO_CHAR(TRUNC(CS.DATA_CONTRATO),'MM/YYYY');
