CREATE MATERIALIZED VIEW VW_FRETE_ORCADO_REALIZADO
REFRESH FORCE ON DEMAND
START WITH TO_DATE('01-03-2021 15:36:03', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE + 10/24/60 
AS
SELECT CS.SEQ_PLA_PED_VENDA,
       CS.COD_EMPRESA,
       CS.COD_SAFRA,
       CS.NR_CONTRATO||'/'||CS.LETRA_CONTRATO AS CONTRATO,
       PR.DESCRICAO_PRODUTO                   AS PRODUTO,
       TRUNC(CS.DATA_CONTRATO)                AS DATA_CONTRATO,
       SUM(DISTINCT(NVL(CS.QUANTIDADE,0)))    AS QTDE_CONTRATO,
       SUM(DISTINCT(NVL(AA.QUANTIDADE,0)))    AS QTDE_ENTREGUE,
       SUM(DISTINCT(NVL(CS.PRECO_SACA,0)))    AS VLR_UNITARIO,
       SUM(DISTINCT(NVL(CS.VALOR_TOTAL,0)))   AS VLR_CONTRATO,
       ROUND((SUM(DISTINCT(NVL(CS.QUANTIDADE,0))) * SUM(DISTINCT(NVL(CS.VALOR_FRETE,1))))/1000,2) AS VLR_FRETE_ORCADO,
       SUM((NVL(CA.VALOR_DOCUM,0))) + SUM((NVL(FDEV.VALOR_FRETE_DEV,0)))   AS VLR_FRETE_REALIZADO, --jhony hebert 01/03/2021 ch 67686 removi o distinct
       ROUND((SUM(DISTINCT(NVL(CS.QUANTIDADE,0))) * SUM(DISTINCT(NVL(CS.VALOR_FRETE,1))))/1000,2) - (SUM((NVL(CA.VALOR_DOCUM,0))) + SUM((NVL(FDEV.VALOR_FRETE_DEV,0)))) AS DESVIO_FRETE
  FROM CERES1002.CONTRATO_SAIDA          CS,
       CERES1002.CONTRATO_DESMEMBRAMENTO CD,
       CERES1002.EST_SAIDAS              ES,
       CERES1002.EST_SAIDAS_ITENS        EI,
       CERES1002.EST_LIGA_FRETE_ROMANEIO LG,
       CERES1002.EST_FRETE_ROMANEIO      EF,
       CERES1002.EMPRESAS                EM,
       CERES1002.CLIENTES                CL,
       CERES1002.CLIENTES_ENDERECOS      CE,
       CERES1002.CONTAS_PAGAR            CA,
       CERES1002.PRODUTOS                PR,
       (SELECT SUM(QUANTIDADE) AS QUANTIDADE,
               SEQ_PLA_ORIGEM
          FROM (SELECT CD.SEQ_PLA_PED_VENDA as SEQ_PLA_ORIGEM,
                       SUM(ESI.QUANTIDADE) QUANTIDADE
                  FROM CERES1002.CONTRATO_DESMEMBRAMENTO CD,
                       CERES1002.EST_SAIDAS              ES,
                       CERES1002.EST_SAIDAS_ITENS        ESI
                 WHERE CD.SEQ_PLA_CONT_DES    = ES.SEQ_PLA_CONT_DES
                   AND ES.SEQ_PLA_SAIDA       = ESI.SEQ_PLA_SAIDA
                   AND NVL(ES.CANCELADO,'N')= 'N'
                 GROUP BY CD.SEQ_PLA_PED_VENDA
                UNION
                SELECT DECODE(EE.SEQ_PLA_ORIGEM,'', CD.SEQ_PLA_PED_VENDA) AS SEQ_PLA_ORIGEM,
                       SUM(NVL(EI.QUANTIDADE, 0))*-1 QUANTIDADE
                  FROM CERES1002.EST_ENTRADAS            EE,
                       CERES1002.EST_ENTRADAS_ITENS      EI,
                       CERES1002.CONTRATO_DESMEMBRAMENTO CD
                 WHERE EE.SEQ_PLA_ENTRADA    = EI.SEQ_PLA_ENTRADA
                  AND (EE.SEQ_PLA_CTR_RETORNO  IN (SELECT CDD.SEQ_PLA_CONT_DES
                                                     FROM CERES1002.CONTRATO_DESMEMBRAMENTO CDD
                                                    WHERE CDD.SEQ_PLA_PED_VENDA = EE.SEQ_PLA_ORIGEM
                                                       OR CDD.SEQ_PLA_PED_VENDA = CD.SEQ_PLA_PED_VENDA)
                  AND CD.SEQ_PLA_CONT_DES = EE.SEQ_PLA_CTR_RETORNO)
                  AND NVL(EE.CANCELADO,'N') = 'N'
                GROUP BY EE.SEQ_PLA_ORIGEM, CD.SEQ_PLA_PED_VENDA
                UNION
                SELECT ES.SEQ_PLA_ORIGEM,
                       SUM(ESI.QUANTIDADE) QUANTIDADE
                  FROM CERES1002.EST_SAIDAS              ES,
                       CERES1002.EST_SAIDAS_ITENS        ESI,
                       CERES1002.EST_SAIDAS_ROM          ER,
                       (SELECT LR.SEQ_PLA_SAI_ITEM,
                               EE.NR_DOCUMENTO
                          FROM CERES1002.EST_ENTRADAS          EE,
                               CERES1002.EST_ENTRADAS_ITENS    EI,
                               CERES1002.LIGA_NF_RETORNO       LR
                         WHERE EE.SEQ_PLA_ENTRADA  = EI.SEQ_PLA_ENTRADA
                           AND LR.SEQ_PLA_ENT_ITEM = EI.SEQ_PLA_ENT_ITEM) DV
                 WHERE ES.SEQ_PLA_SAIDA      = ESI.SEQ_PLA_SAIDA
                   AND ES.SEQ_PLA_SAIDA      = ER.SEQ_PLA_SAIDA   (+)
                   AND ESI.SEQ_PLA_SAI_ITEM  = DV.SEQ_PLA_SAI_ITEM(+)
                   AND NVL(ES.CANCELADO,'N') = 'N'
                 GROUP BY ES.SEQ_PLA_ORIGEM )
         GROUP BY SEQ_PLA_ORIGEM) AA,
       (SELECT DECODE(EEF.SEQ_PLA_ORIGEM,'', CDF.SEQ_PLA_PED_VENDA) AS SEQ_PLA_ORIGEM,
               SUM(NVL(CAF.VALOR_DOCUM,0)) AS VALOR_FRETE_DEV
          FROM CERES1002.EST_ENTRADAS            EEF,
               CERES1002.EST_ENTRADAS_ITENS      EIF,
               CERES1002.CONTRATO_DESMEMBRAMENTO CDF,
               CERES1002.EST_LIGA_FRETE_ROMANEIO LGF,
               CERES1002.EST_FRETE_ROMANEIO      EFF,
               CERES1002.CONTAS_PAGAR            CAF
         WHERE EEF.SEQ_PLA_ENTRADA    = EIF.SEQ_PLA_ENTRADA
           AND EEF.SEQ_PLA_ENTRADA    = LGF.SEQ_PLA_ENTRADA
           AND LGF.SEQ_PLA_FRETE      = EFF.SEQ_PLA_FRETE    (+)
           AND EFF.SEQ_PLA_PAGAR      = CAF.SEQ_PLA_PAGAR    (+)
           AND (EEF.SEQ_PLA_CTR_RETORNO IN (SELECT CDD2.SEQ_PLA_CONT_DES
                                              FROM CERES1002.CONTRATO_DESMEMBRAMENTO CDD2
                                             WHERE CDD2.SEQ_PLA_PED_VENDA = EEF.SEQ_PLA_ORIGEM
                                                OR CDD2.SEQ_PLA_PED_VENDA = CDF.SEQ_PLA_PED_VENDA)
           AND CDF.SEQ_PLA_CONT_DES   = EEF.SEQ_PLA_CTR_RETORNO)
           AND NVL(EEF.CANCELADO,'N') = 'N'
         GROUP BY EEF.SEQ_PLA_ORIGEM, CDF.SEQ_PLA_PED_VENDA) FDEV

 WHERE CS.SEQ_PLA_PED_VENDA   = CD.SEQ_PLA_PED_VENDA
   AND CD.SEQ_PLA_CONT_DES    = ES.SEQ_PLA_CONT_DES (+)
   AND ES.SEQ_PLA_SAIDA       = EI.SEQ_PLA_SAIDA    (+)
   AND ES.SEQ_PLA_SAIDA       = LG.SEQ_PLA_SAIDA    (+)
   AND LG.SEQ_PLA_FRETE       = EF.SEQ_PLA_FRETE    (+)
   AND CS.COD_EMPRESA         = EM.COD_EMPRESA
   AND CS.SEQ_PLA_END_ENTREGA = CE.SEQ_PLA_ENDERECO (+)
   AND CE.SEQ_PLA_CLIENTE     = CL.SEQ_PLA_CLIENTE  (+)
   AND EF.SEQ_PLA_PAGAR       = CA.SEQ_PLA_PAGAR    (+)
   AND CS.SEQ_PLA_PED_VENDA   = AA.SEQ_PLA_ORIGEM   (+)
   AND CS.SEQ_PLA_PED_VENDA   = FDEV.SEQ_PLA_ORIGEM (+)
   AND CS.SEQ_PLA_PRODUTO     = PR.SEQ_PLA_PRODUTO  (+)
   AND NVL(CS.TIPO_FRETE,'E') = 'E'
   AND NVL(ES.CANCELADO, 'N') = 'N'
   AND TO_CHAR(TRUNC(CS.DATA_CONTRATO),'YYYYMM')    >= '200001'

 GROUP BY CS.SEQ_PLA_PED_VENDA,
          CS.DATA_CONTRATO,
          CS.NR_CONTRATO||'/'||CS.LETRA_CONTRATO,
          EM.NOME_EMPRESA,
          CL.NOME_CLIENTE,
          PR.DESCRICAO_PRODUTO,
          CS.COD_EMPRESA,
          CS.COD_SAFRA

   HAVING SUM(DISTINCT(NVL(CA.VALOR_DOCUM,0))) + SUM(DISTINCT(NVL(FDEV.VALOR_FRETE_DEV,0))) <> 0;
