CREATE MATERIALIZED VIEW VW_FRETE_ORCADO_DETALHE
REFRESH FORCE ON DEMAND
START WITH TO_DATE('05-03-2021 10:31:17', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE + 10/24/60 
AS
SELECT CS.SEQ_PLA_PED_VENDA,
       CS.NR_CONTRATO||'/'||CS.LETRA_CONTRATO AS CONTRATO,
       CS.COD_EMPRESA,
       CS.COD_SAFRA,
       CA.DOCUMENTO,
       ES.NR_DOCUMENTO,
       TRUNC(ES.DATA_EMISSAO) AS DATA_FATURAMENTO,
       NVL(EI.QUANTIDADE,0)QUANTIDADE,
       NVL(LG.VALOR_TONELADA,0)VALOR_TONELADA,
       NVL(DECODE((SELECT COUNT(LG2.SEQ_PLA_LIGA_FRETE)
                 FROM CERES1002.EST_LIGA_FRETE_ROMANEIO LG2
                WHERE LG2.SEQ_PLA_FRETE = EF.SEQ_PLA_FRETE), 1 ,NVL(CA.VALOR_DOCUM,0),ROUND(LG.QUANTIDADE*(LG.VALOR_TONELADA/1000),2)),0) AS VLR_FRETE_REALIZADO,
       NVL(ROUND((((NVL(CS.QUANTIDADE,0))) * ((NVL(CS.VALOR_FRETE,1))))/1000,2),0) AS VLR_FRETE_ORCADO

  FROM CERES1002.CONTRATO_SAIDA          CS,
       CERES1002.CONTRATO_DESMEMBRAMENTO CD,
       CERES1002.EST_SAIDAS              ES,
       CERES1002.EST_SAIDAS_ITENS        EI,
       CERES1002.EST_LIGA_FRETE_ROMANEIO LG,
       CERES1002.EST_FRETE_ROMANEIO      EF,
       CERES1002.CONTAS_PAGAR            CA

 WHERE CS.SEQ_PLA_PED_VENDA   = CD.SEQ_PLA_PED_VENDA
   AND CD.SEQ_PLA_CONT_DES    = ES.SEQ_PLA_CONT_DES
   AND ES.SEQ_PLA_SAIDA       = EI.SEQ_PLA_SAIDA    (+)
   AND ES.SEQ_PLA_SAIDA       = LG.SEQ_PLA_SAIDA    (+)
   AND LG.SEQ_PLA_FRETE       = EF.SEQ_PLA_FRETE    (+)
   AND EF.SEQ_PLA_PAGAR       = CA.SEQ_PLA_PAGAR    (+)
   AND NVL(CS.TIPO_FRETE,'E') = 'E'
   AND NVL(ES.CANCELADO, 'N') = 'N'
   AND TO_CHAR(TRUNC(CS.DATA_CONTRATO),'YYYYMM')    >= '200001';
