CREATE MATERIALIZED VIEW FLUXO_CAIXA_BI
REFRESH FORCE ON DEMAND
START WITH SYSDATE  NEXT SYSDATE + 5/24/60 
AS
SELECT GF.SEQ_PLA_AGRUPADOR,
       GF.DESCRICAO AS GRUPO,
       GF.ORDEM,
       'FC' AS TIPO,
       FC.NOME_CLIENTE,
       FC.DATA_VCTO,
       FC.VLR_EM_REAIS AS VLR_REAL,
       FC.VLR_EM_DOLAR AS VLR_DOLAR
  FROM COOAMI.VW_FLUXO_CAIXA        FC,
       COOAMI.TIPOS_LANCTOS         TL,
       COOAMI.GRUPO_GER_FLUXO_CAIXA GF
 WHERE FC.COD_TIPO_LCTO     = TL.COD_TIPO_LCTO
   AND TL.SEQ_PLA_AGRUPADOR = GF.SEQ_PLA_AGRUPADOR

UNION ALL

SELECT FC.SEQ_PLA_AGRUPADOR,
       'EMPRESTIMO' AS GRUPO,
       98 AS ORDEM,
       'EM' AS TIPO,
       FC.NOME_CLIENTE,
       FC.DATA_VCTO,
       FC.VALOR AS VLR_REAL, --COLOCAR ABS
       0 AS VLR_DOLAR
  FROM COOAMI.VW_FICHA_FLUXO_CAIXA FC
 WHERE FC.DEB_CRED_FICHA_FINAN = 'D'

UNION ALL

SELECT FC.SEQ_PLA_AGRUPADOR,
       'FICHA' AS GRUPO,
       99 AS ORDEM,
       'FF' AS TIPO,
       FC.NOME_CLIENTE,
       FC.DATA_VCTO,
       FC.VALOR AS VLR_REAL,
       0 AS VLR_DOLAR
  FROM COOAMI.VW_FICHA_FLUXO_CAIXA FC
 WHERE FC.DEB_CRED_FICHA_FINAN = 'C'

UNION ALL

SELECT '100' AS SEQ_PLA_AGRUPADOR,
       'FICHA CONTA CORRENTE' AS GRUPO,
       100 AS ORDEM,
       'CO' AS TIPO,
       FC.NOME_CLIENTE,
       FC.DATA_LCTO,
       FC.VALOR_CONVERTIDO AS VLR_REAL,
       0 AS VLR_DOLAR
  FROM COOAMI.VW_FICHA_CONTA_CORRENTE FC

UNION ALL

SELECT '101' AS SEQ_PLA_AGRUPADOR,
       'BANCO' AS GRUPO,
       101 AS ORDEM,
       'BB' AS TIPO,
       FC.NOME_CONTA AS NOME_CLIENTE,
       FC.DATA_DOCUM,
       FC.VALOR AS VLR_REAL,
       0 AS VLR_DOLAR
  FROM COOAMI.VW_BANCO_FLUXO_CAIXA FC
  WHERE UPPER(TIPO_CONTA) <> 'I'

UNION ALL

SELECT '101' AS SEQ_PLA_AGRUPADOR,
       'BANCO INVESTIMENTO' AS GRUPO,
       101 AS ORDEM,
       'BB' AS TIPO,
       FC.NOME_CONTA AS NOME_CLIENTE,
       FC.DATA_DOCUM,
       FC.VALOR AS VLR_REAL,
       0 AS VLR_DOLAR
  FROM COOAMI.VW_BANCO_FLUXO_CAIXA FC
  WHERE UPPER(FC.TIPO_CONTA)  = 'I'

UNION ALL

SELECT '102' AS SEQ_PLA_AGRUPADOR,
       'CHEQUE A COMPENSAR' AS GRUPO,
       102 AS ORDEM,
       'CC' AS TIPO,
       FC.NOME_CLIENTE,
       DATA_DOCUM,
       FC.VLR_REAL AS VLR_REAL,
       0 AS VLR_DOLAR
  FROM COOAMI.VW_CHEQUE_FLUXO_CAIXA FC

UNION ALL

SELECT FC.SEQ_PLA_AGRUPADOR,
       'PREVISAO' AS GRUPO,
       999 AS ORDEM,
       'PR' AS TIPO,
       FC.NOME_CLIENTE,
       DATA_VCTO,
       FC.VLR_EM_REAIS AS VLR_REAL,
       FC.VLR_EM_DOLAR AS VLR_DOLAR
  FROM COOAMI.VW_PREVISAO_FLUXO_CAIXA FC;
