CREATE MATERIALIZED VIEW VW_POTENCIALIZACAO_AGENTE REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT DISTINCT PO.COD_SAFRA,
       CLA.NOME_CLIENTE NOME_AGENTE,
       AG.SEQ_PLA_AGENTE,
       PR.DESCRICAO_PRODUTO,
       PR.SEQ_PLA_PRODUTO,
       PO.QUANTIDADE_SC as PRODUTO_SHARE,
       ROUND((NVL(PO.QTD_CLIE,0) * 100) / NVL(PR.QTD_CLIE,0),2) AS PORCENTO,
       ROUND((NVL(PO.QUANTIDADE_SC,0) * 100) / NVL(PR.QUANTIDADE_SC,0),2) AS PORCENTO2,       
       FAT.QUANTIDADE AS FATURAMENTO,
       ROUND((FAT.QUANTIDADE * 100) / PO.QUANTIDADE_SC,2) AS PORCENTO_FAT

  FROM AGRICOLA.AGENTES              AG,
       AGRICOLA.CLIENTES             CLA, --AGENTE
       AGRICOLA.CLIENTES_ENDERECOS   CE,
       AGRICOLA.AGENTES_PERIODOS     AP,
       (SELECT CL.SEQ_PLA_AGENTE,
               CP.SEQ_PLA_PRODUTO,
               CP.COD_SAFRA,
               SUM(NVL(CP.QUANTIDADE_SC,0)) QUANTIDADE_SC,
               COUNT(CL.SEQ_PLA_CLIENTE) QTD_CLIE
          FROM AGRICOLA.CLIENTES             CL,
               AGRICOLA.CLIENTE_POTENCIAL_SC CP
         WHERE CL.SEQ_PLA_CLIENTE = CP.SEQ_PLA_CLIENTE
           AND CL.SEQ_PLA_AGENTE IS NOT NULL
         GROUP BY CL.SEQ_PLA_AGENTE,CP.SEQ_PLA_PRODUTO,CP.COD_SAFRA
        )PO, --TDS OS PRODUTOS DA CARTELA DAQUELE AGENTE
       (SELECT PD.SEQ_PLA_PRODUTO, PD.DESCRICAO_PRODUTO,CP.COD_SAFRA,
               SUM(NVL(CP.QUANTIDADE_SC,0)) QUANTIDADE_SC,
               COUNT(CL.SEQ_PLA_CLIENTE) QTD_CLIE
          FROM AGRICOLA.CLIENTES             CL,
               AGRICOLA.CLIENTE_POTENCIAL_SC CP,
               AGRICOLA.PRODUTOS             PD
         WHERE CL.SEQ_PLA_CLIENTE = CP.SEQ_PLA_CLIENTE
           AND CP.SEQ_PLA_PRODUTO = PD.SEQ_PLA_PRODUTO
           AND CL.SEQ_PLA_AGENTE IS NOT NULL
         GROUP BY PD.SEQ_PLA_PRODUTO, PD.DESCRICAO_PRODUTO,CP.COD_SAFRA
        )PR, --SOMATORIA DE TODOS OS CLIENTES POR PRODUTO
       (SELECT AG.SEQ_PLA_AGENTE,
               CS.SEQ_PLA_PRODUTO,
               CS.COD_SAFRA,
               ROUND(SUM(NVL(CS.QUANTIDADE ,0)),2) AS QUANTIDADE,
               ROUND(SUM(NVL(CS.VALOR_TOTAL,0)),2) AS VALOR_TOTAL

          FROM AGRICOLA.ACORDO_POTENCIAL   AP,
               AGRICOLA.AGENTES            AG,--agente interno
               AGRICOLA.CONTRATO_SAIDA     CS,--FATURAMENTO
               --CLI/FORN
               AGRICOLA.CLIENTES_ENDERECOS CE,
               AGRICOLA.CLIENTES           CL

         WHERE AP.SEQ_PLA_AGENTE_IN          = AG.SEQ_PLA_AGENTE
           AND AP.SEQ_PLA_ACORDO_POTENCIAL   = CS.SEQ_PLA_ACORDO_POTENCIAL
           --SÓ POSSO CONSIDERAR FATURAMENTO OS CONTRATOS QUE DE FATO FORAM FEITOS PELO AGENTE DAQUELE CLIENTE
           AND CS.SEQ_PLA_END_ENTREGA        = CE.SEQ_PLA_ENDERECO
           AND CE.SEQ_PLA_CLIENTE            = CL.SEQ_PLA_CLIENTE
           AND AG.SEQ_PLA_AGENTE             = CL.SEQ_PLA_AGENTE
           --
           AND EXISTS (SELECT SC.SEQ_PLA_CLIENTE FROM AGRICOLA.CLIENTE_POTENCIAL_SC SC WHERE SC.SEQ_PLA_CLIENTE = CL.SEQ_PLA_CLIENTE)--Só vai trazer os faturamentos dos clientes parametrizados.           
           AND NVL(AG.ATIVO, 'N')            = 'S'
           AND NVL(AP.STATUS,'A')            = 'F'
           AND NVL(AP.TIPO_CTR,'C')          = 'V'
           GROUP BY AG.SEQ_PLA_AGENTE, CS.SEQ_PLA_PRODUTO,CS.COD_SAFRA
         ) FAT --FATURAMENTO

 WHERE AG.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE  = CLA.SEQ_PLA_CLIENTE
   AND AG.SEQ_PLA_AGENTE   = AP.SEQ_PLA_AGENTE
   AND AG.SEQ_PLA_AGENTE   = PO.SEQ_PLA_AGENTE
   AND PO.SEQ_PLA_PRODUTO  = PR.SEQ_PLA_PRODUTO
   AND PO.COD_SAFRA        = PR.COD_SAFRA
   AND PO.SEQ_PLA_AGENTE   = FAT.SEQ_PLA_AGENTE
   AND PO.SEQ_PLA_PRODUTO  = FAT.SEQ_PLA_PRODUTO
   AND PO.COD_SAFRA        = FAT.COD_SAFRA
   AND NVL(AP.ATIVO, 'N')  = 'S'
   AND NVL(AG.ATIVO, 'N')  = 'S'

 ORDER BY 1,3,2

