CREATE MATERIALIZED VIEW VW_POTENCIALIZACAO_AGENTE_FAT REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT AG.SEQ_PLA_AGENTE,
       CLA.NOME_CLIENTE AS NOME_AGENTE,
       CS.SEQ_PLA_PRODUTO,
       CS.COD_SAFRA,
       CS.DATA_CONTRATO,
       ROUND(NVL(CS.QUANTIDADE ,0),2) AS QUANTIDADE,
       ROUND(NVL(CS.VALOR_TOTAL,0),2) AS VALOR_TOTAL

  FROM AGRICOLA.ACORDO_POTENCIAL   AP,
       AGRICOLA.AGENTES            AG, --agente interno
       AGRICOLA.CONTRATO_SAIDA     CS, --FATURAMENTO
       AGRICOLA.CLIENTES           CLA,--AGENTE
       AGRICOLA.CLIENTES_ENDERECOS CEA,
       AGRICOLA.CLIENTES_ENDERECOS CE,--CLIE/FORN
       AGRICOLA.CLIENTES           CL       

 WHERE AP.SEQ_PLA_AGENTE_IN        = AG.SEQ_PLA_AGENTE
   AND AP.SEQ_PLA_ACORDO_POTENCIAL = CS.SEQ_PLA_ACORDO_POTENCIAL
   AND AG.SEQ_PLA_ENDERECO         = CEA.SEQ_PLA_ENDERECO
   AND CEA.SEQ_PLA_CLIENTE         = CLA.SEQ_PLA_CLIENTE
   --SÓ POSSO CONSIDERAR FATURAMENTO OS CONTRATOS QUE DE FATO FORAM FEITOS PELO AGENTE DAQUELE CLIENTE
   AND CS.SEQ_PLA_END_ENTREGA      = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE          = CL.SEQ_PLA_CLIENTE
   AND AG.SEQ_PLA_AGENTE           = CL.SEQ_PLA_AGENTE
   --
   AND EXISTS (SELECT SC.SEQ_PLA_CLIENTE FROM AGRICOLA.CLIENTE_POTENCIAL_SC SC WHERE SC.SEQ_PLA_CLIENTE = CL.SEQ_PLA_CLIENTE)--Só vai trazer os faturamentos dos clientes parametrizados.   
   AND NVL(AG.ATIVO, 'N')            = 'S'
   AND NVL(AP.STATUS,'A')            = 'F'
   AND NVL(AP.TIPO_CTR,'C')          = 'V'
           
