CREATE MATERIALIZED VIEW VW_POTENCIALIZACAO_CLIENTE_FAT REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT AC.SEQ_PLA_AGENTE_IN, --SÓ POSSO CONSIDERAR FATURAMENTO OS CONTRATOS QUE DE FATO FORAM FEITOS PELO AGENTE DAQUELE CLIENTE
       CE.SEQ_PLA_CLIENTE,
       CS.SEQ_PLA_PRODUTO,
       CS.COD_SAFRA,
       CS.DATA_CONTRATO,
       ROUND(NVL(CS.QUANTIDADE ,0),2) AS QUANTIDADE,
       ROUND(NVL(CS.VALOR_TOTAL,0),2) AS VALOR_TOTAL
  FROM AGRICOLA.ACORDO_POTENCIAL   AC,
       AGRICOLA.CONTRATO_SAIDA     CS,--FATURAMENTO
       AGRICOLA.CLIENTES_ENDERECOS CE --END FATURAMENTO
 WHERE AC.SEQ_PLA_ACORDO_POTENCIAL   = CS.SEQ_PLA_ACORDO_POTENCIAL
   AND CS.SEQ_PLA_END_ENTREGA        = CE.SEQ_PLA_ENDERECO
         
