CREATE MATERIALIZED VIEW VW_POTENCIALIZACAO_CLIENTE REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT DISTINCT CP.COD_SAFRA,
       CLA.NOME_CLIENTE NOME_AGENTE,
       AG.SEQ_PLA_AGENTE,
       CL.NOME_CLIENTE,
       CL.SEQ_PLA_CLIENTE,
       AV.DESCRICAO_ATIVIDADE ATIVIDADE,       
       PD.DESCRICAO_PRODUTO,
       PD.SEQ_PLA_PRODUTO,
       CP.QUANTIDADE_SC as PRODUTO_SHARE,
       ROUND((CP.QUANTIDADE_SC * 100 ) /  (SELECT SUM(CPP.QUANTIDADE_SC) FROM AGRICOLA.CLIENTE_POTENCIAL_SC CPP WHERE CPP.SEQ_PLA_PRODUTO = CP.SEQ_PLA_PRODUTO AND CPP.COD_SAFRA = CP.COD_SAFRA),2) PORCENTO, --SOMATORIA DA QTD DE TODOS OS CLIENTES POR PRODUTO
       FAT.QUANTIDADE AS FATURAMENTO

  FROM AGRICOLA.AGENTES              AG,
       AGRICOLA.CLIENTES             CLA, --AGENTE
       AGRICOLA.CLIENTES_ENDERECOS   CE,
       AGRICOLA.AGENTES_PERIODOS     AP,
       AGRICOLA.CLIENTES             CL,--CLIE/FORN
       AGRICOLA.CLIENTE_POTENCIAL_SC CP,
       AGRICOLA.PRODUTOS             PD,

       (SELECT AT.DESCRICAO_ATIVIDADE, CA.SEQ_PLA_CLIENTE 
          FROM AGRICOLA.ATIVIDADE AT, AGRICOLA.CLIENTES_ATIVIDADE CA 
         WHERE AT.SEQ_PLA_ATIVIDADE = CA.SEQ_PLA_ATIVIDADE AND ROWNUM = 1) AV,
         
       (SELECT AC.SEQ_PLA_AGENTE_IN,
               CE.SEQ_PLA_CLIENTE,
               CS.SEQ_PLA_PRODUTO,
               CS.COD_SAFRA,
               ROUND(SUM(NVL(CS.QUANTIDADE ,0)),2) AS QUANTIDADE,
               ROUND(SUM(NVL(CS.VALOR_TOTAL,0)),2) AS VALOR_TOTAL
          FROM AGRICOLA.ACORDO_POTENCIAL   AC,                 
               AGRICOLA.CONTRATO_SAIDA     CS,--FATURAMENTO
               AGRICOLA.CLIENTES_ENDERECOS CE --END FATURAMENTO
         WHERE AC.SEQ_PLA_ACORDO_POTENCIAL = CS.SEQ_PLA_ACORDO_POTENCIAL
           AND CS.SEQ_PLA_END_ENTREGA      = CE.SEQ_PLA_ENDERECO
         GROUP BY AC.SEQ_PLA_AGENTE_IN,CE.SEQ_PLA_CLIENTE, CS.SEQ_PLA_PRODUTO,CS.COD_SAFRA
         ) FAT --FATURAMENTO

 WHERE AG.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE  = CLA.SEQ_PLA_CLIENTE
   AND AG.SEQ_PLA_AGENTE   = AP.SEQ_PLA_AGENTE
   AND AG.SEQ_PLA_AGENTE   = CL.SEQ_PLA_AGENTE
   AND CL.SEQ_PLA_CLIENTE  = CP.SEQ_PLA_CLIENTE
   AND CP.SEQ_PLA_PRODUTO  = PD.SEQ_PLA_PRODUTO   
   AND CP.SEQ_PLA_CLIENTE  = FAT.SEQ_PLA_CLIENTE   
   AND CP.SEQ_PLA_PRODUTO  = FAT.SEQ_PLA_PRODUTO
   AND CP.COD_SAFRA        = FAT.COD_SAFRA
   AND AG.SEQ_PLA_AGENTE   = FAT.SEQ_PLA_AGENTE_IN --SÓ POSSO CONSIDERAR FATURAMENTO OS CONTRATOS QUE DE FATO FORAM FEITOS PELO AGENTE DAQUELE CLIENTE
   AND CL.SEQ_PLA_CLIENTE  = AV.SEQ_PLA_CLIENTE
   AND NVL(AP.ATIVO, 'N')  = 'S'
   AND NVL(AG.ATIVO, 'N')  = 'S'

 ORDER BY 1,4,7
