CREATE MATERIALIZED VIEW FLUXO_TITULOS_BI
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT
       'PAGAR' AS TIPO,
       CP.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_CLIENTE,
       TRUNC(CP.DATA_VCTO) AS DATA_VCTO,
       NULL AS DATA_BAIXA,
       CASE WHEN MO.DESC_MOEDA <> 'REAL'
            THEN CASE WHEN NVL(CP.FIXADO,'N') = 'S' THEN CP.VALOR_REAL ELSE (NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0)) * FINDICEMOEDA(MO.SEQ_PLA_MOEDA,CP.DATA_VCTO) END
            ELSE NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0)
       END AS VALOR,
       'ABERTO' AS STATUS,
       1 AS ID_MOEDA_FILTRO,
       'REAL/DOLAR' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       CASE WHEN MO.DESC_MOEDA <> 'REAL'
            THEN CASE WHEN NVL(CP.FIXADO,'N') = 'S' THEN CP.INDICE_ORIGEM ELSE FINDICEMOEDA(MO.SEQ_PLA_MOEDA, CP.DATA_VCTO) END
            ELSE 1
       END AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_PAGAR CP,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND NOT EXISTS (SELECT * FROM COMPASS_PRD.PAGAR_PAGTOS PP WHERE PP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR AND PP.LIB_PGTO = 'B')
   AND NOT EXISTS (SELECT LG.SEQ_PLA_FATURA_PAGAR FROM COMPASS_PRD.LIGA_FATURA_PAGAR LG WHERE LG.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR)
   AND CP.COD_EMPRESA = EP.COD_EMPRESA
   AND CP.COD_EMPRESA = FI.COD_EMPRESA
   AND CP.COD_FILIAL = FI.COD_FILIAL
   AND CP.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CP.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CP.CANCELADO, 'N') = 'N'
   AND NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) > 0

UNION ALL

/*MOV PAGAR ABERTO*/
SELECT
  'PAGAR' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  NULL AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'ABERTO' AS STATUS,
  1 AS ID_MOEDA_FILTRO,
  'REAL/DOLAR' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  CASE WHEN MO.DESC_MOEDA <> 'REAL' THEN FINDICEMOEDA(MO.SEQ_PLA_MOEDA, FM.DATA_DOCUM) ELSE 1 END AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL

WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.DEB_CRED = 'D'
     AND NVL(FM.CONCILIADO,'N') = 'N'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL
/* TITULOS A PAGAR BAIXADO */
SELECT
       'PAGAR' AS TIPO,
       CP.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_FANTASIA,
       TRUNC(CP.DATA_VCTO) AS DATA_VCTO,
       FRETORNA_DATA_BAIXA_PAGAR(CP.SEQ_PLA_PAGAR) AS DATA_BAIXA,
       NVL(PP.VALOR_PAGO_REAL,0) AS VALOR,
       'FECHADO' AS STATUS,
       1 AS ID_MOEDA_FILTRO,
       'REAL/DOLAR' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       CASE WHEN MO.DESC_MOEDA <> 'REAL' THEN FINDICEBAIXA_PAGAR(CP.SEQ_PLA_PAGAR) ELSE 1  END AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_PAGAR CP,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASs_PRD.PAGAR_PAGTOS PP,
       COMPASs_PRD.LIGA_PAGTOS_MOVIMENTO PM,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
   AND PP.SEQ_PLA_PAGAR_LCTOS = PM.SEQ_PLA_PAGAR_LCTOS
   AND CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND EXISTS (SELECT * FROM COMPASs_PRD.PAGAR_PAGTOS PP WHERE PP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR AND PP.LIB_PGTO = 'B')
   AND CP.COD_EMPRESA = EP.COD_EMPRESA
   AND CP.COD_EMPRESA = FI.COD_EMPRESA
   AND CP.COD_FILIAL = FI.COD_FILIAL
   AND CP.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CP.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) > 0
   AND NVL(CP.CANCELADO, 'N') <> 'S'
   AND NVL(CP.FINALIZADO, 'N') = 'S'

 UNION ALL

 /*MOV PAGAR FECHADO*/
SELECT
  'PAGAR' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  TRUNC(FM.DATA_CONCILIADO) AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'FECHADO' AS STATUS,
  1 AS ID_MOEDA_FILTRO,
  'REAL/DOLAR' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  CASE WHEN MO.DESC_MOEDA <> 'REAL' THEN FINDICEMOEDA(MO.SEQ_PLA_MOEDA, FM.DATA_DOCUM) ELSE 1 END AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND FM.DEB_CRED = 'D'
     AND NVL(FM.CONCILIADO,'N') = 'S'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL
/* TITULOS A RECEBER ABERTO */
SELECT
      'RECEBER' AS TIPO,
      CR.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_FANTASIA,
       TRUNC(CR.DATA_VCTO) AS DATA_VCTO,
       NULL AS DATA_BAIXA,
       CASE WHEN MO.DESC_MOEDA <> 'REAL'
            THEN CASE WHEN NVL(CR.FIXADO,'N') = 'S' THEN CR.VALOR_REAL ELSE (NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0)) * FINDICEMOEDA(MO.SEQ_PLA_MOEDA, CR.DATA_VCTO) END
            ELSE NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0)
       END AS VALOR,
       'ABERTO' AS STATUS,
       1 AS ID_MOEDA_FILTRO,
       'REAL/DOLAR' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       CASE WHEN MO.DESC_MOEDA <> 'REAL'
            THEN CASE WHEN NVL(CR.FIXADO,'N') = 'S' THEN CR.INDICE_ORIGEM ELSE FINDICEMOEDA(MO.SEQ_PLA_MOEDA, CR.DATA_VCTO) END
       ELSE 1 END AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_RECEBER CR,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND NOT EXISTS (SELECT * FROM COMPASS_PRD.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND NOT EXISTS (SELECT LR.SEQ_PLA_RECEBER  FROM COMPASS_PRD.Liga_Fatura_Receber LR WHERE LR.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND CR.COD_EMPRESA = EP.COD_EMPRESA
   AND CR.COD_EMPRESA = FI.COD_EMPRESA
   AND CR.COD_FILIAL = FI.COD_FILIAL
   AND CR.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CR.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) > 0
   AND NVL(CR.CANCELADO, 'N') <> 'S'

UNION ALL

/*MOV RECEBER ABERTO*/
SELECT
  'RECEBER' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  NULL AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'ABERTO' AS STATUS,
  1 AS ID_MOEDA_FILTRO,
  'REAL/DOLAR' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  CASE WHEN MO.DESC_MOEDA <> 'REAL' THEN FINDICEMOEDA(MO.SEQ_PLA_MOEDA, FM.DATA_DOCUM) ELSE 1 END AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND FM.DEB_CRED = 'C'
     AND NVL(FM.CONCILIADO,'N') = 'N'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL
/* TITULOS A RECEBER BAIXADO */
SELECT
      'RECEBER' AS TIPO,
       CR.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_FANTASIA,
       TRUNC(CR.DATA_VCTO) AS DATA_VCTO,
       FRETORNA_DATA_BAIXA_RECEBER(CR.SEQ_PLA_RECEBER) AS DATA_BAIXA,
       NVL(RP.VALOR_RECEBIDO_REAL,0) AS VALOR,
       'FECHADO' AS STATUS,
       1 AS ID_MOEDA_FILTRO,
       'REAL/DOLAR' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       CASE WHEN MO.DESC_MOEDA <> 'REAL' THEN FINDICEBAIXA_RECEBER(CR.SEQ_PLA_RECEBER) ELSE 1 END  AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_RECEBER CR,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASs_PRD.RECEBER_PAGTOS RP,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
   AND CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND EXISTS (SELECT * FROM COMPASs_PRD.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND NOT EXISTS (SELECT LG.SEQ_PLA_FATURA_RECEBER FROM COMPASs_PRD.LIGA_FATURA_RECEBER LG WHERE LG.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND CR.COD_EMPRESA = EP.COD_EMPRESA
   AND CR.COD_EMPRESA = FI.COD_EMPRESA
   AND CR.COD_FILIAL = FI.COD_FILIAL
   AND CR.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CR.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) > 0
   AND NVL(CR.CANCELADO, 'N') = 'N'
   AND NVL(CR.FINALIZADO, 'N') = 'S'

UNION ALL

/*MOV RECEBER FECHADO*/
SELECT
  'RECEBER' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  TRUNC(FM.DATA_CONCILIADO) AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'FECHADO' AS STATUS,
  1 AS ID_MOEDA_FILTRO,
  'REAL/DOLAR' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  CASE WHEN MO.DESC_MOEDA <> 'REAL' THEN findicebaixa_receber(FM.DATA_CONCILIADO) ELSE 1 END AS VALOR_INDICE,
   NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND FM.DEB_CRED = 'C'
     AND NVL(FM.CONCILIADO,'N') = 'S'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)
UNION ALL

/* APENAS REAL */
/* TITULOS PAGAR EM ABERTO */
SELECT
       'PAGAR' AS TIPO,
       CP.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_CLIENTE,
       TRUNC(CP.DATA_VCTO) AS DATA_VCTO,
       NULL AS DATA_BAIXA,
       NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0)  AS VALOR,
       'ABERTO' AS STATUS,
       3 AS ID_MOEDA_FILTRO,
       'REAL' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       1 AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_PAGAR CP,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND NOT EXISTS (SELECT * FROM COMPASS_PRD.PAGAR_PAGTOS PP WHERE PP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR AND PP.LIB_PGTO = 'B')
   AND NOT EXISTS (SELECT LG.SEQ_PLA_FATURA_PAGAR FROM COMPASS_PRD.LIGA_FATURA_PAGAR LG WHERE LG.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR)
   AND CP.COD_EMPRESA = EP.COD_EMPRESA
   AND CP.COD_EMPRESA = FI.COD_EMPRESA
   AND CP.COD_FILIAL = FI.COD_FILIAL
   AND CP.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CP.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND MO.SEQ_PLA_MOEDA = '   1212601'
   AND NVL(CP.CANCELADO, 'N') = 'N'
   AND NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) > 0

UNION ALL

/*MOV PAGAR ABERTO*/
SELECT
  'PAGAR' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  NULL AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'ABERTO' AS STATUS,
  3 AS ID_MOEDA_FILTRO,
  'REAL' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  1 AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL

WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND MO.SEQ_PLA_MOEDA = '   1212601'
     AND FM.DEB_CRED = 'D'
     AND NVL(FM.CONCILIADO,'N') = 'N'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL
/* TITULOS A PAGAR BAIXADO */
SELECT
       'PAGAR' AS TIPO,
       CP.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_FANTASIA,
       TRUNC(CP.DATA_VCTO) AS DATA_VCTO,
       FRETORNA_DATA_BAIXA_PAGAR(CP.SEQ_PLA_PAGAR) AS DATA_BAIXA,
       NVL(PP.VALOR_PAGO_REAL,0) AS VALOR,
       'FECHADO' AS STATUS,
       3 AS ID_MOEDA_FILTRO,
       'REAL' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       1  AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_PAGAR CP,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASs_PRD.PAGAR_PAGTOS PP,
       COMPASs_PRD.LIGA_PAGTOS_MOVIMENTO PM,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
   AND PP.SEQ_PLA_PAGAR_LCTOS = PM.SEQ_PLA_PAGAR_LCTOS
   AND CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND EXISTS (SELECT * FROM COMPASs_PRD.PAGAR_PAGTOS PP WHERE PP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR AND PP.LIB_PGTO = 'B')
   AND CP.COD_EMPRESA = EP.COD_EMPRESA
   AND CP.COD_EMPRESA = FI.COD_EMPRESA
   AND CP.COD_FILIAL = FI.COD_FILIAL
   AND CP.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CP.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) > 0
   AND MO.SEQ_PLA_MOEDA = '   1212601'
   AND NVL(CP.CANCELADO, 'N') <> 'S'
   AND NVL(CP.FINALIZADO, 'N') = 'S'

 UNION ALL

 /*MOV PAGAR FECHADO*/
SELECT
  'PAGAR' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  TRUNC(FM.DATA_CONCILIADO) AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'FECHADO' AS STATUS,
  3 AS ID_MOEDA_FILTRO,
  'REAL' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  1 AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND MO.SEQ_PLA_MOEDA = '   1212601'
     AND FM.DEB_CRED = 'D'
     AND NVL(FM.CONCILIADO,'N') = 'S'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL
/* TITULOS A RECEBER ABERTO */
SELECT
      'RECEBER' AS TIPO,
      CR.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_FANTASIA,
       TRUNC(CR.DATA_VCTO) AS DATA_VCTO,
       NULL AS DATA_BAIXA,
       NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) AS VALOR,
       'ABERTO' AS STATUS,
       3 AS ID_MOEDA_FILTRO,
       'REAL' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       1 AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_RECEBER CR,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND NOT EXISTS (SELECT * FROM COMPASS_PRD.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND NOT EXISTS (SELECT LR.SEQ_PLA_RECEBER  FROM COMPASS_PRD.Liga_Fatura_Receber LR WHERE LR.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND CR.COD_EMPRESA = EP.COD_EMPRESA
   AND CR.COD_EMPRESA = FI.COD_EMPRESA
   AND CR.COD_FILIAL = FI.COD_FILIAL
   AND CR.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CR.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) > 0
   AND MO.SEQ_PLA_MOEDA = '   1212601'
   AND NVL(CR.CANCELADO, 'N') <> 'S'

UNION ALL

/*MOV RECEBER ABERTO*/
SELECT
  'RECEBER' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  NULL AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'ABERTO' AS STATUS,
  3 AS ID_MOEDA_FILTRO,
  'REAL' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  1 AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND MO.SEQ_PLA_MOEDA = '   1212601'
     AND FM.DEB_CRED = 'C'
     AND NVL(FM.CONCILIADO,'N') = 'N'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL
/* TITULOS A RECEBER BAIXADO */
SELECT
      'RECEBER' AS TIPO,
       CR.DOCUMENTO,
       EP.COD_EMPRESA,
       EP.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.SIGLA_FILIAL,
       FI.SEQ_PLA_ENDERECO,
       CLI.NOME_FANTASIA,
       TRUNC(CR.DATA_VCTO) AS DATA_VCTO,
       FRETORNA_DATA_BAIXA_RECEBER(CR.SEQ_PLA_RECEBER) AS DATA_BAIXA,
       NVL(RP.VALOR_RECEBIDO_REAL,0) AS VALOR,
       'FECHADO' AS STATUS,
       3 AS ID_MOEDA_FILTRO,
       'REAL' AS MOEDA_FILTRO,
       MO.SIGLA_MOEDA,
       MO.DESC_MOEDA,
       1 AS VALOR_INDICE,
       NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
  FROM COMPASs_PRD.CONTAS_RECEBER CR,
       COMPASs_PRD.EMPRESAS EP,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.MOEDAS MO,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       COMPASs_PRD.RECEBER_PAGTOS RP,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
   CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
   AND CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
   AND EXISTS (SELECT * FROM COMPASs_PRD.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND NOT EXISTS (SELECT LG.SEQ_PLA_FATURA_RECEBER FROM COMPASs_PRD.LIGA_FATURA_RECEBER LG WHERE LG.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
   AND CR.COD_EMPRESA = EP.COD_EMPRESA
   AND CR.COD_EMPRESA = FI.COD_EMPRESA
   AND CR.COD_FILIAL = FI.COD_FILIAL
   AND CR.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND CR.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
   AND NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) > 0
   AND MO.SEQ_PLA_MOEDA = '   1212601'
   AND NVL(CR.CANCELADO, 'N') = 'N'
   AND NVL(CR.FINALIZADO, 'N') = 'S'

UNION ALL

/*MOV RECEBER FECHADO*/
SELECT
  'RECEBER' AS TIPO,
  FM.NR_DOCUMENTO,
  EP.COD_EMPRESA,
  EP.SIGLA_EMPRESA,
  FI.COD_FILIAL,
  FI.SIGLA_FILIAL,
  FI.SEQ_PLA_ENDERECO,
  CLI.NOME_CLIENTE,
  TRUNC(FM.DATA_DOCUM) AS DATA_VCTO,
  TRUNC(FM.DATA_CONCILIADO) AS DATA_BAIXA,
  FM.VALOR_TOTAL AS VALOR,
  'FECHADO' AS STATUS,
  3 AS ID_MOEDA_FILTRO,
  'REAL' AS MOEDA_FILTRO,
  MO.SIGLA_MOEDA,
  MO.DESC_MOEDA,
  1 AS VALOR_INDICE,
  NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASS_PRD.FIN_MOVIMENTO FM,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
     FM.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
     AND FM.COD_EMPRESA = EP.COD_EMPRESA
     AND FM.COD_EMPRESA = FI.COD_EMPRESA
     AND FM.COD_FILIAL = FI.COD_FILIAL
     AND FM.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
     AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
     AND FM.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
     AND MO.SEQ_PLA_MOEDA = '   1212601'
     AND FM.DEB_CRED = 'C'
     AND NVL(FM.CONCILIADO,'N') = 'S'
     AND NVL(FM.CANCELADO,'N') = 'N'
     AND NOT EXISTS (SELECT RP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_RECEBER CR,
                          COMPASS_PRD.RECEBER_PAGTOS RP
                    WHERE CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
                      AND RP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN
                    UNION ALL
                   SELECT LP.SEQ_PLA_MOV_FIN
                     FROM COMPASS_PRD.CONTAS_PAGAR          CP,
                          COMPASS_PRD.PAGAR_PAGTOS          PP,
                          COMPASS_PRD.LIGA_PAGTOS_MOVIMENTO LP
                    WHERE CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
                      AND PP.SEQ_PLA_PAGAR_LCTOS = LP.SEQ_PLA_PAGAR_LCTOS
                      AND LP.SEQ_PLA_MOV_FIN = FM.SEQ_PLA_MOV_FIN)

UNION ALL

/* APENAS DOLAR */
SELECT
   'PAGAR' AS TIPO,
   CP.DOCUMENTO,
   EP.COD_EMPRESA,
   EP.SIGLA_EMPRESA,
   FI.COD_FILIAL,
   FI.SIGLA_FILIAL,
   FI.SEQ_PLA_ENDERECO,
   CLI.NOME_FANTASIA,
   TRUNC(CP.DATA_VCTO) AS DATA_VCTO,
   NULL AS DATA_BAIXA,
   NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) AS VALOR,
   'ABERTO' AS STATUS,
   2 AS ID_MOEDA_FILTRO,
   'DOLAR' AS MOEDA_FILTRO,
   MO.SIGLA_MOEDA AS SIGLA_MOEDA,
   MO.DESC_MOEDA AS DESC_MOEDA,
   CASE WHEN NVL(CP.FIXADO,'N') = 'S' THEN CP.INDICE_ORIGEM ELSE FINDICEMOEDA(MO.SEQ_PLA_MOEDA, CP.DATA_VCTO) END AS VALOR_INDICE,
   NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASs_PRD.CONTAS_PAGAR CP,
     COMPASs_PRD.PAR_GERAL PG,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
 CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
 AND CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
 AND MO.SEQ_PLA_MOEDA = PG.MOEDA_DOLAR
 AND NOT EXISTS (SELECT * FROM COMPASs_PRD.PAGAR_PAGTOS PP WHERE PP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR AND PP.LIB_PGTO = 'B')
 AND NOT EXISTS (SELECT LG.SEQ_PLA_FATURA_PAGAR FROM COMPASS_PRD.LIGA_FATURA_PAGAR LG WHERE LG.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR)
 AND CP.COD_EMPRESA = EP.COD_EMPRESA
 AND CP.COD_EMPRESA = FI.COD_EMPRESA
 AND CP.COD_FILIAL = FI.COD_FILIAL
 AND CP.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
 AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
 AND CP.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
 AND NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) > 0
 AND NVL(CP.CANCELADO, 'N') = 'N'
 AND NVL(CP.FINALIZADO, 'N') = 'S'

UNION ALL

SELECT
     'PAGAR' AS TIPO,
     CP.DOCUMENTO,
     EP.COD_EMPRESA,
     EP.SIGLA_EMPRESA,
     FI.COD_FILIAL,
     FI.SIGLA_FILIAL,
     FI.SEQ_PLA_ENDERECO,
     CLI.NOME_FANTASIA,
     TRUNC(CP.DATA_VCTO) AS DATA_VCTO,
     FRETORNA_DATA_BAIXA_PAGAR(CP.SEQ_PLA_PAGAR) AS DATA_BAIXA,
     NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) AS VALOR,
     'FECHADO' AS STATUS,
     2 AS ID_MOEDA_FILTRO,
     'DOLAR' AS MOEDA_FILTRO,
     MO.SIGLA_MOEDA AS SIGLA_MOEDA,
     MO.DESC_MOEDA AS DESC_MOEDA,
     findicebaixa_pagar(CP.SEQ_PLA_PAGAR)  AS VALOR_INDICE,
     NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASs_PRD.CONTAS_PAGAR CP,
     COMPASs_PRD.PAR_GERAL PG,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASs_PRD.PAGAR_PAGTOS PP,
     COMPASs_PRD.LIGA_PAGTOS_MOVIMENTO PM,
     COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
  CP.SEQ_PLA_PAGAR = PP.SEQ_PLA_PAGAR
  AND PP.SEQ_PLA_PAGAR_LCTOS = PM.SEQ_PLA_PAGAR_LCTOS
  AND CP.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
  AND MO.SEQ_PLA_MOEDA = PG.MOEDA_DOLAR
  AND EXISTS (SELECT * FROM COMPASs_PRD.PAGAR_PAGTOS PP WHERE PP.SEQ_PLA_PAGAR = CP.SEQ_PLA_PAGAR AND PP.LIB_PGTO = 'B')
  AND CP.COD_EMPRESA = EP.COD_EMPRESA
  AND CP.COD_EMPRESA = FI.COD_EMPRESA
  AND CP.COD_FILIAL = FI.COD_FILIAL
  AND CP.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
  AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
  AND CP.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
  AND NVL(CP.VALOR_DOCUM,0)+NVL(CP.VALOR_JUROS,0)-NVL(CP.VALOR_DESCONTO,0) > 0
  AND NVL(CP.CANCELADO, 'N') = 'N'

UNION ALL

SELECT
     'RECEBER' AS TIPO,
     CR.DOCUMENTO,
     EP.COD_EMPRESA,
     EP.SIGLA_EMPRESA,
     FI.COD_FILIAL,
     FI.SIGLA_FILIAL,
     FI.SEQ_PLA_ENDERECO,
     CLI.NOME_FANTASIA,
     TRUNC(CR.DATA_VCTO) AS DATA_VCTO,
     NULL AS DATA_BAIXA,
     NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) AS VALOR,
     'ABERTO' AS STATUS,
     2 AS ID_MOEDA_FILTRO,
     'DOLAR' AS MOEDA_FILTRO,
     MO.SIGLA_MOEDA AS SIGLA_MOEDA,
     MO.DESC_MOEDA AS DESC_MOEDA,
     CASE WHEN NVL(CR.FIXADO,'N') = 'S' THEN CR.INDICE_ORIGEM ELSE FINDICEMOEDA(MO.SEQ_PLA_MOEDA, CR.DATA_VCTO) END AS VALOR_INDICE,
     NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASs_PRD.CONTAS_RECEBER CR,
     COMPASs_PRD.PAR_GERAL PG,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASS_PRD.TIPOS_LANCTOS TL
WHERE
 CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
 AND CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
 AND MO.SEQ_PLA_MOEDA = PG.MOEDA_DOLAR
 AND NOT EXISTS (SELECT * FROM COMPASs_PRD.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
 AND NOT EXISTS (SELECT LR.SEQ_PLA_RECEBER  FROM COMPASS_PRD.Liga_Fatura_Receber LR WHERE LR.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
 AND CR.COD_EMPRESA = EP.COD_EMPRESA
 AND CR.COD_EMPRESA = FI.COD_EMPRESA
 AND CR.COD_FILIAL = FI.COD_FILIAL
 AND CR.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
 AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
 AND CR.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
 AND NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) > 0
 AND NVL(CR.CANCELADO, 'N') = 'N'

UNION ALL

SELECT
      'RECEBER' AS TIPO,
     cr.documento,
     EP.COD_EMPRESA,
     EP.SIGLA_EMPRESA,
     FI.COD_FILIAL,
     FI.SIGLA_FILIAL,
     FI.SEQ_PLA_ENDERECO,
     CLI.NOME_FANTASIA,
     TRUNC(CR.DATA_VCTO) AS DATA_VCTO,
     FRETORNA_DATA_BAIXA_RECEBER(CR.SEQ_PLA_RECEBER) AS DATA_BAIXA,
     NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) AS VALOR,
     'FECHADO' AS STATUS,
     2 AS ID_MOEDA_FILTRO,
     'DOLAR' AS MOEDA_FILTRO,
     MO.SIGLA_MOEDA AS SIGLA_MOEDA,
     MO.DESC_MOEDA AS DESC_MOEDA,
     findicebaixa_receber(CR.SEQ_PLA_RECEBER) AS VALOR_INDICE,
     NVL(TL.ADIANTAMENTO,'N') AS ADIANTAMENTO
FROM COMPASs_PRD.CONTAS_RECEBER CR,
     COMPASs_PRD.PAR_GERAL PG,
     COMPASs_PRD.EMPRESAS EP,
     COMPASs_PRD.FILIAIS FI,
     COMPASs_PRD.MOEDAS MO,
     COMPASs_PRD.CLIENTES CLI,
     COMPASs_PRD.CLIENTES_ENDERECOS CE,
     COMPASs_PRD.RECEBER_PAGTOS RP,
       COMPASS_PRD.TIPOS_LANCTOS TL
 WHERE
 CR.SEQ_PLA_RECEBER = RP.SEQ_PLA_RECEBER
 AND CR.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
 AND MO.SEQ_PLA_MOEDA = PG.MOEDA_DOLAR
 AND EXISTS (SELECT * FROM COMPASs_PRD.RECEBER_PAGTOS RP WHERE RP.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
 AND NOT EXISTS (SELECT LG.SEQ_PLA_FATURA_RECEBER FROM COMPASs_PRD.LIGA_FATURA_RECEBER LG WHERE LG.SEQ_PLA_RECEBER = CR.SEQ_PLA_RECEBER)
 AND CR.COD_EMPRESA = EP.COD_EMPRESA
 AND CR.COD_EMPRESA = FI.COD_EMPRESA
 AND CR.COD_FILIAL = FI.COD_FILIAL
 AND CR.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
 AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
 AND CR.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
 AND NVL(CR.VALOR_DOCUM,0)+NVL(CR.VALOR_JUROS,0)-NVL(CR.VALOR_DESCONTO,0) > 0
 AND NVL(CR.CANCELADO, 'N') = 'N'
/* FIM DOLAR */