CREATE MATERIALIZED VIEW FLUXO_PREVISAO_BI
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT PX.TIPO,
       PX.COD_EMPRESA,
       PX.COD_FILIAL,
       PX.FORM_LANCAMENTO,
       PX.SEQ_PLA_PREVISAO,
       TO_CHAR(PX.NR_DOCUMENTO) AS NR_DOCUMENTO,
       PX.DATA_VCTO AS DATA,
       PX.DATA_LCTO,
       CE.NOME_CLIENTE,
       CE.SEQ_PLA_CLIENTE,
       PX.SEQ_PLA_ENDERECO,
       PX.OBSERVACOES,
       PX.SEQ_PLA_MOEDA,
       PX.SIGLA_MOEDA,
       PX.VALOR_INDICE,
       PX.STATUS,
       PX.VLR_ORIGINAL,
       PX.VLR_BAIXA_ORIGINAL,
       PX.VLR_DOCUM,
       PX.VLR_REAL,
       PX.VLR_SO_REAIS,
       PX.VLR_EM_REAIS,
       PX.VLR_EM_REAIS1,
       PX.VLR_SO_DOLAR,
       PX.VLR_EM_DOLAR,
       PX.VLR_FINAL,
       PX.BAIXADO,
       PX.ID_MOEDA_FILTRO,
       PX.MOEDA_FILTRO,
       '999' AS SEQ_PLA_AGRUPADOR
 FROM (
        SELECT
              CASE WHEN PF.OPERACAO = 'D' THEN 'PAGAR' ELSE 'RECEBER' END AS TIPO,
              PC.COD_EMPRESA,
              PC.COD_FILIAL,
              PF.COD_CONTA,
              PF.COD_TABELA,
              PF.FORM_LANCAMENTO,
              PF.SEQ_PLA_PREVISAO,
              TO_CHAR(NVL(PC.NR_PEDIDO,PC.NR_CONTROLE)) AS NR_DOCUMENTO,
              PF.DATA_VCTO AS DATA_VCTO,
              PC.DATA_PEDIDO AS DATA_LCTO,
              PF.SEQ_PLA_ENDERECO,
              PF.OBSERVACOES,
              PF.SEQ_PLA_MOEDA,
              MO.SIGLA_MOEDA,
              COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) AS VALOR_INDICE,
              'PREVISAO_PEDIDO_COMPRAS' AS STATUS,
              PF.Valor_Previsto AS VLR_ORIGINAL,
              nvl(BX.VALOR,0) AS VLR_BAIXA_ORIGINAL,
              PF.Valor_Previsto AS VLR_DOCUM,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 2
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 1 ELSE 0 END AS ID_MOEDA_FILTRO,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 'DOLAR'
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 'REAL' ELSE '' END AS MOEDA_FILTRO,
              0 AS VLR_REAL,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
              ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END VLR_EM_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_REAIS1,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_DOLAR,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_DOLAR,
              (CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
               ELSE (PF.VALOR_PREVISTO-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END)*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) VLR_FINAL,
              'N' AS BAIXADO
         FROM COMPASs_PRD.PREVISOES_FINANCEIRAS PF,
              COMPASs_PRD.PEDIDO_COMPRAS PC,
              COMPASs_PRD.PAR_GERAL PG,
              COMPASs_PRD.Moedas MO,
              (SELECT SUM(LP.VALOR*DECODE(LP.TIPO_OPERACAO,'D',-1,DECODE(LP.TIPO_OPERACAO,'R',-1,1))) AS VALOR,
                       LPP.SEQ_PLA_PREVISAO
                 FROM COMPASs_PRD.LIGA_PRODUTO_PROVISAO LP,
                      COMPASs_PRD.LIGA_PREVISAO_PRODUTO LPP
                WHERE LP.SEQ_PLA_PREV_PROD = LPP.SEQ_PLA_LIGA
                  AND NVL(LP.COMPENSADO,'N') = 'N'
                GROUP BY LPP.SEQ_PLA_PREVISAO) BX
        WHERE PC.SEQ_PLA_PEDIDO = PF.SEQ_PLA_PEDIDO_COMPRA
          AND PF.SEQ_PLA_PREVISAO = BX.SEQ_PLA_PREVISAO(+)
          AND PF.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA(+)
          AND NVL(PF.FINALIZADO,'N') <> 'S'

        UNION ALL

       SELECT CASE WHEN PF.OPERACAO = 'D' THEN 'PAGAR' ELSE 'RECEBER' END AS TIPO,
              PV.COD_EMPRESA,
              PV.COD_FILIAL,
              PF.COD_CONTA,
              PF.COD_TABELA,
              PF.FORM_LANCAMENTO,
              PF.SEQ_PLA_PREVISAO,
              TO_CHAR(NVL(PV.NR_PEDIDO,PV.NR_CONTROLE)) AS NR_DOCUMENTO,
              PF.DATA_VCTO AS DATA_VCTO,
              PV.DATA_PEDIDO AS DATA_LCTO,
              PF.SEQ_PLA_ENDERECO,
              PF.OBSERVACOES,
              PF.SEQ_PLA_MOEDA,
              MO.SIGLA_MOEDA,
              COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) AS VALOR_INDICE,
              'PREVISAO_PEDIDO_VENDA' AS STATUS,
              PF.Valor_Previsto AS VLR_ORIGINAL,
              nvl(BX.VALOR,0) AS VLR_BAIXA_ORIGINAL,
              PF.Valor_Previsto AS VLR_DOCUM,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 2
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 1 ELSE 0 END AS ID_MOEDA_FILTRO,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 'DOLAR'
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 'REAL' ELSE '' END AS MOEDA_FILTRO,
              0 AS VLR_REAL,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
              ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END VLR_EM_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_REAIS1,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_DOLAR,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_DOLAR,
              (CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
               ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END)*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) VLR_FINAL,
              'N' AS BAIXADO
         FROM COMPASs_PRD.PREVISOES_FINANCEIRAS PF,
              COMPASs_PRD.PEDIDO_VENDAS PV,
              COMPASs_PRD.PAR_GERAL PG,
              COMPASs_PRD.Moedas MO,
              (SELECT SUM(LP.VALOR*DECODE(LP.TIPO_OPERACAO,'D',-1,DECODE(LP.TIPO_OPERACAO,'R',-1,1))) AS VALOR,
                      LPP.SEQ_PLA_PREVISAO
                 FROM COMPASs_PRD.LIGA_PRODUTO_PROVISAO LP,
                      COMPASs_PRD.LIGA_PREVISAO_PRODUTO LPP
                WHERE LP.SEQ_PLA_PREV_PROD = LPP.SEQ_PLA_LIGA
                  AND NVL(LP.COMPENSADO,'N') = 'N'
                GROUP BY LPP.SEQ_PLA_PREVISAO) BX
        WHERE PV.SEQ_PLA_PEDIDO = PF.SEQ_PLA_PEDIDO_VENDA
          AND PF.SEQ_PLA_PREVISAO = BX.SEQ_PLA_PREVISAO(+)
          AND PF.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA(+)
          AND NVL(PF.FINALIZADO,'N') <> 'S'

        UNION ALL

       SELECT CASE WHEN PF.OPERACAO = 'D' THEN 'PAGAR' ELSE 'RECEBER' END AS TIPO,
              CP.COD_EMPRESA,
              CP.COD_FILIAL,
              PF.COD_CONTA,
              PF.COD_TABELA,
              PF.FORM_LANCAMENTO,
              PF.SEQ_PLA_PREVISAO,
              TO_CHAR(NVL(CP.NR_CONTRATO_EMPRESA,CP.NR_CONTRATO)) AS NR_DOCUMENTO,
              PF.DATA_VCTO AS DATA_VCTO,
              CP.DATA_CONTRATO AS DATA_LCTO,
              PF.SEQ_PLA_ENDERECO,
              PF.OBSERVACOES,
              PF.SEQ_PLA_MOEDA,
              MO.SIGLA_MOEDA,
              COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) AS VALOR_INDICE,
              'PREVISAO_CONTRATO' AS SIGLA_TIPO_DOCUM,
              PF.Valor_Previsto AS VLR_ORIGINAL,
              nvl(BX.VALOR,0) AS VLR_BAIXA_ORIGINAL,
              PF.Valor_Previsto AS VLR_DOCUM,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 2
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 1 ELSE 0 END AS ID_MOEDA_FILTRO,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 'DOLAR'
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 'REAL' ELSE '' END AS MOEDA_FILTRO,
              0 AS VLR_REAL,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
              ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END VLR_EM_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_REAIS1,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_DOLAR,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_DOLAR,

              (CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
               ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END)*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) VLR_FINAL,
              'N' AS BAIXADO
         FROM COMPASs_PRD.PREVISOES_FINANCEIRAS PF,
              COMPASs_PRD.CONT_PRINCIPAL CP,
              COMPASs_PRD.PAR_GERAL PG,
              COMPASs_PRD.Moedas MO,
              (SELECT SUM(LP.VALOR*DECODE(LP.TIPO_OPERACAO,'D',-1,DECODE(LP.TIPO_OPERACAO,'R',-1,1))) AS VALOR,
                      LPP.SEQ_PLA_PREVISAO
                 FROM COMPASs_PRD.LIGA_PRODUTO_PROVISAO LP,
                      COMPASs_PRD.LIGA_PREVISAO_PRODUTO LPP
                WHERE LP.SEQ_PLA_PREV_PROD = LPP.SEQ_PLA_LIGA
                  AND NVL(LP.COMPENSADO,'N') = 'N'
                GROUP BY LPP.SEQ_PLA_PREVISAO) BX
        WHERE CP.SEQ_PLA_CONTRATO = PF.SEQ_PLA_CONTRATO
          AND PF.SEQ_PLA_PREVISAO = BX.SEQ_PLA_PREVISAO(+)
          AND PF.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA(+)
          AND NVL(PF.FINALIZADO,'N') <> 'S'

        UNION ALL

       SELECT CASE WHEN PF.OPERACAO = 'D' THEN 'PAGAR' ELSE 'RECEBER' END AS TIPO,
              IE.COD_EMPRESA,
              IE.COD_FILIAL,
              PF.COD_CONTA,
              PF.COD_TABELA,
              PF.FORM_LANCAMENTO,
              PF.SEQ_PLA_PREVISAO,
              TO_CHAR(IE.NR_INSTRUCAO) AS NR_DOCUMENTO,
              PF.DATA_VCTO AS DATA_VCTO,
              IE.DATA_INSTRUCAO AS DATA_LCTO,
              PF.SEQ_PLA_ENDERECO,
              PF.OBSERVACOES,
              PF.SEQ_PLA_MOEDA,
              MO.SIGLA_MOEDA,
              COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) AS VALOR_INDICE,
              'PREVISAO_EMBARQUE' AS SIGLA_TIPO_DOCUM,
              PF.Valor_Previsto AS VLR_ORIGINAL,
              nvl(BX.VALOR,0) AS VLR_BAIXA_ORIGINAL,
              PF.Valor_Previsto AS VLR_DOCUM,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 2
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 1 ELSE 0 END AS ID_MOEDA_FILTRO,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 'DOLAR'
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 'REAL' ELSE '' END AS MOEDA_FILTRO,
              0 AS VLR_REAL,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
              ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END VLR_EM_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_REAIS1,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_DOLAR,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_DOLAR,

              (CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
               ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END)*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) VLR_FINAL,
              'N' AS BAIXADO
         FROM COMPASs_PRD.PREVISOES_FINANCEIRAS PF,
              COMPASs_PRD.INSTRUCAO_EMBARQUE IE,
              COMPASs_PRD.PAR_GERAL PG,
              COMPASs_PRD.Moedas MO,
              (SELECT SUM(LP.VALOR*DECODE(LP.TIPO_OPERACAO,'D',-1,DECODE(LP.TIPO_OPERACAO,'R',-1,1))) AS VALOR,
                      LPP.SEQ_PLA_PREVISAO
                 FROM COMPASs_PRD.LIGA_PRODUTO_PROVISAO LP,
                      COMPASs_PRD.LIGA_PREVISAO_PRODUTO LPP
                WHERE LP.SEQ_PLA_PREV_PROD = LPP.SEQ_PLA_LIGA
                  AND NVL(LP.COMPENSADO,'N') = 'N'
                GROUP BY LPP.SEQ_PLA_PREVISAO) BX
        WHERE IE.SEQ_PLA_INSTRUCAO = PF.SEQ_PLA_INSTRUCAO
          AND PF.SEQ_PLA_PREVISAO = BX.SEQ_PLA_PREVISAO(+)
          AND PF.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA(+)
          AND NVL(PF.FINALIZADO,'N') <> 'S'

        UNION ALL

       SELECT CASE WHEN PF.OPERACAO = 'D' THEN 'PAGAR' ELSE 'RECEBER' END AS TIPO,
              NG.COD_EMPRESA,
              NG.COD_FILIAL,
              PF.COD_CONTA,
              PF.COD_TABELA,
              PF.FORM_LANCAMENTO,
              PF.SEQ_PLA_PREVISAO,
              TO_CHAR(NG.NR_CONTRATO) AS NR_DOCUMENTO,
              PF.DATA_VCTO AS DATA_VCTO,
              NG.DATA_NEGOCIACAO AS DATA_LCTO,
              PF.SEQ_PLA_ENDERECO,
              PF.OBSERVACOES,
              PF.SEQ_PLA_MOEDA,
              MO.SIGLA_MOEDA,
              COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) AS VALOR_INDICE,
              'PREVISAO_NEG_GRAOS' AS STATUS,
              PF.Valor_Previsto AS VLR_ORIGINAL,
              nvl(BX.VALOR,0) AS VLR_BAIXA_ORIGINAL,
              PF.Valor_Previsto AS VLR_DOCUM,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 2
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 1 ELSE 0 END AS ID_MOEDA_FILTRO,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 'DOLAR'
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 'REAL' ELSE '' END AS MOEDA_FILTRO,
              0 AS VLR_REAL,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
              ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END VLR_EM_REAIS,
              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_REAIS1,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_DOLAR,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_DOLAR,

              (CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
               ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END)*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) VLR_FINAL,
              'N' AS BAIXADO
         FROM COMPASs_PRD.PREVISOES_FINANCEIRAS PF,
              COMPASs_PRD.NEGOCIACAO_GRAOS NG,
              COMPASs_PRD.PAR_GERAL PG,
              COMPASs_PRD.Moedas MO,
              (SELECT SUM(LP.VALOR*DECODE(LP.TIPO_OPERACAO,'D',-1,DECODE(LP.TIPO_OPERACAO,'R',-1,1))) AS VALOR,
                      LPP.SEQ_PLA_PREVISAO
                 FROM COMPASs_PRD.LIGA_PRODUTO_PROVISAO LP,
                      COMPASs_PRD.LIGA_PREVISAO_PRODUTO LPP
                WHERE COMPASs_PRD.LP.SEQ_PLA_PREV_PROD = LPP.SEQ_PLA_LIGA
                  AND NVL(LP.COMPENSADO,'N') = 'N'
                GROUP BY LPP.SEQ_PLA_PREVISAO) BX
        WHERE NG.SEQ_PLA_NEGOCIACAO = PF.SEQ_PLA_NEGOCIACAO_GRA
          AND PF.SEQ_PLA_PREVISAO = BX.SEQ_PLA_PREVISAO(+)
          AND PF.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA(+)
          AND NVL(PF.FINALIZADO,'N') <> 'S'

        UNION ALL

       SELECT CASE WHEN PF.OPERACAO = 'D' THEN 'PAGAR' ELSE 'RECEBER' END AS TIPO,
              NG.COD_EMPRESA,
              NG.COD_FILIAL,
              PF.COD_CONTA,
              PF.COD_TABELA,
              PF.FORM_LANCAMENTO,
              PF.SEQ_PLA_PREVISAO,
              TO_CHAR(NG.NR_CONTRATO) AS NR_DOCUMENTO,
              PF.DATA_VCTO AS DATA_VCTO,
              NG.DATA_NEGOCIACAO AS DATA_LCTO,
              PF.SEQ_PLA_ENDERECO,
              PF.OBSERVACOES,
              PF.SEQ_PLA_MOEDA,
              MO.SIGLA_MOEDA,
              COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) AS VALOR_INDICE,
              'PREVISAO_NEG_ALGODAO' AS STATUS,
              PF.Valor_Previsto AS VLR_ORIGINAL,
              nvl(BX.VALOR,0) AS VLR_BAIXA_ORIGINAL,
              PF.Valor_Previsto AS VLR_DOCUM,
              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 2
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 1 ELSE 0 END AS ID_MOEDA_FILTRO,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN 'DOLAR'
                   WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA  THEN 'REAL' ELSE '' END AS MOEDA_FILTRO,

              0 AS VLR_REAL,

              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_REAIS,

              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
              ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END VLR_EM_REAIS,

              CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_REAIS1,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0))*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) ELSE 0 END VLR_SO_DOLAR,

              CASE WHEN PG.MOEDA_DOLAR = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0) ELSE 0 END VLR_EM_DOLAR,

              (CASE WHEN PG.MOEDA_REAL = PF.SEQ_PLA_MOEDA THEN (PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)
               ELSE ((PF.VALOR_PREVISTO)-nvl(BX.VALOR,0)) * COMPASs_PRD.findicemoeda(PF.SEQ_PLA_MOEDA,TRUNC(SYSDATE)) END)*(CASE WHEN PF.OPERACAO = 'D' THEN -1 ELSE 1 END) VLR_FINAL,
              'N' AS BAIXADO
         FROM COMPASs_PRD.PREVISOES_FINANCEIRAS PF,
              COMPASs_PRD.NEGOCIACAO_ALGODAO NG,
              COMPASs_PRD.PAR_GERAL PG,
              COMPASs_PRD.Moedas MO,
              (SELECT SUM(LP.VALOR*DECODE(LP.TIPO_OPERACAO,'D',-1,DECODE(LP.TIPO_OPERACAO,'R',-1,1))) AS VALOR,
                      LPP.SEQ_PLA_PREVISAO
                 FROM COMPASs_PRD.LIGA_PRODUTO_PROVISAO LP,
                      COMPASs_PRD.LIGA_PREVISAO_PRODUTO LPP
                WHERE LP.SEQ_PLA_PREV_PROD = LPP.SEQ_PLA_LIGA
                  AND NVL(LP.COMPENSADO,'N') = 'N'
                GROUP BY LPP.SEQ_PLA_PREVISAO) BX
        WHERE NG.SEQ_PLA_NEGOCIACAO = PF.SEQ_PLA_NEGOCIACAO_ALG
          AND PF.SEQ_PLA_PREVISAO = BX.SEQ_PLA_PREVISAO(+)
          AND PF.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA(+)
          AND NVL(PF.FINALIZADO,'N') <> 'S') PX,
       COMPASs_PRD.VW_CLIENTE_ENDERECO CE,
       COMPASs_PRD.EMPRESAS EM,
       COMPASs_PRD.FILIAIS FI,
       COMPASs_PRD.GER_PLANO_CONTAS GP
 WHERE PX.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND PX.COD_EMPRESA     = EM.COD_EMPRESA
   AND PX.COD_EMPRESA     = FI.COD_EMPRESA
   AND PX.COD_FILIAL      = FI.COD_FILIAL
   AND PX.COD_CONTA       = GP.COD_CONTA
   AND PX.COD_TABELA      = GP.COD_TABELA