CREATE MATERIALIZED VIEW FLUXO_BANCOS_BI
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT
       'BANCO' AS STATUS,
       FC.COD_EMPRESA,
       EM.SIGLA_EMPRESA,
       FC.COD_FILIAL,
       FIL.SIGLA_FILIAL,
       FC.SEQ_PLA_ENDERECO,
       CLI.NOME_CLIENTE,
       MV3.SEQ_PLA_TIPO_DOC,
       MV3.SEQ_PLA_MOEDA,
       MV3.DATA_DOCUM AS DATA,
       MV3.NR_DOCUMENTO,
       BA.SIGLA_BANCO,
       'AG:' || AG.COD_AGENCIA || ' / CC:' || FC.NR_CONTA AS CONTA,
       '100' AS SEQ_PLA_AGRUPADOR,
       FC.TIPO_CONTA,
       (nvl(MV3.CREDITO, 0)) AS CREDITO,
       (nvl(MV3.DEBITO, 0)) AS  DEBITO,
       SIGLA_MOEDA,
       DESC_MOEDA
  FROM COMPASs_PRD.FIN_CONTAS FC,
       COMPASs_PRD.FILIAIS FIL,
       COMPASs_PRD.AGENCIAS AG,
       COMPASs_PRD.BANCOS BA,
       COMPASs_PRD.EMPRESAS EM,
       COMPASs_PRD.CLIENTES CLI,
       COMPASs_PRD.CLIENTES_ENDERECOS CE,
       (SELECT FI.SEQ_PLA_FIN_CONTA,
               FI.SEQ_PLA_MOEDA,
               FI.SEQ_PLA_TIPO_DOC,
               FI.NR_DOCUMENTO,
               MO.SIGLA_MOEDA,
               MO.DESC_MOEDA,
               NVL(FI.DATA_PREV_COMPENSA, FI.DATA_DOCUM) AS DATA_DOCUM,
               (CASE WHEN FI.DEB_CRED = 'D' THEN ROUND(FI.VALOR_TOTAL, 2) ELSE 0 END) AS DEBITO,
               (CASE WHEN FI.DEB_CRED = 'C' THEN ROUND(FI.VALOR_TOTAL, 2) ELSE 0 END) AS CREDITO
          FROM COMPASs_PRD.FIN_MOVIMENTO FI,
               COMPASs_PRD.TIPOS_LANCTOS TL,
               COMPASs_PRD.TIPO_DOCUMENTO TD,
               COMPASs_PRD.MOEDAS MO
         WHERE FI.COD_TIPO_LCTO = TL.COD_TIPO_LCTO
           AND FI.SEQ_PLA_TIPO_DOC = TD.SEQ_PLA_TIPO_DOC(+)
           AND FI.SEQ_PLA_MOEDA = MO.SEQ_PLA_MOEDA
           AND NVL(FI.CANCELADO, 'N') = 'N'
           AND FI.CONCILIADO = 'S'
         ) MV3
 WHERE 1=1
   AND FC.SEQ_PLA_FIN_CONTA = MV3.SEQ_PLA_FIN_CONTA(+)
   AND FC.COD_EMPRESA = FIL.COD_EMPRESA
   AND FC.SEQ_PLA_AGENCIA = AG.SEQ_PLA_AGENCIA(+)
   AND AG.SEQ_PLA_BANCO = BA.SEQ_PLA_BANCO(+)
   AND FC.TIPO_CONTA <> 'T'
   AND NVL(FC.ATIVO, 'N') IN ('S', 'N')
   AND NVL(FC.FLUXO_CAIXA, 'N') = 'S'
   AND FC.COD_FILIAL = FIL.COD_FILIAL
   AND FC.SEQ_PLA_ENDERECO = CE.SEQ_PLA_ENDERECO
   AND CE.SEQ_PLA_CLIENTE = CLI.SEQ_PLA_CLIENTE
   AND FC.COD_EMPRESA = EM.COD_EMPRESA