CREATE MATERIALIZED VIEW VW_CONSULTA_ESTOQUE_ARMAZEM REFRESH FORCE ON DEMAND START WITH TO_DATE('18-03-2021 16:07:23', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE + 10/24/60 AS
SELECT '0' AS TIPO,
       SI.ANO_SALDO,
       AR.COD_EMPRESA,
       AR.COD_FILIAL,
       0 COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       SI.SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PR.COD_FABRICANTE,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       TO_DATE('01/01'||SI.ANO_SALDO,'DD/MM/RRRR') AS DATA,
       SUM(AGRICOLA.ConverteUnidade(SI.SEQ_PLA_PRODUTO,UN.SEQ_PLA_UNIDADE,SI.QUANTIDADE)) AS ESTOQUE_INICIAL,
       0 AS ENTRADAS,
       0 AS SAIDAS
  FROM AGRICOLA.PRODUTO_SALDO_INI SI,
       AGRICOLA.PRODUTOS          PR,
       AGRICOLA.SUB_GRUPO         SG,
       AGRICOLA.GRUPO             GR,
       AGRICOLA.ARMAZENS          AR,
       AGRICOLA.FILIAIS           FI,
       AGRICOLA.UNIDADE_PRODUTO   UN,
       AGRICOLA.SAFRAS            SA
 WHERE SI.SEQ_PLA_PRODUTO      = PR.SEQ_PLA_PRODUTO
   AND SI.SEQ_PLA_ARMAZEM      = AR.SEQ_PLA_ARMAZEM
   AND SI.COD_EMPRESA          = FI.COD_EMPRESA
   AND SI.COD_FILIAL           = FI.COD_FILIAL
   AND PR.SEQ_PLA_SUB_GRUPO    = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND PR.SEQ_PLA_UNIDADE      = UN.SEQ_PLA_UNIDADE
   AND SI.ANO_SALDO            = SA.ANO_SALDO
   AND PR.ATIVO                = 'S'
   AND DECODE(PR.SERVICO,NULL,'N',PR.SERVICO) = 'N'
--   AND SI.ANO_SALDO            = '2014'
--   AND AR.COD_EMPRESA          = 1
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
 GROUP BY '0',
          SI.ANO_SALDO,
          AR.COD_EMPRESA,
          AR.COD_FILIAL,
          FI.DESCRICAO_FILIAL,
          SI.SEQ_PLA_ARMAZEM,
          AR.DESC_ARMAZEM,
          GR.SEQ_PLA_GRUPO,
          GR.DESCRICAO_GRUPO,
          SG.SEQ_PLA_SUB_GRUPO,
          SG.DESC_SUB_GRUPO,
          PR.COD_FABRICANTE,
          PR.SEQ_PLA_PRODUTO,
          PR.DESCRICAO_PRODUTO,
          UN.SEQ_PLA_UNIDADE,
          UN.SIGLA_UNIDADE,
          TO_DATE('01/01'||SI.ANO_SALDO,'DD/MM/RRRR')
UNION
SELECT '1' AS TIPO,
       SF.ANO_SALDO,
       AR.COD_EMPRESA,
       AR.COD_FILIAL,
       EN.COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       IT.SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PR.COD_FABRICANTE,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       TRUNC(EN.DATA_ENTRADA) AS DATA,
       0 AS ESTOQUE_INICIAL,
       SUM(DECODE(IT.QUANTIDADE_CHEGADA,NULL,ConverteUnidade(IT.SEQ_PLA_PRODUTO,IT.SEQ_PLA_UNIDADE,IT.QUANTIDADE),IT.QUANTIDADE_CHEGADA))  as ENTRADAS,
       0 AS SAIDAS
  FROM AGRICOLA.EST_ENTRADAS_ITENS IT,
       AGRICOLA.EST_ENTRADAS       EN,
       AGRICOLA.PRODUTOS           PR,
       AGRICOLA.SUB_GRUPO          SG,
       AGRICOLA.GRUPO              GR,
       AGRICOLA.ARMAZENS           AR,
       AGRICOLA.FILIAIS            FI,
       AGRICOLA.SAFRAS             SF,
       AGRICOLA.UNIDADE_PRODUTO    UN
 WHERE IT.SEQ_PLA_PRODUTO      = PR.SEQ_PLA_PRODUTO
   AND IT.SEQ_PLA_ENTRADA      = EN.SEQ_PLA_ENTRADA
   AND IT.SEQ_PLA_ARMAZEM      = AR.SEQ_PLA_ARMAZEM
   AND EN.COD_EMPRESA          = FI.COD_EMPRESA
   AND EN.COD_FILIAL           = FI.COD_FILIAL
   AND PR.SEQ_PLA_SUB_GRUPO    = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND EN.COD_SAFRA            = SF.COD_SAFRA
   AND PR.SEQ_PLA_UNIDADE      = UN.SEQ_PLA_UNIDADE
   AND PR.ATIVO                = 'S'
   AND DECODE(PR.SERVICO,NULL,'N',PR.SERVICO) = 'N'
   AND (IT.SEQ_PLA_PRODUTO NOT IN (SELECT SEQ_PLA_PRODUTO FROM AGRICOLA.PRODUTOS WHERE NVL(ENTRADA_ROMANEIO,'N') = 'S') OR EN.FORM_LANCAMENTO      = 'DFMFATURAPEDIDO' OR EN.FORM_LANCAMENTO = 'DFMNOTAENTRADA')
   AND NVL(EN.CANCELADO,'N') <> 'S'
--   AND EN.COD_EMPRESA          = 1
--   AND EN.COD_SAFRA IN (SELECT COD_SAFRA FROM AGRICOLA.SAFRAS WHERE ANO_SALDO = '2014')
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
--   AND TRUNC(EN.DATA_ENTRADA) <= TO_DATE('20/03/2021')
 GROUP BY '1',
          SF.ANO_SALDO,
          AR.COD_EMPRESA,
          AR.COD_FILIAL,
          EN.COD_SAFRA,
          EN.COD_SAFRA,
          FI.DESCRICAO_FILIAL,
          IT.SEQ_PLA_ARMAZEM,
          AR.DESC_ARMAZEM,
          GR.SEQ_PLA_GRUPO,
          GR.DESCRICAO_GRUPO,
          SG.SEQ_PLA_SUB_GRUPO,
          SG.DESC_SUB_GRUPO,
          PR.COD_FABRICANTE,
          PR.SEQ_PLA_PRODUTO,
          PR.DESCRICAO_PRODUTO,
          UN.SEQ_PLA_UNIDADE,
          UN.SIGLA_UNIDADE,
          EN.DATA_ENTRADA
UNION
SELECT '2' AS TIPO,
       SF.ANO_SALDO,
       AR.COD_EMPRESA,
       AR.COD_FILIAL,
       EN.COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       EN.SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PR.COD_FABRICANTE,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       EN.DATA,
       0 AS ESTOQUE_INICIAL,
       0 AS ENTRADAS,
       SUM(ConverteUnidade(IT.SEQ_PLA_PRODUTO,IT.SEQ_PLA_UNIDADE,IT.QUANTIDADE)) AS SAIDAS
  FROM AGRICOLA.ALM_REQUIS_PRODUTOS IT,
       AGRICOLA.ALM_REQUISICAO      EN,
       AGRICOLA.PRODUTOS            PR,
       AGRICOLA.SUB_GRUPO           SG,
       AGRICOLA.GRUPO               GR,
       AGRICOLA.ARMAZENS            AR,
       AGRICOLA.FILIAIS             FI,
       AGRICOLA.SAFRAS              SF,
       AGRICOLA.UNIDADE_PRODUTO     UN,
       AGRICOLA.LIGA_REQUIS_SAIDA   RS,
       AGRICOLA.TIPOS_LANCTOS       TL,
       AGRICOLA.EST_SAIDAS_ITENS    EI,
       AGRICOLA.EST_SAIDAS          EE
 WHERE IT.SEQ_PLA_PRODUTO      = PR.SEQ_PLA_PRODUTO
   AND IT.SEQ_PLA_REQUIS       = EN.SEQ_PLA_REQUIS
   AND EN.SEQ_PLA_ARMAZEM      = AR.SEQ_PLA_ARMAZEM
   AND EN.COD_EMPRESA          = FI.COD_EMPRESA
   AND EN.COD_FILIAL           = FI.COD_FILIAL
   AND PR.SEQ_PLA_SUB_GRUPO    = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND EN.COD_SAFRA            = SF.COD_SAFRA
   AND PR.SEQ_PLA_UNIDADE      = UN.SEQ_PLA_UNIDADE
   AND PR.ATIVO                = 'S'
   AND IT.SEQ_PLA_REQ_PROD     = RS.SEQ_PLA_REQ_PROD (+)
   AND RS.SEQ_PLA_SAI_ITEM     = EI.SEQ_PLA_SAI_ITEM (+)
   AND EI.SEQ_PLA_SAIDA        = EE.SEQ_PLA_SAIDA    (+)
   AND EE.COD_TIPO_LCTO        = TL.COD_TIPO_LCTO    (+)
   AND NVL(TL.DEVOLUCAO,'N')<> 'S'
   AND NVL(EE.CANCELADO,'N') = 'N'
   AND DECODE(PR.SERVICO,NULL,'N',PR.SERVICO) = 'N'
   AND NVL(EN.FORM_LANCAMENTO,'VAZIO')<> 'DFMDEVREQUISICAO'
--   AND EN.COD_EMPRESA          = 1
--   AND EN.COD_SAFRA IN (SELECT COD_SAFRA FROM AGRICOLA.SAFRAS WHERE ANO_SALDO = '2014')
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
--   AND TRUNC(EN.DATA)         <= TO_DATE('20/03/2021')
 GROUP BY '2',
          SF.ANO_SALDO,
          AR.COD_EMPRESA,
          AR.COD_FILIAL,
          EN.COD_SAFRA,
          FI.DESCRICAO_FILIAL,
          EN.SEQ_PLA_ARMAZEM,
          AR.DESC_ARMAZEM,
          GR.SEQ_PLA_GRUPO,
          GR.DESCRICAO_GRUPO,
          SG.SEQ_PLA_SUB_GRUPO,
          SG.DESC_SUB_GRUPO,
          PR.COD_FABRICANTE,
          PR.SEQ_PLA_PRODUTO,
          PR.DESCRICAO_PRODUTO,
          UN.SEQ_PLA_UNIDADE,
          UN.SIGLA_UNIDADE,
          EN.DATA
UNION
SELECT '3' AS TIPO,
       SF.ANO_SALDO,
       AR.COD_EMPRESA,
       AR.COD_FILIAL,
       EN.COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       EN.SEQ_PLA_ARM_ORIGEM AS SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PR.COD_FABRICANTE,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       EN.DATA,
       0 AS ESTOQUE_INICIAL,
       0 AS ENTRADAS,
       SUM(ConverteUnidade(IT.SEQ_PLA_PRODUTO,IT.SEQ_PLA_UNIDADE, IT.QUANTIDADE)) AS SAIDAS
  FROM AGRICOLA.ALM_TRANSF_ITENS    IT,
       AGRICOLA.ALM_TRANSF          EN,
       AGRICOLA.PRODUTOS            PR,
       AGRICOLA.SUB_GRUPO           SG,
       AGRICOLA.GRUPO               GR,
       AGRICOLA.ARMAZENS            AR,
       AGRICOLA.FILIAIS             FI,
       AGRICOLA.SAFRAS              SF,
       AGRICOLA.UNIDADE_PRODUTO     UN
 WHERE IT.SEQ_PLA_PRODUTO      = PR.SEQ_PLA_PRODUTO
   AND IT.SEQ_PLA_TRANSF       = EN.SEQ_PLA_TRANSF
   AND EN.SEQ_PLA_ARM_ORIGEM   = AR.SEQ_PLA_ARMAZEM
   AND EN.COD_EMPRESA          = FI.COD_EMPRESA
   AND EN.CANCELADA            = 'N'
   AND EN.COD_FILIAL           = FI.COD_FILIAL
   AND PR.SEQ_PLA_SUB_GRUPO    = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND EN.COD_SAFRA            = SF.COD_SAFRA
   AND PR.SEQ_PLA_UNIDADE      = UN.SEQ_PLA_UNIDADE
   AND PR.ATIVO                = 'S'
   AND DECODE(PR.SERVICO,NULL,'N',PR.SERVICO) = 'N'
--   AND EN.COD_EMPRESA          = 1
--   AND EN.COD_SAFRA IN (SELECT COD_SAFRA FROM AGRICOLA.SAFRAS WHERE ANO_SALDO = '2014')
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
--   AND TRUNC(EN.DATA)         <= TO_DATE('20/03/2021')
 GROUP BY '3',
          SF.ANO_SALDO,
          AR.COD_EMPRESA,
          AR.COD_FILIAL,
          EN.COD_SAFRA,
          FI.DESCRICAO_FILIAL,
          EN.SEQ_PLA_ARM_ORIGEM,
          AR.DESC_ARMAZEM,
          GR.SEQ_PLA_GRUPO,
          GR.DESCRICAO_GRUPO,
          SG.SEQ_PLA_SUB_GRUPO,
          SG.DESC_SUB_GRUPO,
          PR.COD_FABRICANTE,
          PR.SEQ_PLA_PRODUTO,
          PR.DESCRICAO_PRODUTO,
          UN.SEQ_PLA_UNIDADE,
          UN.SIGLA_UNIDADE,
          EN.DATA
UNION
SELECT '4' AS TIPO,
       SF.ANO_SALDO,
       AR.COD_EMPRESA,
       AR.COD_FILIAL,
       EN.COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       EN.SEQ_PLA_ARM_DESTINO AS SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PR.COD_FABRICANTE,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       EN.DATA,
       0 AS ESTOQUE_INICIAL,
       SUM(ConverteUnidade(IT.SEQ_PLA_PRODUTO,IT.SEQ_PLA_UNIDADE,DECODE(EN.ACEITE, 'S', IT.QUANTIDADE, 0))) AS ENTRADAS,
       0 AS SAIDAS
  FROM AGRICOLA.ALM_TRANSF_ITENS    IT,
       AGRICOLA.ALM_TRANSF          EN,
       AGRICOLA.PRODUTOS            PR,
       AGRICOLA.SUB_GRUPO           SG,
       AGRICOLA.GRUPO               GR,
       AGRICOLA.ARMAZENS            AR,
       AGRICOLA.FILIAIS             FI,
       AGRICOLA.SAFRAS              SF,
       AGRICOLA.UNIDADE_PRODUTO     UN
 WHERE IT.SEQ_PLA_PRODUTO      = PR.SEQ_PLA_PRODUTO
   AND IT.SEQ_PLA_TRANSF       = EN.SEQ_PLA_TRANSF
   AND EN.SEQ_PLA_ARM_DESTINO  = AR.SEQ_PLA_ARMAZEM
   AND EN.COD_EMPRESA          = FI.COD_EMPRESA
   AND EN.COD_FILIAL           = FI.COD_FILIAL
   AND NVL(EN.CANCELADA,'N') = 'N'
   AND PR.SEQ_PLA_SUB_GRUPO    = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND EN.COD_SAFRA            = SF.COD_SAFRA
   AND PR.SEQ_PLA_UNIDADE      = UN.SEQ_PLA_UNIDADE
   AND PR.ATIVO                = 'S'
   AND DECODE(PR.SERVICO,NULL,'N',PR.SERVICO) = 'N'
--   AND EN.COD_EMPRESA          = 1
--   AND EN.COD_SAFRA IN (SELECT COD_SAFRA FROM AGRICOLA.SAFRAS WHERE ANO_SALDO = '2014')
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
--   AND TRUNC(EN.DATA)         <= TO_DATE('20/03/2021')
 GROUP BY '4',
          SF.ANO_SALDO,
          AR.COD_EMPRESA,
          AR.COD_FILIAL,
          EN.COD_SAFRA,
          FI.DESCRICAO_FILIAL,
          EN.SEQ_PLA_ARM_DESTINO,
          AR.DESC_ARMAZEM,
          GR.SEQ_PLA_GRUPO,
          GR.DESCRICAO_GRUPO,
          SG.SEQ_PLA_SUB_GRUPO,
          SG.DESC_SUB_GRUPO,
          PR.COD_FABRICANTE,
          PR.SEQ_PLA_PRODUTO,
          PR.DESCRICAO_PRODUTO,
          UN.SEQ_PLA_UNIDADE,
          UN.SIGLA_UNIDADE,
          EN.DATA
UNION
SELECT '5' AS TIPO,
       SF.ANO_SALDO,
       AR.COD_EMPRESA,
       AR.COD_FILIAL,
       EN.COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       EN.SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PR.COD_FABRICANTE,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       EN.DATA,
       0 AS ESTOQUE_INICIAL,
       SUM(ConverteUnidade(IT.SEQ_PLA_PRODUTO,IT.SEQ_PLA_UNIDADE,IT.QUANTIDADE)) AS ENTRADAS,
       0 AS SAIDAS
  FROM AGRICOLA.ALM_REQUIS_PRODUTOS IT,
       AGRICOLA.ALM_REQUISICAO      EN,
       AGRICOLA.PRODUTOS            PR,
       AGRICOLA.SUB_GRUPO           SG,
       AGRICOLA.GRUPO               GR,
       AGRICOLA.ARMAZENS            AR,
       AGRICOLA.FILIAIS             FI,
       AGRICOLA.SAFRAS              SF,
       AGRICOLA.UNIDADE_PRODUTO     UN
 WHERE IT.SEQ_PLA_PRODUTO      = PR.SEQ_PLA_PRODUTO
   AND IT.SEQ_PLA_REQUIS       = EN.SEQ_PLA_REQUIS
   AND EN.SEQ_PLA_ARMAZEM      = AR.SEQ_PLA_ARMAZEM
   AND EN.COD_EMPRESA          = FI.COD_EMPRESA
   AND EN.COD_FILIAL           = FI.COD_FILIAL
   AND PR.SEQ_PLA_SUB_GRUPO    = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND EN.COD_SAFRA            = SF.COD_SAFRA
   AND PR.SEQ_PLA_UNIDADE      = UN.SEQ_PLA_UNIDADE
   AND PR.ATIVO                = 'S'
   AND DECODE(PR.SERVICO,NULL,'N',PR.SERVICO) = 'N'
   AND EN.FORM_LANCAMENTO      = 'DFMDEVREQUISICAO'
--   AND EN.COD_EMPRESA          = 1
--   AND EN.COD_SAFRA IN (SELECT COD_SAFRA FROM AGRICOLA.SAFRAS WHERE ANO_SALDO = '2014')
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
--   AND TRUNC(EN.DATA)         <= TO_DATE('20/03/2021')
 GROUP BY '5',
        SF.ANO_SALDO,
        AR.COD_EMPRESA,
        AR.COD_FILIAL,
        EN.COD_SAFRA,
        FI.DESCRICAO_FILIAL,
        EN.SEQ_PLA_ARMAZEM,
        AR.DESC_ARMAZEM,
        GR.SEQ_PLA_GRUPO,
        GR.DESCRICAO_GRUPO,
        SG.SEQ_PLA_SUB_GRUPO,
        SG.DESC_SUB_GRUPO,
        PR.COD_FABRICANTE,
        PR.SEQ_PLA_PRODUTO,
        PR.DESCRICAO_PRODUTO,
        UN.SEQ_PLA_UNIDADE,
        UN.SIGLA_UNIDADE,
        EN.DATA
 UNION
SELECT '6' AS TIPO,
       SF.ANO_SALDO,
       ES.COD_EMPRESA,
       ES.COD_FILIAL,
       ES.COD_SAFRA,
       FI.DESCRICAO_FILIAL,
       AR.SEQ_PLA_ARMAZEM,
       AR.DESC_ARMAZEM,
       GR.SEQ_PLA_GRUPO,
       GR.DESCRICAO_GRUPO,
       SG.SEQ_PLA_SUB_GRUPO,
       SG.DESC_SUB_GRUPO,
       PDT.COD_FABRICANTE,
       PDT.SEQ_PLA_PRODUTO,
       PDT.DESCRICAO_PRODUTO,
       UN.SEQ_PLA_UNIDADE,
       UN.SIGLA_UNIDADE,
       ES.DATA_SAIDA,
       0 AS ESTOQUE_INICIAL,
       0 AS ENTRADAS,
       SUM(ConverteUnidade(ESI.SEQ_PLA_PRODUTO,ESI.SEQ_PLA_UNIDADE,ESI.QUANTIDADE))  AS SAIDAS
  FROM AGRICOLA.EST_SAIDAS_ITENS    ESI,
       AGRICOLA.EST_SAIDAS          ES,
       AGRICOLA.TIPOS_LANCTOS       TL,
       AGRICOLA.PRODUTOS            PDT,
       AGRICOLA.ARMAZENS            AR,
       AGRICOLA.SAFRAS              SF,
       AGRICOLA.FILIAIS             FI,
       AGRICOLA.GRUPO               GR,
       AGRICOLA.SUB_GRUPO           SG,
       AGRICOLA.UNIDADE_PRODUTO     UN
 WHERE ESI.SEQ_PLA_SAIDA       = ES.SEQ_PLA_SAIDA
   AND ESI.SEQ_PLA_ARMAZEM     = AR.SEQ_PLA_ARMAZEM
   AND ES.COD_TIPO_LCTO        = TL.COD_TIPO_LCTO
   AND TL.DEVOLUCAO            = 'S'
   AND NVL(ES.CANCELADO,'N') = 'N'
   AND ESI.SEQ_PLA_PRODUTO     = PDT.SEQ_PLA_PRODUTO
   AND PDT.SEQ_PLA_SUB_GRUPO   = SG.SEQ_PLA_SUB_GRUPO
   AND SG.SEQ_PLA_GRUPO        = GR.SEQ_PLA_GRUPO
   AND ES.COD_SAFRA            = SF.COD_SAFRA
   AND AR.COD_FILIAL           = FI.COD_FILIAL
   AND PDT.SEQ_PLA_UNIDADE     = UN.SEQ_PLA_UNIDADE
   AND AR.COD_EMPRESA          = FI.COD_EMPRESA
   AND PDT.ATIVO                = 'S'
   AND DECODE(PDT.SERVICO,NULL,'N',PDT.SERVICO) = 'N'
--   AND ES.COD_EMPRESA          = 1
--   AND ES.COD_SAFRA IN (SELECT COD_SAFRA FROM AGRICOLA.SAFRAS WHERE ANO_SALDO = '2014')
--   AND SG.SEQ_PLA_GRUPO        = ' 207498501'
--   AND TRUNC(ES.DATA_SAIDA)         <= TO_DATE('20/03/2021')
  GROUP BY '6',
         SF.ANO_SALDO,
         ES.COD_EMPRESA,
         ES.COD_FILIAL,
         ES.COD_SAFRA,
         FI.DESCRICAO_FILIAL,
         AR.SEQ_PLA_ARMAZEM,
         AR.DESC_ARMAZEM,
         GR.SEQ_PLA_GRUPO,
         SG.SEQ_PLA_SUB_GRUPO,
         SG.DESC_SUB_GRUPO,
         PDT.COD_FABRICANTE,
         PDT.SEQ_PLA_PRODUTO,
         PDT.DESCRICAO_PRODUTO,
         UN.SEQ_PLA_UNIDADE,
         UN.SIGLA_UNIDADE,
         ES.DATA_SAIDA,
         GR.DESCRICAO_GRUPO;
