CREATE MATERIALIZED VIEW VW_GER_MOVIMENTO_CUSTOS REFRESH FORCE ON DEMAND START WITH TO_DATE('23-03-2021 14:31:13', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE + 10/24/60 AS
SELECT DISTINCT EM.COD_EMPRESA,
        GE.COD_FILIAL,
        GE.COD_SAFRA,
        EM.NOME_EMPRESA,
        GP.SEQ_PLANILHA AS SEQ_PLA_CONTA,
        GP.COD_CONTA,
        GP.COD_TABELA,
        GP.NOME_CONTA,
        GE.SEQ_PLA_MOV_GER, GE.NR_DOCUMENTO,
        GE.SEQ_PLA_FAZENDA, CL.NOME_CLIENTE,
        TRUNC(GE.DATA_MVTO)DATA_MVTO,
        ROUND((GE.VALOR_REAL * NVL(TS.PORC,0)) / 100,2) VALOR_REAL,
        NVL(TS.PORC,0) PORC_CULT,
        TC.SEQ_PLA_TIPO_CULT,
        TC.DESC_CULTURA,
        '' SEQ_PLA_CCUSTO,
        '' DESC_CCUSTO

   FROM AGRICOLA.GER_PLANO_CONTAS   GP,
        AGRICOLA.GER_MOVIMENTO      GE,
        AGRICOLA.CONTAS_PAGAR       CP,
        AGRICOLA.TIPO_CULTURA       TC,
        AGRICOLA.EMPRESAS           EM,
        AGRICOLA.CLIENTES_ENDERECOS CE,
        AGRICOLA.CLIENTES           CL,
        (SELECT TS.COD_SAFRA, TS.SEQ_PLA_TIPO_CULT, TH.SEQ_PLA_FAZENDA,
               SUM(TS.QTDE_HA) QTDE_HA,
               ROUND((SUM(TS.QTDE_HA) * 100) / (SELECT SUM(TS1.QTDE_HA) FROM AGRICOLA.TALHOES TH1, AGRICOLA.TALHOES_SAFRA TS1 WHERE TH1.SEQ_PLA_TALHAO = TS1.SEQ_PLA_TALHAO AND TH1.SEQ_PLA_FAZENDA = TH.SEQ_PLA_FAZENDA AND TS1.COD_SAFRA = TS.COD_SAFRA),2) PORC
          FROM AGRICOLA.TALHOES TH, AGRICOLA.TALHOES_SAFRA TS
         WHERE TH.SEQ_PLA_TALHAO = TS.SEQ_PLA_TALHAO
         GROUP BY TS.COD_SAFRA, TS.SEQ_PLA_TIPO_CULT, TH.SEQ_PLA_FAZENDA
         ORDER BY 3,5
       )TS
  WHERE GP.COD_TABELA        = GE.COD_TABELA
    AND GP.COD_CONTA         = GE.COD_CONTA
    AND GE.SEQ_PLA_PAGAR     = CP.SEQ_PLA_PAGAR
    AND GE.SEQ_PLA_FAZENDA   = TS.SEQ_PLA_FAZENDA
    AND GE.COD_SAFRA         = TS.COD_SAFRA
    AND TS.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT
    AND GP.COD_TABELA        = EM.COD_TABELA_GERENCIAL
    AND GE.COD_EMPRESA       = EM.COD_EMPRESA
    AND GE.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
    AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
    AND CP.SEQ_PLA_ORIGEM IS NULL    
    AND GP.DEBITO_CREDITO    = 'D'
    AND GE.SEQ_PLA_MOV_FIN IS NULL
UNION
--CP DA EST_ENTRADAS COM CCUSTO VINCULADO NO RATEIOCUSTO
 SELECT DISTINCT EM.COD_EMPRESA,
        GE.COD_FILIAL,
        GE.COD_SAFRA,
        EM.NOME_EMPRESA,
        GP.SEQ_PLANILHA AS SEQ_PLA_CONTA,
        GP.COD_CONTA,
        GP.COD_TABELA,
        GP.NOME_CONTA,
        GE.SEQ_PLA_MOV_GER, GE.NR_DOCUMENTO,
        GE.SEQ_PLA_FAZENDA, CL.NOME_CLIENTE,
        TRUNC(GE.DATA_MVTO)DATA_MVTO,
        ROUND((GE.VALOR_REAL * NVL(RA.PERC_RATEIO,0)) / 100,2) VALOR_REAL,
        NVL(RA.PERC_RATEIO,0) PORC_CULT,
        TC.SEQ_PLA_TIPO_CULT,
        TC.DESC_CULTURA,
        CC.SEQ_PLA_CCUSTO,
        CC.IDENTIFICACAO DESC_CCUSTO
   FROM AGRICOLA.GER_PLANO_CONTAS   GP,
        AGRICOLA.GER_MOVIMENTO      GE,
        AGRICOLA.CONTAS_PAGAR       CP,
        AGRICOLA.EST_ENTRADAS       EE,
        AGRICOLA.EST_ENTRADAS_ITENS EI,
        AGRICOLA.ALM_CCUSTO         CC,
        AGRICOLA.ALM_CCUSTO_RATEIOCUSTO RA,
        AGRICOLA.TIPO_CULTURA       TC,
        AGRICOLA.EMPRESAS           EM,
        AGRICOLA.CLIENTES_ENDERECOS CE,
        AGRICOLA.CLIENTES           CL
  WHERE GP.COD_TABELA        = GE.COD_TABELA
    AND GP.COD_CONTA         = GE.COD_CONTA
    AND GE.SEQ_PLA_PAGAR     = CP.SEQ_PLA_PAGAR
    AND CP.SEQ_PLA_ORIGEM    = EE.SEQ_PLA_ENTRADA
    AND EE.SEQ_PLA_ENTRADA   = EI.SEQ_PLA_ENTRADA
    AND EI.SEQ_PLA_CCUSTO    = CC.SEQ_PLA_CCUSTO
    AND CC.SEQ_PLA_CCUSTO    = RA.SEQ_PLA_CCUSTO
    AND EE.COD_SAFRA         = RA.COD_SAFRA
    AND RA.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT
    AND GP.COD_TABELA        = EM.COD_TABELA_GERENCIAL
    AND GE.COD_EMPRESA       = EM.COD_EMPRESA
    AND GE.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
    AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
    AND GP.DEBITO_CREDITO    = 'D'
    AND GE.SEQ_PLA_MOV_FIN IS NULL        
UNION
--CP DA EST_ENTRADAS COM CCUSTO SEM VINCULO NO RATEIOCUSTO
 SELECT DISTINCT EM.COD_EMPRESA,
        GE.COD_FILIAL,
        GE.COD_SAFRA,
        EM.NOME_EMPRESA,
        GP.SEQ_PLANILHA AS SEQ_PLA_CONTA,
        GP.COD_CONTA,
        GP.COD_TABELA,
        GP.NOME_CONTA,
        GE.SEQ_PLA_MOV_GER, GE.NR_DOCUMENTO,
        GE.SEQ_PLA_FAZENDA, CL.NOME_CLIENTE,
        TRUNC(GE.DATA_MVTO)DATA_MVTO,
        ROUND((GE.VALOR_REAL * NVL(TS.PORC,0)) / 100,2) VALOR_REAL,
        NVL(TS.PORC,0) PORC_CULT,
        TC.SEQ_PLA_TIPO_CULT,
        TC.DESC_CULTURA,
        CC.SEQ_PLA_CCUSTO,
        CC.IDENTIFICACAO DESC_CCUSTO
   FROM AGRICOLA.GER_PLANO_CONTAS   GP,
        AGRICOLA.GER_MOVIMENTO      GE,
        AGRICOLA.CONTAS_PAGAR       CP,
        AGRICOLA.EST_ENTRADAS       EE,
        AGRICOLA.EST_ENTRADAS_ITENS EI,
        AGRICOLA.ALM_CCUSTO         CC,
        AGRICOLA.TIPO_CULTURA       TC,
        AGRICOLA.EMPRESAS           EM,
        AGRICOLA.CLIENTES_ENDERECOS CE,
        AGRICOLA.CLIENTES           CL,
       (SELECT TS.COD_SAFRA, TS.SEQ_PLA_TIPO_CULT, TH.SEQ_PLA_FAZENDA,
               SUM(TS.QTDE_HA) QTDE_HA,
               ROUND((SUM(TS.QTDE_HA) * 100) / (SELECT SUM(TS1.QTDE_HA) FROM AGRICOLA.TALHOES TH1, AGRICOLA.TALHOES_SAFRA TS1 WHERE TH1.SEQ_PLA_TALHAO = TS1.SEQ_PLA_TALHAO AND TH1.SEQ_PLA_FAZENDA = TH.SEQ_PLA_FAZENDA AND TS1.COD_SAFRA = TS.COD_SAFRA),2) PORC
          FROM AGRICOLA.TALHOES TH, AGRICOLA.TALHOES_SAFRA TS
         WHERE TH.SEQ_PLA_TALHAO = TS.SEQ_PLA_TALHAO
         GROUP BY TS.COD_SAFRA, TS.SEQ_PLA_TIPO_CULT, TH.SEQ_PLA_FAZENDA
         ORDER BY 3,5
       )TS
  WHERE GP.COD_TABELA        = GE.COD_TABELA
    AND GP.COD_CONTA         = GE.COD_CONTA
    AND GE.SEQ_PLA_PAGAR     = CP.SEQ_PLA_PAGAR
    AND CP.SEQ_PLA_ORIGEM    = EE.SEQ_PLA_ENTRADA
    AND EE.SEQ_PLA_ENTRADA   = EI.SEQ_PLA_ENTRADA
    AND EI.SEQ_PLA_CCUSTO    = CC.SEQ_PLA_CCUSTO
    AND NOT EXISTS (SELECT RA.SEQ_PLA_CCUSTO FROM AGRICOLA.ALM_CCUSTO_RATEIOCUSTO RA WHERE CC.SEQ_PLA_CCUSTO = RA.SEQ_PLA_CCUSTO )
    AND GE.SEQ_PLA_FAZENDA   = TS.SEQ_PLA_FAZENDA
    AND GE.COD_SAFRA         = TS.COD_SAFRA
    AND TS.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT
    AND GP.COD_TABELA        = EM.COD_TABELA_GERENCIAL
    AND GE.COD_EMPRESA       = EM.COD_EMPRESA
    AND GE.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
    AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
    AND GP.DEBITO_CREDITO    = 'D'
    AND GE.SEQ_PLA_MOV_FIN IS NULL
--CP DA ALM_REQUISICAO COM CCUSTO VINCULADO NO RATEIOCUSTO
UNION
 SELECT DISTINCT EM.COD_EMPRESA,
        GE.COD_FILIAL,
        GE.COD_SAFRA,
        EM.NOME_EMPRESA,
        GP.SEQ_PLANILHA AS SEQ_PLA_CONTA,
        GP.COD_CONTA,
        GP.COD_TABELA,
        GP.NOME_CONTA,
        GE.SEQ_PLA_MOV_GER, GE.NR_DOCUMENTO,
        GE.SEQ_PLA_FAZENDA, CL.NOME_CLIENTE,
        TRUNC(GE.DATA_MVTO)DATA_MVTO,
        ROUND((GE.VALOR_REAL * NVL(RA.PERC_RATEIO,0)) / 100,2) VALOR_REAL,
        NVL(RA.PERC_RATEIO,0) PORC_CULT,
        TC.SEQ_PLA_TIPO_CULT,
        TC.DESC_CULTURA,
        CC.SEQ_PLA_CCUSTO,
        CC.IDENTIFICACAO DESC_CCUSTO
   FROM AGRICOLA.GER_PLANO_CONTAS       GP,
        AGRICOLA.GER_MOVIMENTO          GE,
        AGRICOLA.CONTAS_PAGAR           CP,
        AGRICOLA.ALM_REQUISICAO         RE,
        AGRICOLA.ALM_CCUSTO             CC,
        AGRICOLA.ALM_CCUSTO_RATEIOCUSTO RA,
        AGRICOLA.TIPO_CULTURA           TC,
        AGRICOLA.EMPRESAS               EM,
        AGRICOLA.CLIENTES_ENDERECOS CE,
        AGRICOLA.CLIENTES           CL
  WHERE GP.COD_TABELA        = GE.COD_TABELA
    AND GP.COD_CONTA         = GE.COD_CONTA
    AND GE.SEQ_PLA_PAGAR     = CP.SEQ_PLA_PAGAR
    AND CP.SEQ_PLA_ORIGEM    = RE.SEQ_PLA_REQUIS
    AND RE.SEQ_PLA_CCUSTO    = CC.SEQ_PLA_CCUSTO
    AND CC.SEQ_PLA_CCUSTO    = RA.SEQ_PLA_CCUSTO
    AND RE.COD_SAFRA         = RA.COD_SAFRA
    AND RA.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT
    AND GP.COD_TABELA        = EM.COD_TABELA_GERENCIAL
    AND GE.COD_EMPRESA       = EM.COD_EMPRESA
    AND GE.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
    AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
    AND GP.DEBITO_CREDITO    = 'D'
    AND GE.SEQ_PLA_MOV_FIN IS NULL
UNION
--CP DA ALM_REQUISICAO SEM CCUSTO VINCULO NO RATEIOCUSTO
 SELECT DISTINCT EM.COD_EMPRESA,
        GE.COD_FILIAL,
        GE.COD_SAFRA,
        EM.NOME_EMPRESA,
        GP.SEQ_PLANILHA AS SEQ_PLA_CONTA,
        GP.COD_CONTA,
        GP.COD_TABELA,
        GP.NOME_CONTA,
        GE.SEQ_PLA_MOV_GER, GE.NR_DOCUMENTO,
        GE.SEQ_PLA_FAZENDA, CL.NOME_CLIENTE,
        TRUNC(GE.DATA_MVTO)DATA_MVTO,
        ROUND((GE.VALOR_REAL * NVL(TS.PORC,0)) / 100,2) VALOR_REAL,
        NVL(TS.PORC,0) PORC_CULT,
        TC.SEQ_PLA_TIPO_CULT,
        TC.DESC_CULTURA,
        CC.SEQ_PLA_CCUSTO,
        CC.IDENTIFICACAO DESC_CCUSTO
   FROM AGRICOLA.GER_PLANO_CONTAS   GP,
        AGRICOLA.GER_MOVIMENTO      GE,
        AGRICOLA.CONTAS_PAGAR       CP,
        AGRICOLA.ALM_REQUISICAO     RE,
        AGRICOLA.ALM_CCUSTO         CC,
        AGRICOLA.TIPO_CULTURA       TC,
        AGRICOLA.EMPRESAS           EM,
        AGRICOLA.CLIENTES_ENDERECOS CE,
        AGRICOLA.CLIENTES           CL,
       (SELECT TS.COD_SAFRA, TS.SEQ_PLA_TIPO_CULT, TH.SEQ_PLA_FAZENDA,
               SUM(TS.QTDE_HA) QTDE_HA,
               ROUND((SUM(TS.QTDE_HA) * 100) / (SELECT SUM(TS1.QTDE_HA) FROM AGRICOLA.TALHOES TH1, AGRICOLA.TALHOES_SAFRA TS1 WHERE TH1.SEQ_PLA_TALHAO = TS1.SEQ_PLA_TALHAO AND TH1.SEQ_PLA_FAZENDA = TH.SEQ_PLA_FAZENDA AND TS1.COD_SAFRA = TS.COD_SAFRA),2) PORC
          FROM AGRICOLA.TALHOES TH, AGRICOLA.TALHOES_SAFRA TS
         WHERE TH.SEQ_PLA_TALHAO = TS.SEQ_PLA_TALHAO
         GROUP BY TS.COD_SAFRA, TS.SEQ_PLA_TIPO_CULT, TH.SEQ_PLA_FAZENDA
         ORDER BY 3,5
       )TS
  WHERE GP.COD_TABELA        = GE.COD_TABELA
    AND GP.COD_CONTA         = GE.COD_CONTA
    AND GE.SEQ_PLA_PAGAR     = CP.SEQ_PLA_PAGAR
    AND CP.SEQ_PLA_ORIGEM    = RE.SEQ_PLA_REQUIS
    AND RE.SEQ_PLA_CCUSTO    = CC.SEQ_PLA_CCUSTO
    AND NOT EXISTS (SELECT RA.SEQ_PLA_CCUSTO FROM AGRICOLA.ALM_CCUSTO_RATEIOCUSTO RA WHERE CC.SEQ_PLA_CCUSTO = RA.SEQ_PLA_CCUSTO )
    AND GE.SEQ_PLA_FAZENDA   = TS.SEQ_PLA_FAZENDA
    AND GE.COD_SAFRA         = TS.COD_SAFRA
    AND TS.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT
    AND GP.COD_TABELA        = EM.COD_TABELA_GERENCIAL
    AND GE.COD_EMPRESA       = EM.COD_EMPRESA
    AND GE.SEQ_PLA_ENDERECO  = CE.SEQ_PLA_ENDERECO
    AND CE.SEQ_PLA_CLIENTE   = CL.SEQ_PLA_CLIENTE
    AND GP.DEBITO_CREDITO    = 'D'
    AND GE.SEQ_PLA_MOV_FIN IS NULL;
