CREATE MATERIALIZED VIEW VW_CUSTO_FROTAS
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT TOTAL.*, (((QUANTIDADE-DEVOLUCAO)*UNITARIO)) AS TOTAL FROM(
SELECT TO_NUMBER(ES.NR_DOCUMENTO) AS NR_DOCUMENTO,
       ES.DATA_SAIDA,
       PR.DESCRICAO_PRODUTO,
       PR.CODIGO_REDUZIDO,
       UP.SIGLA_UNIDADE,
       ESI.QUANTIDADE,
       ESI.VALOR_DESCONTOS,
       ESI.CUSTO_TOTAL AS VALOR_TOTAL,
       DECODE(NVL(ESI.QUANTIDADE,0),0,0,ESI.CUSTO_TOTAL/ESI.QUANTIDADE) AS UNITARIO,
       MP.DESCRICAO_MARCA,
       SG.SEQ_PLA_SUB_GRUPO,
       GR.SEQ_PLA_GRUPO,
       FA.SEQ_PLA_FAMILIA,
       FA.DESCRICAO_FAMILIA AS DESCRICAO_FAMILIA,
       GR.DESCRICAO_GRUPO AS DESCRICAO_GRUPO,
       SG.DESC_SUB_GRUPO AS DESC_SUB_GRUPO,
       FI.SIGLA_FILIAL AS SIGLA_FILIAL,
       SA.DESCRICAO_SAFRA AS DESCRICAO_SAFRA,
       PM.SEQ_PLA_MODELO,
       PM.DESC_MODELO,
       CASE WHEN ESC.SEQ_PLA_CCUSTO IS NOT NULL THEN
         PC.NOME_CONTA
       ELSE
         CASE WHEN PA.DESCRICAO IS NOT NULL THEN PA.DESCRICAO END
         ||
         CASE WHEN PA.COD_IDENTIFICACAO IS NOT NULL THEN ' - '||PA.COD_IDENTIFICACAO END
         ||
         CASE WHEN PM.DESC_MODELO IS NOT NULL THEN ' - '||PM.DESC_MODELO END
         ||
         CASE WHEN PA.PLACA IS NOT NULL THEN ' - '||PA.PLACA END
         ||
         CASE WHEN PA.ANO_FABRICACAO IS NOT NULL THEN ' - '||PA.ANO_FABRICACAO END
       END AS APLICACAO,
       PG.DESCRICAO||' - '||PG.CLASSIFICACAO AS DESC_GRUPO,
        NVL((SELECT
              SUM(EI.QUANTIDADE)
         FROM
              MVR.EST_ENTRADAS E ,
              MVR.EST_ENTRADAS_ITENS EI,
              MVR.EST_DEVOLUCAO_CONSUMO ED
         WHERE
              E.SEQ_PLA_ENTRADA = EI.SEQ_PLA_ENTRADA
              AND ED.SEQ_PLA_ENT_ITEM = EI.SEQ_PLA_ENT_ITEM
              AND ED.SEQ_PLA_SAI_ITEM = ESI.SEQ_PLA_SAI_ITEM
         ),0)AS DEVOLUCAO,
         ESI.SEQ_PLA_SAI_ITEM,
         ES.SEQ_PLA_ENDERECO AS SEQ_PLA_ENDERECO_CLIENTE,
         US.NOME_USUARIO AS SOLICITANTE,
         UR.NOME_USUARIO AS RETIRANTE,
         TA.DESCRICAO AS TAREFA_CONSUMO,
         PA.SEQ_PLA_PATRIMONIO,
         PA.DESCRICAO AS DESC_FROTA,
         PA.COD_IDENTIFICACAO,
         PA.NR_PATRIMONIO,
         INF.VALOR AS KM_HORA
  FROM MVR.EST_SAIDAS_CONSUMO ESC,
       MVR.EST_SAIDAS ES,
       MVR.EST_SAIDAS_ITENS ESI,
       MVR.PRODUTOS PR,
       MVR.MARCA_PRODUTO MP,
       MVR.FILIAIS    FI,
       MVR.SAFRAS     SA,
       MVR.UNIDADE_PRODUTO UP,
       MVR.SUB_GRUPO SG,
       MVR.FAMILIAS FA,
       MVR.GRUPO GR,
       MVR.PATRIMONIOS PA,
       MVR.PAT_GRUPOS  PG,
       MVR.PAT_MODELOS PM,
       MVR.PV_CCUSTO PC,
       MVR.ALM_USUARIOS  US,
       MVR.ALM_USUARIOS  UR,
       MVR.TAREFAS_CONSUMO TA,
       (SELECT LG.SEQ_PLA_SAIDA,
               CT.VALOR
          FROM MVR.LIGA_TEMPO_USO_EST_SAIDA LG,
               MVR.CTU_MOVIMENTACAO CT
         WHERE LG.SEQ_PLA_LG_TEMPO_USO = CT.SEQ_PLA_ORIGEM
       ) INF
 WHERE ESC.SEQ_PLA_SAIDA = ES.SEQ_PLA_SAIDA
   AND ES.SEQ_PLA_SAIDA = ESI.SEQ_PLA_SAIDA
   AND ESC.SEQ_PLA_TAREFA_CONSUMO = TA.SEQ_PLA_TAREFA_CONSUMO(+)
   AND ESI.SEQ_PLA_PRODUTO = PR.SEQ_PLA_PRODUTO
   AND PR.SEQ_PLA_MARCA = MP.SEQ_PLA_MARCA(+)
   AND PR.SEQ_PLA_UNIDADE = UP.SEQ_PLA_UNIDADE(+)
   AND PR.SEQ_PLA_SUB_GRUPO = SG.SEQ_PLA_SUB_GRUPO(+)
   AND SG.SEQ_PLA_GRUPO = GR.SEQ_PLA_GRUPO(+)
   AND GR.SEQ_PLA_FAMILIA = FA.SEQ_PLA_FAMILIA(+)
   AND ESC.SEQ_PLA_PATRIMONIO = PA.SEQ_PLA_PATRIMONIO(+)
   AND PA.SEQ_PLA_MODELO = PM.SEQ_PLA_MODELO(+)
   AND ESC.SEQ_PLA_CCUSTO = PC.SEQ_PLA_CCUSTO(+)
   AND ESC.SEQ_PLA_USU_SOL = US.SEQ_PLA_USUARIO(+)
   AND ESC.SEQ_PLA_USU_RET = UR.SEQ_PLA_USUARIO(+)
   AND ES.COD_EMPRESA = FI.COD_EMPRESA
   AND ES.COD_FILIAL  = FI.COD_FILIAL
   AND ES.COD_SAFRA   = SA.COD_SAFRA
   AND PA.SEQ_PLA_GRUPO   = PG.SEQ_PLA_GRUPO(+)
   AND ESC.SEQ_PLA_SAIDA = INF.SEQ_PLA_SAIDA(+)
 ORDER BY ES.DATA_SAIDA, TO_NUMBER(ES.NR_DOCUMENTO)
)TOTAL;
