CREATE MATERIALIZED VIEW VW_CUSTO_VARIEDADE
REFRESH FORCE ON DEMAND
START WITH SYSDATE NEXT SYSDATE + 5/24/60 
AS
SELECT 
  X.COD_SAFRA,
  X.DESCRICAO_SAFRA,
  X.COD_EMPRESA,
  X.NOME_EMPRESA,
  X.SIGLA_EMPRESA,
  X.SEQ_PLA_FAZENDA,
  X.DESC_FAZENDA,
  X.SIGLA_FAZENDA,
  X.SEQ_PLA_TALHAO,
  X.NUMERO_TALHAO,
  X.DESC_TALHAO,
  X.SEQ_PLA_TIPO_CULT,
  X.DESC_CULTURA,
  X.SEQ_PLA_VARIEDADE,
  X.DESC_VARIEDADE,
  MAX(X.QTDE_HA) AS QTDE_HA_TALHAO,
  MAX(X.QTD_HA_EFETIVO) AS QTDE_HA_VARIEDADE,
  SUM(X.VALOR_TOTAL) AS VALOR_TOTAL,
  MAX(INTERNA.VALOR_TOTAL) AS VALOR_TOTAL_SEM_VARIEDADE,
  ROUND(((MAX(X.QTD_HA_EFETIVO)/MAX(X.QTDE_HA)) * 100) ,2) AS PERC_HA,
  ROUND((MAX(INTERNA.VALOR_TOTAL)/100) * ((MAX(X.QTD_HA_EFETIVO)/MAX(X.QTDE_HA)) * 100),2) AS RATEIO_VLR_SEM_VARIED,
  ROUND(SUM(X.VALOR_TOTAL) + (MAX(INTERNA.VALOR_TOTAL)/100) * ((MAX(X.QTD_HA_EFETIVO)/MAX(X.QTDE_HA)) * 100),2) AS CUSTO_TOTAL,
  ROUND((SUM(X.VALOR_TOTAL) + (MAX(INTERNA.VALOR_TOTAL)/100) * ((MAX(X.QTD_HA_EFETIVO)/MAX(X.QTDE_HA)) * 100)) / MAX(X.QTD_HA_EFETIVO) ,2) AS CUSTO_HA
FROM (
SELECT
       SA.COD_SAFRA,
       SA.DESCRICAO_SAFRA,
       RE.DESC_REGIAO,
       RE.SIGLA_REGIAO,
       EM.COD_EMPRESA,
       EM.NOME_EMPRESA,
       EM.SIGLA_EMPRESA,
       AG.SEQ_PLA_AGLOMERADO,
       AG.DESC_AGLOMERADO,
       AG.SIGLA_AGLOMERADO,
       FA.SEQ_PLA_FAZENDA,
       FA.DESC_FAZENDA,
       FA.SIGLA_FAZENDA,
       TA.SEQ_PLA_TALHAO,
       TA.NUMERO_TALHAO,
       TA.DESC_TALHAO,
       TC.SEQ_PLA_TIPO_CULT,
       TC.DESC_CULTURA,
       FN.DESCRICAO AS DESC_FINALIDADE,

       CASE
        WHEN TSA.SEQ_PLA_VARIEDADE IS NULL THEN
          (SELECT mvr.WM_CONCAT(DISTINCT V.SEQ_PLA_VARIEDADE)
             FROM mvr.RECEITUARIO_SEMENTE S, mvr.UBS_VARIEDADES V
            WHERE S.SEQ_PLA_ORDEM = OS.SEQ_PLA_ORDEM
              AND S.SEQ_PLA_VARIEDADE = V.SEQ_PLA_VARIEDADE)
        ELSE
          VAA.SEQ_PLA_VARIEDADE
      END AS SEQ_PLA_VARIEDADE,

       CASE
        WHEN TSA.SEQ_PLA_VARIEDADE IS NULL THEN
          (SELECT mvr.WM_CONCAT(DISTINCT V.DESC_VARIEDADE)
             FROM mvr.RECEITUARIO_SEMENTE S, mvr.UBS_VARIEDADES V
            WHERE S.SEQ_PLA_ORDEM = OS.SEQ_PLA_ORDEM
              AND S.SEQ_PLA_VARIEDADE = V.SEQ_PLA_VARIEDADE)
        ELSE
          VAA.DESC_VARIEDADE
      END AS DESC_VARIEDADE,

       OST.EFETIVO_CUMPRIMENTO as DATA_CUMPR,
       OST.DATA_LANCAMENTO,
       OS.DATA_EMISSAO,
       OS.NR_CONTROLE,
       FAM.DESCRICAO_FAMILIA,
       GR.DESCRICAO_GRUPO,
       
       case when esi.quantidade <> 0
        then (NVL(ESI.CUSTO_TOTAL,0)/NVL(ESI.QUANTIDADE,0))
        else 0 end AS CUSTO_TOTAL,
          
       case when esi.quantidade <> 0
        then ( NVL(ESI.CUSTO_TOTAL,0)/NVL(ESI.QUANTIDADE,0) * NVL(LTA.QUANTIDADE,0))
        else 0 end   AS VALOR_TOTAL,
          
       case when esi.quantidade <> 0
        then (NVL(ESI.CUSTO_TOTAL,0)/NVL(ESI.QUANTIDADE,0) * NVL(LTA.QUANTIDADE,0)    / OST.QTD_HA_EFETIVO)
        else 0 end AS CUSTO_HA,
          
       SG.DESC_SUB_GRUPO,
       PR.SEQ_PLA_PRODUTO,
       PR.DESCRICAO_PRODUTO,
       UN.SIGLA_UNIDADE,
       LT.LOTE,
       TA.QTDE_HA,
       TS.QTDE_HA AS QTD_HA_EFETIVO,
       0 QUANTIDADE_RECOMENDADA,
       0 DOSE_RECOMENDADA,
       LTA.QUANTIDADE,
       DECODE(NVL(OST.QTD_HA_EFETIVO,0),0,0,NVL(LTA.QUANTIDADE,0)/NVL(OST.QTD_HA_EFETIVO,0)) DOSE,
       OS.VAZAO,
       GT.DESC_GRUPO_TAREFA,
       TAR.DESC_TAREFA,
       FF.NOME,
       DECODE(TAR.DEFENSIVO,'S',
              DECODE(OS.FORMA_APLICACAO_DEFENSIVO,1,'A?rea',2,'Terrestre',3,'A Definir'),
              DECODE(OS.FORMA_APLICACAO_FERTILIZANTE,1,'A?rea',2,'A Lan?o',3,'Em Linha',4,'A Definir')) FORMA_APLICACAO,
       FF1.NOME AS EXECUTOR
FROM MVR.ORDEM_SERVICO         OS,
     MVR.ORDEM_SERV_TALHOES    OST,
     MVR.VINCULA_TAREFA_GRUPO  VTG,
     MVR.TAREFAS               TAR,
     MVR.TALHOES_SAFRA         TS,
     MVR.GRUPO_TAREFAS         GT,
     MVR.FUNCIONARIOS_FAZENDA  FF,
     MVR.FUNCIONARIOS_FAZENDA FF1,
     MVR.TALHOES_SAFRA        TSA,
     MVR.UBS_VARIEDADES       VAA,
     MVR.LIGA_TALHAO_APLICACAO LTA,
     MVR.EST_SAIDAS_ITENS      ESI,
     MVR.EST_SAIDAS            ES,
     MVR.SAFRAS               SA,
     MVR.EMPRESAS             EM,
     MVR.FILIAIS              FI,
     MVR.AGLOMERADOS          AG,
     MVR.REGIOES_GERENCIAIS   RE,
     MVR.FAZENDAS             FA,
     MVR.TALHOES              TA,
     MVR.TIPO_CULTURA         TC,
     MVR.PRODUTOS             PR,
     MVR.SUB_GRUPO            SG,
     MVR.GRUPO                GR,
     MVR.FAMILIAS             FAM,
     MVR.UNIDADE_PRODUTO      UN,
     MVR.PRODUTOS_INSUMOS     PRI,
     MVR.VAZAO                VA,
     MVR.FINALIDADE_ORDEM_SERVICO FN,
     (SELECT esl.seq_pla_sai_item,
               MVR.WM_CONCAT(UL.NR_LOTE) as lote
          FROM MVR.EST_SAIDAS_LOTES ESL, MVR.UBS_LOTES UL
         WHERE ESL.SEQ_PLA_LOTES = UL.SEQ_PLA_LOTES
         GROUP BY ESL.SEQ_PLA_SAI_ITEM
         union
        SELECT esl.seq_pla_sai_item,
               MVR.WM_CONCAT(pl.lote) as lote
          FROM MVR.EST_SAIDAS_LOTES ESL, MVR.produto_lotes pl
         WHERE ESL.SEQ_PLA_LOTE_PRODUTO = pl.seq_pla_lote_produto
         GROUP BY ESL.SEQ_PLA_SAI_ITEM) lt
WHERE OS.SEQ_PLA_ORDEM          = OST.SEQ_PLA_ORDEM
  AND OST.SEQ_PLA_ORDEM_TALHOES = TS.SEQ_PLA_ORDEM_PLANTIO(+)
  AND OS.COD_SAFRA              = SA.COD_SAFRA
  AND OS.SEQ_PLA_FAZENDA        = FA.SEQ_PLA_FAZENDA
  AND OS.SEQ_PLA_VINC_TAREFA    = VTG.SEQ_PLA_VINC_TAREFA
  AND OS.SEQ_PLA_FUNCIONARIO    = FF.SEQ_PLA_FUNCIONARIO(+)
    AND OST.SEQ_PLA_TALHAO_SAFRA = TSA.SEQ_PLA_TALHAO_SAFRA(+)
    AND TSA.SEQ_PLA_VARIEDADE  = VAA.SEQ_PLA_VARIEDADE(+)
  AND OS.SEQ_PLA_FINALIDADE = FN.SEQ_PLA_FINALIDADE(+)
  AND VTG.SEQ_PLA_TAREFA        = TAR.SEQ_PLA_TAREFA
  AND VTG.SEQ_PLA_GRUPO_TAREFA  = GT.SEQ_PLA_GRUPO_TAREFA
  AND OST.SEQ_PLA_TALHAO        = TA.SEQ_PLA_TALHAO
  AND FA.SEQ_PLA_AGLOMERADO     = AG.SEQ_PLA_AGLOMERADO
  AND AG.COD_EMPRESA            = EM.COD_EMPRESA
  AND AG.COD_EMPRESA            = FI.COD_EMPRESA
  AND AG.COD_FILIAL             = FI.COD_FILIAL
  AND AG.SEQ_PLA_REGIAO         = RE.SEQ_PLA_REGIAO(+)
  AND OS.SEQ_PLA_TIPO_CULT      = TC.SEQ_PLA_TIPO_CULT
  AND OST.SEQ_PLA_ORDEM_TALHOES = LTA.SEQ_PLA_ORDEM_TALHAO
  AND LTA.SEQ_PLA_SAI_ITEM      = ESI.SEQ_PLA_SAI_ITEM
  AND ESI.SEQ_PLA_SAIDA         = ES.SEQ_PLA_SAIDA
  AND ESI.SEQ_PLA_PRODUTO       = PR.SEQ_PLA_PRODUTO
  AND PR.SEQ_PLA_SUB_GRUPO      = SG.SEQ_PLA_SUB_GRUPO
  AND SG.SEQ_PLA_GRUPO          = GR.SEQ_PLA_GRUPO
  AND GR.SEQ_PLA_FAMILIA        = FAM.SEQ_PLA_FAMILIA
  AND PR.SEQ_PLA_UNIDADE        = UN.SEQ_PLA_UNIDADE
  and OS.Seq_Pla_Executor       = ff1.seq_pla_funcionario (+)
  AND PR.SEQ_PLA_PRODUTO        = PRI.SEQ_PLA_PRODUTO(+)
  AND OS.SEQ_PLA_VAZAO = VA.SEQ_PLA_VAZAO(+)
  AND ESI.SEQ_PLA_SAI_ITEM = LT.SEQ_PLA_SAI_ITEM(+)
  AND OST.EFETIVO = 'S'
  AND OS.DATA_ENCERRAMENTO IS NOT NULL
order by SA.DESCRICAO_SAFRA, FA.SIGLA_FAZENDA, TA.DESC_TALHAO, OST.EFETIVO_CUMPRIMENTO
) X,
(SELECT 
  COD_SAFRA,             
  SEQ_PLA_FAZENDA,   
  SEQ_PLA_TIPO_CULT,
  SEQ_PLA_TALHAO,
  NUMERO_TALHAO,
  SUM(VALOR_TOTAL) AS VALOR_TOTAL
FROM (
SELECT 
 OS2.SEQ_PLA_ORDEM, 
 OS2.COD_SAFRA,             
 OS2.SEQ_PLA_FAZENDA,   
 OS2.SEQ_PLA_TIPO_CULT,
 OST2.SEQ_PLA_TALHAO,
 TA2.NUMERO_TALHAO,
   CASE
        WHEN TSA2.SEQ_PLA_VARIEDADE IS NULL THEN
          (SELECT mvr.WM_CONCAT(DISTINCT V2.SEQ_PLA_VARIEDADE)
             FROM mvr.RECEITUARIO_SEMENTE S2, mvr.UBS_VARIEDADES V2
            WHERE S2.SEQ_PLA_ORDEM = OS2.SEQ_PLA_ORDEM
              AND S2.SEQ_PLA_VARIEDADE = V2.SEQ_PLA_VARIEDADE)
        ELSE
          VAA2.SEQ_PLA_VARIEDADE
      END AS SEQ_PLA_VARIEDADE,
      
  case when ESI2.quantidade <> 0
  then ( NVL(ESI2.CUSTO_TOTAL,0)/NVL(ESI2.QUANTIDADE,0) * NVL(LTA2.QUANTIDADE,0))
  else 0 end   AS VALOR_TOTAL
          
FROM MVR.ORDEM_SERVICO         OS2,
     MVR.ORDEM_SERV_TALHOES    OST2,
     MVR.TALHOES_SAFRA         TSA2,
     MVR.TALHOES_SAFRA         TS2,
     MVR.UBS_VARIEDADES        VAA2,
     MVR.LIGA_TALHAO_APLICACAO LTA2,
     MVR.EST_SAIDAS_ITENS      ESI2,
     MVR.EST_SAIDAS            ES2,
     MVR.TALHOES               TA2
WHERE OS2.SEQ_PLA_ORDEM          = OST2.SEQ_PLA_ORDEM
  AND OST2.SEQ_PLA_ORDEM_TALHOES = TS2.SEQ_PLA_ORDEM_PLANTIO(+)  
  AND OST2.SEQ_PLA_TALHAO_SAFRA  = TSA2.SEQ_PLA_TALHAO_SAFRA(+)
  AND TSA2.SEQ_PLA_VARIEDADE     = VAA2.SEQ_PLA_VARIEDADE(+)
  AND OST2.SEQ_PLA_TALHAO        = TA2.SEQ_PLA_TALHAO
  AND OST2.SEQ_PLA_ORDEM_TALHOES = LTA2.SEQ_PLA_ORDEM_TALHAO
  AND LTA2.SEQ_PLA_SAI_ITEM      = ESI2.SEQ_PLA_SAI_ITEM
  AND ESI2.SEQ_PLA_SAIDA         = ES2.SEQ_PLA_SAIDA 
  AND OST2.EFETIVO = 'S'
  AND OS2.DATA_ENCERRAMENTO IS NOT NULL) X
  WHERE  
  SEQ_PLA_VARIEDADE IS NULL
GROUP BY
COD_SAFRA,             
SEQ_PLA_FAZENDA,   
SEQ_PLA_TIPO_CULT,
SEQ_PLA_TALHAO,
NUMERO_TALHAO) INTERNA
WHERE  
  SEQ_PLA_VARIEDADE IS NOT NULL
  AND INTERNA.COD_SAFRA         = X.COD_SAFRA
  AND INTERNA.SEQ_PLA_FAZENDA   = X.SEQ_PLA_FAZENDA
  AND INTERNA.SEQ_PLA_TIPO_CULT = X.SEQ_PLA_TIPO_CULT
  AND INTERNA.SEQ_PLA_TALHAO    = X.SEQ_PLA_TALHAO
GROUP BY
  X.COD_SAFRA,
  X.DESCRICAO_SAFRA,
  X.COD_EMPRESA,
  X.NOME_EMPRESA,
  X.SIGLA_EMPRESA,
  X.SEQ_PLA_FAZENDA,
  X.DESC_FAZENDA,
  X.SIGLA_FAZENDA,
  X.SEQ_PLA_TALHAO,
  X.NUMERO_TALHAO,
  X.DESC_TALHAO,
  X.SEQ_PLA_TIPO_CULT,
  X.DESC_CULTURA,
  X.SEQ_PLA_VARIEDADE,
  X.DESC_VARIEDADE