CREATE OR REPLACE VIEW VW_OSPLANTIO AS
SELECT  
      PLANTIO.*,
      (PLANTIO.DATA_PLANTIO + PLANTIO.CICLO) AS PREVISAO_COLHEITA
FROM (
SELECT 
       EM.COD_EMPRESA,
       EM.NOME_EMPRESA,
       EM.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.DESCRICAO_FILIAL,
       SA.COD_SAFRA,
       SA.DESCRICAO_SAFRA,       
       TC.SEQ_PLA_TIPO_CULT,
       TC.DESC_CULTURA,       
       TA.SEQ_PLA_TALHAO,
       TA.DESC_TALHAO,
       TA.NUMERO_TALHAO,
       TS.FINALIZADO,
       UV.SEQ_PLA_VARIEDADE,      
       UV.DESC_VARIEDADE,
       OS.SEQ_PLA_FAZENDA,
       FA.DESC_FAZENDA,
       FA.SIGLA_FAZENDA,
       RE.SEQ_PLA_REGIAO,
       RE.DESC_REGIAO,
       AG.SEQ_PLA_AGLOMERADO,
       AG.SIGLA_AGLOMERADO,   
       TS.SEQ_PLA_TALHAO_SAFRA,
       TS.DATA_PLANTIO,
       GT.SEQ_PLA_GRUPO_TAREFA,
       GT.DESC_GRUPO_TAREFA,
       (SELECT PVR.CICLO
          FROM MVR.PAR_VARIEDADE_REGIAO PVR
         WHERE PVR.COD_SAFRA = SA.COD_SAFRA
           AND PVR.SEQ_PLA_REGIAO = RE.SEQ_PLA_REGIAO
           AND PVR.SEQ_PLA_VARIEDADE = UV.SEQ_PLA_VARIEDADE) CICLO,     
     SUM(TS.QTDE_HA) AS QTD_HA_EFETIVO,
     AVG(RS.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
     SUM(RS.QUANTIDADE) AS QUANTIDADE,
     AVG(RS.ESPACAMENTO) AS ESPACAMENTO,
     DECODE(((SUM(TS.QTDE_HA) * (10000/AVG(RS.ESPACAMENTO))*AVG(RS.SEMENTES_POR_METRO))/1000),0,0, ((SUM(RS.QUANTIDADE) * 1000) /((SUM(TS.QTDE_HA) * (10000/AVG(RS.ESPACAMENTO))*AVG(RS.SEMENTES_POR_METRO))/1000)))as pms
  FROM MVR.ORDEM_SERVICO        OS,
       MVR.ORDEM_SERV_TALHOES   OST,
       MVR.VINCULA_TAREFA_GRUPO VTG,
       MVR.TAREFAS              TAR,
       MVR.GRUPO_TAREFAS        GT,
       MVR.TALHOES_SAFRA        TS,
       MVR.SAFRAS             SA,
       MVR.EMPRESAS           EM,
       MVR.FILIAIS            FI,
       MVR.AGLOMERADOS        AG,
       MVR.REGIOES_GERENCIAIS RE,
       MVR.FAZENDAS           FA,
       MVR.TALHOES            TA,
       MVR.TIPO_CULTURA       TC,
       MVR.UBS_VARIEDADES     UV,

       (SELECT X.SEQ_PLA_ORDEM AS SEQ_PLA_ORDEM,
            X.SEQ_PLA_ORDEM_TALHAO AS SEQ_PLA_ORDEM_TALHAO,
            AVG(X.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
            AVG(X.SEMENTES_PMS) AS SEMENTES_PMS,
            SUM(X.QUANTIDADE) AS QUANTIDADE,
            AVG(X.ESPACAMENTO) AS ESPACAMENTO,
            AVG(X.PMS_LOTE) AS PMS_LOTE
        FROM
          (SELECT RS.SEQ_PLA_ORDEM,
               LT.SEQ_PLA_ORDEM_TALHAO,
               AVG(RS.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
               AVG(RS.SEMENTES_PMS) AS SEMENTES_PMS,
               SUM(LT.QUANTIDADE) AS QUANTIDADE,
               AVG(E.ESPACAMENTO) AS ESPACAMENTO,
               nvl((select avg(ul.sementes_pms)as pms
                 from MVR.est_saidas_lotes sl,
                      MVR.ubs_lotes ul
                where sl.seq_pla_sai_item = ESI.SEQ_PLA_SAI_ITEM
                  and sl.seq_pla_lotes    = ul.seq_pla_lotes),0)as pms_lote
          FROM MVR.RECEITUARIO_SEMENTE   RS,
               MVR.ESPACAMENTO           E,
               MVR.EST_SAIDAS_ITENS      ESI,
               MVR.EST_SAIDAS            ES,
               MVR.LIGA_TALHAO_APLICACAO LT
         WHERE RS.SEQ_PLA_ESPACAMENTO = E.SEQ_PLA_ESPACAMENTO
           AND RS.SEQ_PLA_REC_SEM = ESI.PRODUTO_COMPLEMENTO
           AND ESI.SEQ_PLA_SAIDA = ES.SEQ_PLA_SAIDA
           AND ES.FORM_LANCAMENTO = 'DFMORDEMAPLICACAO'
           AND ESI.SEQ_PLA_SAI_ITEM = LT.SEQ_PLA_SAI_ITEM
         GROUP BY RS.SEQ_PLA_ORDEM, LT.SEQ_PLA_ORDEM_TALHAO, ESI.SEQ_PLA_SAI_ITEM
        UNION ALL
        SELECT RS.SEQ_PLA_ORDEM,
               NULL AS SEQ_PLA_ORDEM_TALHAO,
               AVG(RS.SEMENTES_POR_METRO) AS SEMENTES_POR_METRO,
               AVG(RS.SEMENTES_PMS) AS SEMENTES_PMS,
               SUM(RS.QUANTIDADE) AS QUANTIDADE,
               AVG(E.ESPACAMENTO) AS ESPACAMENTO,
               0 AS PMS_LOTE
          FROM MVR.RECEITUARIO_SEMENTE RS, MVR.ESPACAMENTO E, MVR.ORDEM_SERVICO OSS
         WHERE RS.SEQ_PLA_ESPACAMENTO = E.SEQ_PLA_ESPACAMENTO
           AND RS.SEQ_PLA_ORDEM = OSS.SEQ_PLA_ORDEM
           AND NVL(OSS.TIPO_ORDEM, 'N') = 'S'
         GROUP BY RS.SEQ_PLA_ORDEM) X
     GROUP BY X.SEQ_PLA_ORDEM, X.SEQ_PLA_ORDEM_TALHAO )RS
 WHERE OS.SEQ_PLA_ORDEM = OST.SEQ_PLA_ORDEM
  AND OST.SEQ_PLA_ORDEM_TALHOES = TS.SEQ_PLA_ORDEM_PLANTIO
   AND OST.SEQ_PLA_ORDEM_TALHOES =
       NVL(RS.SEQ_PLA_ORDEM_TALHAO, OST.SEQ_PLA_ORDEM_TALHOES)
   AND OS.COD_SAFRA = SA.COD_SAFRA
   AND OS.SEQ_PLA_FAZENDA = FA.SEQ_PLA_FAZENDA
   AND OS.SEQ_PLA_VINC_TAREFA = VTG.SEQ_PLA_VINC_TAREFA
   AND VTG.SEQ_PLA_TAREFA = TAR.SEQ_PLA_TAREFA
   AND VTG.SEQ_PLA_GRUPO_TAREFA = GT.SEQ_PLA_GRUPO_TAREFA
   AND OST.SEQ_PLA_TALHAO = TA.SEQ_PLA_TALHAO
   AND FA.SEQ_PLA_AGLOMERADO = AG.SEQ_PLA_AGLOMERADO
   AND AG.COD_EMPRESA = EM.COD_EMPRESA
   AND AG.COD_EMPRESA = FI.COD_EMPRESA
   AND AG.COD_FILIAL = FI.COD_FILIAL
   AND AG.SEQ_PLA_REGIAO = RE.SEQ_PLA_REGIAO
   AND TS.SEQ_PLA_TIPO_CULT = TC.SEQ_PLA_TIPO_CULT
   AND TS.SEQ_PLA_VARIEDADE = UV.SEQ_PLA_VARIEDADE
   AND OST.SEQ_PLA_ORDEM = RS.SEQ_PLA_ORDEM(+)
 AND OST.EFETIVO = 'S'
 AND OS.DATA_ENCERRAMENTO IS NOT NULL
   AND (TAR.PLANTIO = 'S' OR TAR.REPLANTIO = 'S')
 GROUP BY 
       EM.COD_EMPRESA,
       EM.NOME_EMPRESA,
       EM.SIGLA_EMPRESA,
       FI.COD_FILIAL,
       FI.DESCRICAO_FILIAL,
       SA.COD_SAFRA,
       SA.DESCRICAO_SAFRA,       
       TC.SEQ_PLA_TIPO_CULT,
       TC.DESC_CULTURA,       
       TA.SEQ_PLA_TALHAO,
       TA.DESC_TALHAO,
       TA.NUMERO_TALHAO,
       TS.FINALIZADO,
       UV.SEQ_PLA_VARIEDADE,      
       UV.DESC_VARIEDADE,
       OS.SEQ_PLA_FAZENDA,
       FA.DESC_FAZENDA,
       FA.SIGLA_FAZENDA,
       RE.SEQ_PLA_REGIAO,
       RE.DESC_REGIAO,
       AG.SEQ_PLA_AGLOMERADO,
       AG.SIGLA_AGLOMERADO,   
       TS.SEQ_PLA_TALHAO_SAFRA,
       TS.DATA_PLANTIO,
       GT.SEQ_PLA_GRUPO_TAREFA,
       GT.DESC_GRUPO_TAREFA,
       TS.SEQ_PLA_TALHAO_SAFRA
          ) PLANTIO
 ORDER BY PLANTIO.SIGLA_EMPRESA, PLANTIO.DESC_REGIAO;
