CREATE OR REPLACE FUNCTION FSOMA_RECEBIDO
   (MSEQ_PLA_RECEBER CHAR, MDATA_BASE DATE) RETURN NUMBER
IS
 MTOTAL_RECEBIDO NUMBER:=0;
BEGIN
   SELECT SUM(VALOR_RECEBIDO) INTO MTOTAL_RECEBIDO
     FROM AGRICOLA.RECEBER_PAGTOS
    WHERE SEQ_PLA_RECEBER = MSEQ_PLA_RECEBER
      AND DATA_REC <= MDATA_BASE;
   RETURN (MTOTAL_RECEBIDO);
END;
