CREATE OR REPLACE FUNCTION FSOMA_PAGO
(MSEQ_PLA_PAGAR CHAR, MDATA_BASE DATE) RETURN NUMBER 
IS 
MTOTAL_PAGO NUMBER:=0; 
BEGIN 
SELECT SUM(A.VALOR_PAGO) INTO MTOTAL_PAGO 
  FROM AGRICOLA.PAGAR_PAGTOS A, 
       AGRICOLA.CONTAS_PAGAR B 
 WHERE A.SEQ_PLA_PAGAR = B.SEQ_PLA_PAGAR 
   AND A.SEQ_PLA_PAGAR = MSEQ_PLA_PAGAR 
   AND NVL(A.CANCELADO,'N') <> 'S' 
   AND TRUNC(A.DATA_PGTO) <= MDATA_BASE 
   AND TRUNC(B.DATA_LCTO) <= MDATA_BASE; 
RETURN (MTOTAL_PAGO); 
END; 
