CREATE MATERIALIZED VIEW VW_FLUXO_CAIXA_RESUMIDO REFRESH FORCE ON DEMAND START WITH SYSDATE NEXT SYSDATE + 10/24/60 AS
SELECT DISTINCT CP.SEQ_PLA_PAGAR AS SEQ_PLANILHA,
       CP.COD_EMPRESA,
       CP.COD_FILIAL,
       CP.COD_SAFRA,
       TRIM(CP.DOCUMENTO) DOCUMENTO,
       TRUNC(Cp.DATA_LCTO) DATA_LCTO,
       CL.Nome_Cliente,
       Round(SUM(NVL(CP.VALOR_DOCUM,0)) - SUM(NVL(CP.VALOR_DESCONTO,0)) + SUM(NVL(CP.VALOR_JUROS,0)) ,2) AS VALOR_DEBITO_LIQUIDO,
       Round(SUM(NVL(CP.VALOR_DOCUM,0)) ,2) AS VALOR_DEBITO,
       0 AS VALOR_CREDITO_LIQUIDO,
       0 as VALOR_CREDITO,
       SUM(NVL(PA.VALOR_PAGO_REAL,0)) AS VLR_DEBITO_PG,
       0 AS VLR_CREDITO_RE
  FROM AGRICOLA.CONTAS_PAGAR       CP,
       AGRICOLA.FIN_HISTORICOS     FH,
       AGRICOLA.CTB_PLANO_CONTAS   PC,
       AGRICOLA.Clientes_Enderecos CD,
       AGRICOLA.Clientes           CL,
       AGRICOLA.PAGAR_PAGTOS       PP,
       (SELECT SUM(NVL(PA.VALOR_PAGO_REAL,0)) VALOR_PAGO_REAL, PA.SEQ_PLA_PAGAR FROM AGRICOLA.PAGAR_PAGTOS PA GROUP BY SEQ_PLA_PAGAR) PA,
       AGRICOLA.FIN_MOVIMENTO      FM,
       AGRICOLA.FIN_CONTAS         FC
 WHERE DECODE(CP.CANCELADO,NULL,'N',CP.CANCELADO)='N'
   AND CP.SEQ_PLA_PAGAR     = PP.SEQ_PLA_PAGAR(+)
   AND CP.SEQ_PLA_PAGAR     = PA.SEQ_PLA_PAGAR(+)
   AND PP.SEQ_PLA_MOV_FIN   = FM.SEQ_PLA_MOV_FIN(+)
   AND FM.SEQ_PLA_FIN_CONTA = FC.SEQ_PLA_FIN_CONTA(+)
   And CP.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST
   And FH.CTB_TABELA        = PC.CTB_TABELA(+)
   And FH.CTB_CONTA         = PC.CTB_CONTA(+)
   And CP.Seq_Pla_Endereco  = CD.Seq_Pla_Endereco
   And CD.Seq_Pla_Cliente   = CL.Seq_Pla_Cliente
   And decode(PP.CANCELADO,null,'N',PP.CANCELADO) <> 'S'
   And decode(FM.CANCELADO,null,'N',FM.CANCELADO) <> 'S'
   AND CP.DATA_LCTO IS NOT NULL
   -- AJUSTADO NA VALIDAÇÃO DO AGNALDO
   --AND Round(DECODE(CP.VALOR_PAGO,NULL,0,nvl(SOMA_PAGO(CP.SEQ_PLA_PAGAR,TO_DATE(SYSDATE,'DD/MM/RRRR')),0)),2)<>Round((CP.VALOR_DOCUM+NVL(CP.Valor_Juros,0)-NVL(CP.Valor_Desconto,0)),2)
   AND ROUND(NVL(CP.VALOR_DOCUM,0) - NVL(PA.VALOR_PAGO_REAL,0),2) <> 0
   AND UPPER(CP.FORM_LANCAMENTO) not in ('DFMFINANCIAMENTOS1','DFMFINANCIAMENTOS')
   AND NVL(CP.PREVISAO,'N') = 'N'
   AND CP.SEQ_PLA_FIN_HIST IN  (SELECT SEQ_PLA_FIN_HIST  FROM AGRICOLA.FIN_HISTORICOS WHERE NVL(ADIANTAMENTO,'N') <> 'S' )
   AND CP.SEQ_PLA_PAGAR NOT IN (SELECT PP1.SEQ_PLA_PAGAR FROM AGRICOLA.VINCULA_RECEBER_COMPENSACAO VR, AGRICOLA.PAGAR_PAGTOS PP1, AGRICOLA.CONTAS_PAGAR CP1 WHERE VR.SEQ_PLA_PAGAR_LCTOS=PP1.SEQ_PLA_PAGAR_LCTOS AND CP1.SEQ_PLA_PAGAR = PP1.SEQ_PLA_PAGAR)
   AND CP.SEQ_PLA_PAGAR NOT IN (SELECT PP1.SEQ_PLA_PAGAR FROM AGRICOLA.VINCULA_PAGAR_COMPENSACAO   VR, AGRICOLA.PAGAR_PAGTOS PP1, AGRICOLA.CONTAS_PAGAR CP1 WHERE VR.SEQ_PLA_PAGAR_LCTOS=PP1.SEQ_PLA_PAGAR_LCTOS AND CP1.SEQ_PLA_PAGAR = PP1.SEQ_PLA_PAGAR)
   --
 GROUP BY PP.SEQ_PLA_PAGAR_LCTOS, CP.SEQ_PLA_PAGAR, TRIM(CP.DOCUMENTO), TRUNC(CP.DATA_LCTO), CL.Nome_Cliente, CP.COD_EMPRESA, CP.COD_FILIAL, CP.COD_SAFRA
UNION
SELECT DISTINCT CR.SEQ_PLA_RECEBER AS SEQ_PLANILHA,
       CR.COD_EMPRESA,
       CR.COD_FILIAL,
       CR.COD_SAFRA,
       TRIM(CR.DOCUMENTO) DOCUMENTO,
       TRUNC(CR.DATA_LCTO) DATA_LCTO,
       CL.Nome_Cliente,
       0 AS VALOR_DEBITO_LIQUIDO,
       0 as VALOR_DEBITO,
       (SUM(nvl(CR.VALOR_DOCUM,0)) - SUM(NVL(CR.VALOR_DESCONTO,0)) + SUM(NVL(CR.VALOR_JUROS,0))) as VALOR_CREDITO_LIQUIDO,
       ROUND(SUM(nvl(CR.VALOR_DOCUM,0)),2) as VALOR_CREDITO,
       0 AS VLR_DEBITO_PG,
       SUM(NVL(RE.VALOR_RECEBIDO_REAL,0)) AS VLR_CREDITO_RE
  FROM AGRICOLA.CONTAS_RECEBER     CR,
       AGRICOLA.FIN_HISTORICOS     FH,
       AGRICOLA.CTB_PLANO_CONTAS   PC,
       AGRICOLA.Clientes_Enderecos CE,
       AGRICOLA.Clientes           CL,
       AGRICOLA.RECEBER_PAGTOS     RP,
       (SELECT SUM(NVL(RE.VALOR_RECEBIDO_REAL,0)) VALOR_RECEBIDO_REAL, RE.SEQ_PLA_RECEBER FROM AGRICOLA.RECEBER_PAGTOS RE GROUP BY RE.SEQ_PLA_RECEBER) RE,
       AGRICOLA.FIN_MOVIMENTO      FM,
       AGRICOLA.FIN_CONTAS         FC
 WHERE CR.SEQ_PLA_FIN_HIST  = FH.SEQ_PLA_FIN_HIST
   And FH.CTB_TABELA        = PC.CTB_TABELA(+)
   And FH.CTB_CONTA         = PC.CTB_CONTA(+)
   AND CR.SEQ_PLA_RECEBER   = RP.SEQ_PLA_RECEBER(+)
   AND CR.SEQ_PLA_RECEBER   = RE.SEQ_PLA_RECEBER(+)
   AND RP.SEQ_PLA_MOV_FIN   = FM.SEQ_PLA_MOV_FIN(+)
   AND FM.SEQ_PLA_FIN_CONTA = FC.SEQ_PLA_FIN_CONTA(+)
   And CR.Seq_Pla_Endereco  = CE.Seq_Pla_Endereco
   And CE.Seq_Pla_Cliente   = CL.Seq_Pla_Cliente
   AND CR.DATA_LCTO IS NOT NULL
   -- AJUSTADO NA VALIDAÇÃO DO AGNALDO
   AND CR.SEQ_PLA_FIN_HIST IN (SELECT SEQ_PLA_FIN_HIST FROM AGRICOLA.FIN_HISTORICOS WHERE NVL(ADIANTAMENTO,'N') <> 'S' )
   AND UPPER(CR.FORM_LANCAMENTO) not in ('DFMFINANCIAMENTOS1')
   AND NVL(CR.PREVISAO,'N') = 'N'
   --AND Round(DECODE(CR.VALOR_RECEBIDO,NULL,0,nvl(SOMA_RECEBIDO(CR.SEQ_PLA_RECEBER,TO_DATE(SYSDATE,'DD/MM/RRRR')),0)),2)<>Round((CR.VALOR_DOCUM+NVL(CR.JUROS_DOCUMENTO,0)-NVL(CR.DESCONTO_DOCUMENTO,0)),2)
   AND ROUND(NVL(CR.VALOR_DOCUM,0) - NVL(RE.VALOR_RECEBIDO_REAL,0),2) <> 0
   --
 GROUP BY RP.SEQ_PLA_REC_LCTOS, CR.SEQ_PLA_RECEBER, TRIM(CR.DOCUMENTO), TRUNC(CR.DATA_LCTO), CL.Nome_Cliente, CR.COD_EMPRESA, CR.COD_FILIAL, CR.COD_SAFRA
  ORDER BY 3,4,2;
